In [1]:
#Author: Hiba Ali 
#E-mail: hhibaa802@gmail.com 
#Purpose: QSS Thesis

In [1]:
#import libraries 
import pandas as pd
import os

In [2]:
#read data
df = pd.read_csv("../data/politicians_list.csv") 
df.head()

,FirstName,LastName,X Handle,St/Dis,Party,Role,Past or current?
0,Alma,Adams,@RepAdams,NC12,D,Representative,Current
1,Robert,Aderholt,@Robert_Aderholt,AL04,R,Representative,Current
2,Pete,Aguilar,@RepPeteAguilar,CA33,D,Representative,Current
3,Mark,Alford,@RepMarkAlford,MO04,R,Representative,Current
4,Rick,Allen,@RepRickAllen,GA12,R,Representative,Current

In [3]:
#check shape
df.shape

#735 users total

(735, 7)

In [4]:
#check for duplicates
duplicates = df.duplicated(subset=['FirstName', 'LastName'], keep=False)

#show rows that are duplicate
df[duplicates]

,FirstName,LastName,X Handle,St/Dis,Party,Role,Past or current?
74,Lou,Correa,@RepLouCorrea,CA46,D,Representative,Current
159,Morgan,Griffith,@RepMGriffith,VA09,R,Representative,Current
438,Jim,Banks,@SenatorBanks,IN,R,Senate,Current
499,Markwayne,Mullin,@SenMullin,OK,R,Senate,Current
521,Elissa,Slotkin,@SenatorSlotkin,MI,D,Senate,Current
644,Elissa,Slotkin,@SenatorSlotkin,NaN,D,Representative,Past
654,Morgan,Griffith,@RepMGriffith,NaN,R,Representative,Past
656,Lou,Correa,@RepLouCorrea,NaN,D,Representative,Past
669,Jim,Banks,@Jim_Banks,NaN,R,Representative,Past
695,Markwayne,Mullin,@MarkwayneMullin,NaN,R,Representative,Past

In [5]:
df = df.dropna(subset=['X Handle'])
df.shape #now have 723 politicians

(723, 7)

In [11]:
#drop duplicates

# Drop rows with specific indices
rows_to_drop = [644, 654, 656, 669, 695]
df = df.drop(index=rows_to_drop)

# Optional: reset the index
df = df.reset_index(drop=True)

df['X Handle'] = df['X Handle'].str.replace('@', '', regex=False)

print(df.shape)
#now have 718 politicians)

(718, 7)

In [1045]:
df.to_csv("df.csv", index=False)

In [13]:
# Separate the groups
sen_rep = df[df['Role'].isin(['Senator', 'Representative'])]
other = df[~df['Role'].isin(['Senator', 'Representative'])]

# Randomly sample 202 Senators/Representatives out of the 670 total, about 30%
sen_rep_sample = sen_rep.sample(n=202, random_state=42)

# Combine with all other roles
final_df = pd.concat([sen_rep_sample, other], ignore_index=True)

print(final_df.shape)  # Should be 350

(350, 7)

In [15]:
# Remove '@' from 'X Handle' column
final_df['X Handle'] = final_df['X Handle'].str.replace('@', '', regex=False)

In [ ]:
PULLING HEALTH-RELATED TWEETS AND SAVING THEM

In [23]:
import requests
import time
import json

API_BASE_URL = "https://api.data365.co"
API_VERSION = "/v1.1"
API_AUTHORIZATION_TOKEN = "ZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKSVV6STFOaUo5LmV5SnpkV0lpT2lKSWFXSmhRV3hwSWl3aWFXRjBJam94TnpZNU5UQTNOamcyTGpBd05UQXhPSDAuNmpTLTZtbVBGV0F1ZS1McHhXaUIwbUtDUWFDemU4VkRNZVhOSkZ2ckJRTQ=="

In [25]:
# Map shortcut numbers to keyword blocks
KEYWORD_BLOCKS = {
    "1A": "health OR medicine OR medical OR medication",
    "1B": "treatment OR symptoms OR diagnosis",
    "2A": "healthcare OR insurance OR medicare OR medicaid",
    "2B": "premiums OR coverage OR patients OR hospitals",
    "3": "flu OR pneumonia OR bronchitis OR strep throat OR sore throat OR cough OR fever OR infection OR contagious",
    "4": "high blood pressure OR hypertension OR heart OR heart disease OR heart rate OR stroke OR cholesterol OR diabetes OR cancer",
    "5": "lupus OR autoimmune OR chronic illness OR inflammation OR immune system",
    "6": "hydration OR diet OR nutrition OR exercise OR workout OR sleep OR wellness"
}

In [1015]:
import time
import requests

shortcut = "1A"  
keywords = KEYWORD_BLOCKS[shortcut]

update_url = f"{API_BASE_URL}{API_VERSION}/twitter/search/post/update"
posts_url = f"{API_BASE_URL}{API_VERSION}/twitter/search/post/posts"

params = {
    "from_profile": "Liz_Cheney",
    "from_date": "2022-01-01",
    "to_date": "2025-12-31",
    "lang": "en",
    "max_posts": 20,
    "search_type": "latest",
    "max_replies": 3,
    "load_replies": "true",
    "keywords": keywords,
    "access_token": API_AUTHORIZATION_TOKEN
}

# Start the search task
post_response = requests.post(update_url, params=params)
print("Task started:", post_response.status_code)

# Poll for results
max_attempts = 10
attempt = 0
data = {}

while attempt < max_attempts:
    posts_response = requests.get(posts_url, params=params)
    if posts_response.status_code == 200:
        data = posts_response.json()
        items = data.get("data", {}).get("items", [])
        if items:
            print(f"Number of items retrieved: {len(items)}")
            break
        else:
            print(f"Attempt {attempt+1}: No tweets yet, waiting...")
    else:
        print(f"Failed to fetch posts (attempt {attempt+1}):", posts_response.status_code)
    
    attempt += 1
    time.sleep(2)  # wait 2 seconds before next attempt

if not data.get("data", {}).get("items"):
    print("No tweets were retrieved after polling.")

Task started: 202
Attempt 1: No tweets yet, waiting...
Attempt 2: No tweets yet, waiting...
Attempt 3: No tweets yet, waiting...
Attempt 4: No tweets yet, waiting...
Attempt 5: No tweets yet, waiting...
Attempt 6: No tweets yet, waiting...
Attempt 7: No tweets yet, waiting...
Attempt 8: No tweets yet, waiting...
Attempt 9: No tweets yet, waiting...
Attempt 10: No tweets yet, waiting...
No tweets were retrieved after polling.

In [915]:
print(json.dumps(data, indent=4))

{
    "data": {
        "items": [],
        "page_info": {
            "cursor": null,
            "has_next_page": false
        }
    },
    "error": null,
    "status": "ok"
}

In [983]:
politician_name = "RepJoeCourtney"   
block_name = shortcut          

filename = f"{politician_name} Block {block_name}.json"

with open(filename, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=4)

print(f"Saved results to: {filename}")

Saved results to: RepJoeCourtney Block 6.json

In [ ]:
PULLING HEALTH-RELATED TWEET REPLIES AND SAVING THEM

In [985]:
username = "RepJoeCourtney"
input_filename = "RepJoeCourtney Block 6.json"
output_filename = "RepJoeCourtney Block 6 Replies.json"

# ------------------------------------
# 1. Open the saved block file
# ------------------------------------
with open(input_filename, "r", encoding="utf-8") as f:
    block_data = json.load(f)

posts = block_data.get("data", {}).get("items", [])

all_replies_output = []

# ------------------------------------
# 2. Extract every conversation_id
# ------------------------------------
for post in posts:
    conversation_id = post.get("conversation_id")

    if not conversation_id:
        continue

    print(f"Fetching replies for post {conversation_id}")

    # ------------------------------------
    # 3. Call replies endpoint
    # ------------------------------------
    replies_url = f"{API_BASE_URL}{API_VERSION}/twitter/profile/{username}/feed/posts/{conversation_id}/replies"

    params = {
        "order_by": "date_desc",
        "max_page_size": 50,
        "access_token": API_AUTHORIZATION_TOKEN
    }

    response = requests.get(replies_url, params=params)

    if response.status_code == 200:
        replies_json = response.json()
        replies_items = replies_json.get("data", {}).get("items", [])

        all_replies_output.append({
            "conversation_id": conversation_id,
            "replies": replies_items
        })

    else:
        print(f"Failed to fetch replies for {conversation_id}: {response.status_code}")

    time.sleep(1)  # small pause to avoid rate limits

# ------------------------------------
# 4. Save everything into new JSON file
# ------------------------------------
final_output = {
    "politician": username,
    "block": "6",
    "posts": all_replies_output
}

with open(output_filename, "w", encoding="utf-8") as f:
    json.dump(final_output, f, indent=4)

print("Replies file successfully created.")

Fetching replies for post 1489708580613804052
Fetching replies for post 1534524266871398401
Fetching replies for post 1573385180416716800
Fetching replies for post 1798126941448581254
Fetching replies for post 1958677352549892527
Replies file successfully created.

In [ ]:
AUTOMATING HEALTH-RELATED POSTS

In [1013]:
import pandas as pd
import requests
import time
import json

API_BASE_URL = "https://api.data365.co"
API_VERSION = "/v1.1"
API_AUTHORIZATION_TOKEN = "ZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKSVV6STFOaUo5LmV5SnpkV0lpT2lKSWFXSmhRV3hwSWl3aWFXRjBJam94TnpZNU5UQTNOamcyTGpBd05UQXhPSDAuNmpTLTZtbVBGV0F1ZS1McHhXaUIwbUtDUWFDemU4VkRNZVhOSkZ2ckJRTQ=="

# Keyword blocks
KEYWORD_BLOCKS = {
    "1A": "health OR medicine OR medical OR medication",
    "1B": "treatment OR symptoms OR diagnosis",
    "2A": "healthcare OR insurance OR medicare OR medicaid",
    "2B": "premiums OR coverage OR patients OR hospitals",
    "3": "flu OR pneumonia OR bronchitis OR strep throat OR sore throat OR cough OR fever OR infection OR contagious",
    "4": "high blood pressure OR hypertension OR heart OR heart disease OR heart rate OR stroke OR cholesterol OR diabetes OR cancer",
    "5": "lupus OR autoimmune OR chronic illness OR inflammation OR immune system",
    "6": "hydration OR diet OR nutrition OR exercise OR workout OR sleep OR wellness"
}

# ------------------------
# Function to fetch posts only
# ------------------------
def fetch_posts(username, block_name, keywords, max_attempts=10, sleep_time=2):
    update_url = f"{API_BASE_URL}{API_VERSION}/twitter/search/post/update"
    posts_url = f"{API_BASE_URL}{API_VERSION}/twitter/search/post/posts"

    params = {
        "from_profile": username,
        "from_date": "2022-01-01",
        "to_date": "2025-12-31",
        "lang": "en",
        "max_posts": 20,
        "search_type": "latest",
        "max_replies": 3,
        "load_replies": "true",
        "keywords": keywords,
        "access_token": API_AUTHORIZATION_TOKEN
    }

    # Start the search task
    post_response = requests.post(update_url, params=params)
    print(f"Task started for {username} Block {block_name}: {post_response.status_code}")

    attempt = 0
    data = {}
    while attempt < max_attempts:
        posts_response = requests.get(posts_url, params=params)
        if posts_response.status_code == 200:
            data = posts_response.json()
            items = data.get("data", {}).get("items", [])
            if items:
                print(f"{username} Block {block_name}: Retrieved {len(items)} posts")
                break
            else:
                print(f"{username} Block {block_name}, attempt {attempt+1}: No posts yet...")
        else:
            print(f"Failed to fetch posts for {username} (attempt {attempt+1}): {posts_response.status_code}")
        attempt += 1
        time.sleep(sleep_time)

    items = data.get("data", {}).get("items", [])
    if items:
        filename = f"{username} Block {block_name}.json"
        with open(filename, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4)
        print(f"Saved posts to {filename}")
    else:
        print(f"No posts found for {username} Block {block_name}, skipping save.")

    return items

# ------------------------
# Main Execution
# ------------------------
# Assuming final_df is your DataFrame with a 'X Handle' column
start_username = "SecDebHaaland"
start_index = final_df.index[final_df['X Handle'] == start_username][0]

for username in final_df['X Handle'].iloc[start_index:]:
    print(f"\n=== Processing {username} ===")
    for block_name, keywords in KEYWORD_BLOCKS.items():
        fetch_posts(username, block_name, keywords)

=== Processing SecDebHaaland ===
Task started for SecDebHaaland Block 1A: 202
SecDebHaaland Block 1A: Retrieved 20 posts
Saved posts to SecDebHaaland Block 1A.json
Task started for SecDebHaaland Block 1B: 202
SecDebHaaland Block 1B, attempt 1: No posts yet...
SecDebHaaland Block 1B, attempt 2: No posts yet...
SecDebHaaland Block 1B, attempt 3: No posts yet...
SecDebHaaland Block 1B, attempt 4: No posts yet...
SecDebHaaland Block 1B, attempt 5: No posts yet...
SecDebHaaland Block 1B: Retrieved 2 posts
Saved posts to SecDebHaaland Block 1B.json
Task started for SecDebHaaland Block 2A: 202
SecDebHaaland Block 2A, attempt 1: No posts yet...
SecDebHaaland Block 2A, attempt 2: No posts yet...
SecDebHaaland Block 2A, attempt 3: No posts yet...
SecDebHaaland Block 2A, attempt 4: No posts yet...
SecDebHaaland Block 2A, attempt 5: No posts yet...
SecDebHaaland Block 2A: Retrieved 4 posts
Saved posts to SecDebHaaland Block 2A.json
Task started for SecDebHaaland Block 2B: 202
SecDebHaaland Block 2B, attempt 1: No posts yet...
SecDebHaaland Block 2B, attempt 2: No posts yet...
SecDebHaaland Block 2B, attempt 3: No posts yet...
SecDebHaaland Block 2B, attempt 4: No posts yet...
SecDebHaaland Block 2B, attempt 5: No posts yet...
SecDebHaaland Block 2B, attempt 6: No posts yet...
SecDebHaaland Block 2B: Retrieved 3 posts
Saved posts to SecDebHaaland Block 2B.json
Task started for SecDebHaaland Block 3: 202
SecDebHaaland Block 3, attempt 1: No posts yet...
SecDebHaaland Block 3, attempt 2: No posts yet...
SecDebHaaland Block 3, attempt 3: No posts yet...
SecDebHaaland Block 3, attempt 4: No posts yet...
SecDebHaaland Block 3, attempt 5: No posts yet...
SecDebHaaland Block 3, attempt 6: No posts yet...
SecDebHaaland Block 3, attempt 7: No posts yet...
SecDebHaaland Block 3, attempt 8: No posts yet...
SecDebHaaland Block 3, attempt 9: No posts yet...
SecDebHaaland Block 3, attempt 10: No posts yet...
No posts found for SecDebHaaland Block 3, skipping save.
Task started for SecDebHaaland Block 4: 202
SecDebHaaland Block 4, attempt 1: No posts yet...
SecDebHaaland Block 4, attempt 2: No posts yet...
SecDebHaaland Block 4, attempt 3: No posts yet...
SecDebHaaland Block 4, attempt 4: No posts yet...
SecDebHaaland Block 4, attempt 5: No posts yet...
SecDebHaaland Block 4, attempt 6: No posts yet...
SecDebHaaland Block 4, attempt 7: No posts yet...
SecDebHaaland Block 4, attempt 8: No posts yet...
SecDebHaaland Block 4, attempt 9: No posts yet...
SecDebHaaland Block 4, attempt 10: No posts yet...
No posts found for SecDebHaaland Block 4, skipping save.
Task started for SecDebHaaland Block 5: 202
SecDebHaaland Block 5, attempt 1: No posts yet...
SecDebHaaland Block 5, attempt 2: No posts yet...
SecDebHaaland Block 5, attempt 3: No posts yet...
SecDebHaaland Block 5, attempt 4: No posts yet...
SecDebHaaland Block 5, attempt 5: No posts yet...
SecDebHaaland Block 5, attempt 6: No posts yet...
SecDebHaaland Block 5, attempt 7: No posts yet...
SecDebHaaland Block 5, attempt 8: No posts yet...
SecDebHaaland Block 5, attempt 9: No posts yet...
SecDebHaaland Block 5, attempt 10: No posts yet...
No posts found for SecDebHaaland Block 5, skipping save.
Task started for SecDebHaaland Block 6: 202
SecDebHaaland Block 6, attempt 1: No posts yet...
SecDebHaaland Block 6, attempt 2: No posts yet...
SecDebHaaland Block 6, attempt 3: No posts yet...
SecDebHaaland Block 6, attempt 4: No posts yet...
SecDebHaaland Block 6, attempt 5: No posts yet...
SecDebHaaland Block 6: Retrieved 4 posts
Saved posts to SecDebHaaland Block 6.json

=== Processing SecYellen ===
Task started for SecYellen Block 1A: 202
SecYellen Block 1A, attempt 1: No posts yet...
SecYellen Block 1A, attempt 2: No posts yet...
SecYellen Block 1A, attempt 3: No posts yet...
SecYellen Block 1A, attempt 4: No posts yet...
SecYellen Block 1A, attempt 5: No posts yet...
SecYellen Block 1A: Retrieved 20 posts
Saved posts to SecYellen Block 1A.json
Task started for SecYellen Block 1B: 202
SecYellen Block 1B, attempt 1: No posts yet...
SecYellen Block 1B, attempt 2: No posts yet...
SecYellen Block 1B, attempt 3: No posts yet...
SecYellen Block 1B: Retrieved 1 posts
Saved posts to SecYellen Block 1B.json
Task started for SecYellen Block 2A: 202
SecYellen Block 2A, attempt 1: No posts yet...
SecYellen Block 2A, attempt 2: No posts yet...
SecYellen Block 2A, attempt 3: No posts yet...
SecYellen Block 2A, attempt 4: No posts yet...
SecYellen Block 2A, attempt 5: No posts yet...
SecYellen Block 2A: Retrieved 6 posts
Saved posts to SecYellen Block 2A.json
Task started for SecYellen Block 2B: 202
SecYellen Block 2B, attempt 1: No posts yet...
SecYellen Block 2B, attempt 2: No posts yet...
SecYellen Block 2B, attempt 3: No posts yet...
SecYellen Block 2B, attempt 4: No posts yet...
SecYellen Block 2B, attempt 5: No posts yet...
SecYellen Block 2B, attempt 6: No posts yet...
SecYellen Block 2B: Retrieved 7 posts
Saved posts to SecYellen Block 2B.json
Task started for SecYellen Block 3: 202
SecYellen Block 3, attempt 1: No posts yet...
SecYellen Block 3, attempt 2: No posts yet...
SecYellen Block 3, attempt 3: No posts yet...
SecYellen Block 3, attempt 4: No posts yet...
SecYellen Block 3, attempt 5: No posts yet...
SecYellen Block 3, attempt 6: No posts yet...
SecYellen Block 3, attempt 7: No posts yet...
SecYellen Block 3, attempt 8: No posts yet...
SecYellen Block 3, attempt 9: No posts yet...
SecYellen Block 3, attempt 10: No posts yet...
No posts found for SecYellen Block 3, skipping save.
Task started for SecYellen Block 4: 202
SecYellen Block 4, attempt 1: No posts yet...
SecYellen Block 4, attempt 2: No posts yet...
SecYellen Block 4, attempt 3: No posts yet...
SecYellen Block 4, attempt 4: No posts yet...
SecYellen Block 4, attempt 5: No posts yet...
SecYellen Block 4, attempt 6: No posts yet...
SecYellen Block 4, attempt 7: No posts yet...
SecYellen Block 4, attempt 8: No posts yet...
SecYellen Block 4, attempt 9: No posts yet...
SecYellen Block 4, attempt 10: No posts yet...
No posts found for SecYellen Block 4, skipping save.
Task started for SecYellen Block 5: 202
SecYellen Block 5, attempt 1: No posts yet...
SecYellen Block 5, attempt 2: No posts yet...
SecYellen Block 5, attempt 3: No posts yet...
SecYellen Block 5, attempt 4: No posts yet...
SecYellen Block 5, attempt 5: No posts yet...
SecYellen Block 5, attempt 6: No posts yet...
SecYellen Block 5, attempt 7: No posts yet...
SecYellen Block 5, attempt 8: No posts yet...
SecYellen Block 5, attempt 9: No posts yet...
SecYellen Block 5, attempt 10: No posts yet...
No posts found for SecYellen Block 5, skipping save.
Task started for SecYellen Block 6: 202
SecYellen Block 6, attempt 1: No posts yet...
SecYellen Block 6, attempt 2: No posts yet...
SecYellen Block 6, attempt 3: No posts yet...
SecYellen Block 6, attempt 4: No posts yet...
SecYellen Block 6, attempt 5: No posts yet...
SecYellen Block 6, attempt 6: No posts yet...
SecYellen Block 6, attempt 7: No posts yet...
SecYellen Block 6, attempt 8: No posts yet...
SecYellen Block 6, attempt 9: No posts yet...
SecYellen Block 6, attempt 10: No posts yet...
No posts found for SecYellen Block 6, skipping save.

=== Processing PeteButtigieg ===
Task started for PeteButtigieg Block 1A: 202
PeteButtigieg Block 1A, attempt 1: No posts yet...
PeteButtigieg Block 1A, attempt 2: No posts yet...
PeteButtigieg Block 1A, attempt 3: No posts yet...
PeteButtigieg Block 1A, attempt 4: No posts yet...
PeteButtigieg Block 1A, attempt 5: No posts yet...
PeteButtigieg Block 1A, attempt 6: No posts yet...
PeteButtigieg Block 1A, attempt 7: No posts yet...
PeteButtigieg Block 1A: Retrieved 20 posts
Saved posts to PeteButtigieg Block 1A.json
Task started for PeteButtigieg Block 1B: 202
PeteButtigieg Block 1B, attempt 1: No posts yet...
PeteButtigieg Block 1B, attempt 2: No posts yet...
PeteButtigieg Block 1B, attempt 3: No posts yet...
PeteButtigieg Block 1B, attempt 4: No posts yet...
PeteButtigieg Block 1B, attempt 5: No posts yet...
PeteButtigieg Block 1B, attempt 6: No posts yet...
PeteButtigieg Block 1B, attempt 7: No posts yet...
PeteButtigieg Block 1B, attempt 8: No posts yet...
PeteButtigieg Block 1B, attempt 9: No posts yet...
PeteButtigieg Block 1B, attempt 10: No posts yet...
No posts found for PeteButtigieg Block 1B, skipping save.
Task started for PeteButtigieg Block 2A: 202
PeteButtigieg Block 2A, attempt 1: No posts yet...
PeteButtigieg Block 2A, attempt 2: No posts yet...
PeteButtigieg Block 2A, attempt 3: No posts yet...
PeteButtigieg Block 2A, attempt 4: No posts yet...
PeteButtigieg Block 2A, attempt 5: No posts yet...
PeteButtigieg Block 2A, attempt 6: No posts yet...
PeteButtigieg Block 2A: Retrieved 20 posts
Saved posts to PeteButtigieg Block 2A.json
Task started for PeteButtigieg Block 2B: 202
PeteButtigieg Block 2B, attempt 1: No posts yet...
PeteButtigieg Block 2B, attempt 2: No posts yet...
PeteButtigieg Block 2B, attempt 3: No posts yet...
PeteButtigieg Block 2B, attempt 4: No posts yet...
PeteButtigieg Block 2B, attempt 5: No posts yet...
PeteButtigieg Block 2B, attempt 6: No posts yet...
PeteButtigieg Block 2B, attempt 7: No posts yet...
PeteButtigieg Block 2B, attempt 8: No posts yet...
PeteButtigieg Block 2B: Retrieved 8 posts
Saved posts to PeteButtigieg Block 2B.json
Task started for PeteButtigieg Block 3: 202
PeteButtigieg Block 3, attempt 1: No posts yet...
PeteButtigieg Block 3, attempt 2: No posts yet...
PeteButtigieg Block 3, attempt 3: No posts yet...
PeteButtigieg Block 3, attempt 4: No posts yet...
PeteButtigieg Block 3, attempt 5: No posts yet...
PeteButtigieg Block 3, attempt 6: No posts yet...
PeteButtigieg Block 3, attempt 7: No posts yet...
PeteButtigieg Block 3, attempt 8: No posts yet...
PeteButtigieg Block 3, attempt 9: No posts yet...
PeteButtigieg Block 3, attempt 10: No posts yet...
No posts found for PeteButtigieg Block 3, skipping save.
Task started for PeteButtigieg Block 4: 202
PeteButtigieg Block 4, attempt 1: No posts yet...
PeteButtigieg Block 4, attempt 2: No posts yet...
PeteButtigieg Block 4, attempt 3: No posts yet...
PeteButtigieg Block 4, attempt 4: No posts yet...
PeteButtigieg Block 4, attempt 5: No posts yet...
PeteButtigieg Block 4, attempt 6: No posts yet...
PeteButtigieg Block 4, attempt 7: No posts yet...
PeteButtigieg Block 4, attempt 8: No posts yet...
PeteButtigieg Block 4, attempt 9: No posts yet...
PeteButtigieg Block 4, attempt 10: No posts yet...
No posts found for PeteButtigieg Block 4, skipping save.
Task started for PeteButtigieg Block 5: 202
PeteButtigieg Block 5, attempt 1: No posts yet...
PeteButtigieg Block 5, attempt 2: No posts yet...
PeteButtigieg Block 5, attempt 3: No posts yet...
PeteButtigieg Block 5, attempt 4: No posts yet...
PeteButtigieg Block 5, attempt 5: No posts yet...
PeteButtigieg Block 5, attempt 6: No posts yet...
PeteButtigieg Block 5, attempt 7: No posts yet...
PeteButtigieg Block 5, attempt 8: No posts yet...
PeteButtigieg Block 5, attempt 9: No posts yet...
PeteButtigieg Block 5, attempt 10: No posts yet...
No posts found for PeteButtigieg Block 5, skipping save.
Task started for PeteButtigieg Block 6: 202
PeteButtigieg Block 6, attempt 1: No posts yet...
PeteButtigieg Block 6, attempt 2: No posts yet...
PeteButtigieg Block 6, attempt 3: No posts yet...
PeteButtigieg Block 6, attempt 4: No posts yet...
PeteButtigieg Block 6, attempt 5: No posts yet...
PeteButtigieg Block 6, attempt 6: No posts yet...
PeteButtigieg Block 6, attempt 7: No posts yet...
PeteButtigieg Block 6, attempt 8: No posts yet...
PeteButtigieg Block 6, attempt 9: No posts yet...
PeteButtigieg Block 6, attempt 10: No posts yet...
No posts found for PeteButtigieg Block 6, skipping save.

=== Processing DenisMcDonough ===
Task started for DenisMcDonough Block 1A: 202
DenisMcDonough Block 1A, attempt 1: No posts yet...
DenisMcDonough Block 1A, attempt 2: No posts yet...
DenisMcDonough Block 1A, attempt 3: No posts yet...
DenisMcDonough Block 1A, attempt 4: No posts yet...
DenisMcDonough Block 1A, attempt 5: No posts yet...
DenisMcDonough Block 1A, attempt 6: No posts yet...
DenisMcDonough Block 1A, attempt 7: No posts yet...
DenisMcDonough Block 1A, attempt 8: No posts yet...
DenisMcDonough Block 1A, attempt 9: No posts yet...
DenisMcDonough Block 1A, attempt 10: No posts yet...
No posts found for DenisMcDonough Block 1A, skipping save.
Task started for DenisMcDonough Block 1B: 202
DenisMcDonough Block 1B, attempt 1: No posts yet...
DenisMcDonough Block 1B, attempt 2: No posts yet...
DenisMcDonough Block 1B, attempt 3: No posts yet...
DenisMcDonough Block 1B, attempt 4: No posts yet...
DenisMcDonough Block 1B, attempt 5: No posts yet...
DenisMcDonough Block 1B, attempt 6: No posts yet...
DenisMcDonough Block 1B, attempt 7: No posts yet...
DenisMcDonough Block 1B, attempt 8: No posts yet...
DenisMcDonough Block 1B, attempt 9: No posts yet...
DenisMcDonough Block 1B, attempt 10: No posts yet...
No posts found for DenisMcDonough Block 1B, skipping save.
Task started for DenisMcDonough Block 2A: 202
DenisMcDonough Block 2A, attempt 1: No posts yet...
DenisMcDonough Block 2A, attempt 2: No posts yet...
DenisMcDonough Block 2A, attempt 3: No posts yet...
DenisMcDonough Block 2A, attempt 4: No posts yet...
DenisMcDonough Block 2A, attempt 5: No posts yet...
DenisMcDonough Block 2A, attempt 6: No posts yet...
DenisMcDonough Block 2A, attempt 7: No posts yet...
DenisMcDonough Block 2A, attempt 8: No posts yet...
DenisMcDonough Block 2A, attempt 9: No posts yet...
DenisMcDonough Block 2A, attempt 10: No posts yet...
No posts found for DenisMcDonough Block 2A, skipping save.
Task started for DenisMcDonough Block 2B: 202
DenisMcDonough Block 2B, attempt 1: No posts yet...
DenisMcDonough Block 2B, attempt 2: No posts yet...
DenisMcDonough Block 2B, attempt 3: No posts yet...
DenisMcDonough Block 2B, attempt 4: No posts yet...
DenisMcDonough Block 2B, attempt 5: No posts yet...
DenisMcDonough Block 2B, attempt 6: No posts yet...
DenisMcDonough Block 2B, attempt 7: No posts yet...
DenisMcDonough Block 2B, attempt 8: No posts yet...
DenisMcDonough Block 2B, attempt 9: No posts yet...
DenisMcDonough Block 2B, attempt 10: No posts yet...
No posts found for DenisMcDonough Block 2B, skipping save.
Task started for DenisMcDonough Block 3: 202
DenisMcDonough Block 3, attempt 1: No posts yet...
DenisMcDonough Block 3, attempt 2: No posts yet...
DenisMcDonough Block 3, attempt 3: No posts yet...
DenisMcDonough Block 3, attempt 4: No posts yet...
DenisMcDonough Block 3, attempt 5: No posts yet...
DenisMcDonough Block 3, attempt 6: No posts yet...
DenisMcDonough Block 3, attempt 7: No posts yet...
DenisMcDonough Block 3, attempt 8: No posts yet...
DenisMcDonough Block 3, attempt 9: No posts yet...
DenisMcDonough Block 3, attempt 10: No posts yet...
No posts found for DenisMcDonough Block 3, skipping save.
Task started for DenisMcDonough Block 4: 202
DenisMcDonough Block 4, attempt 1: No posts yet...
DenisMcDonough Block 4, attempt 2: No posts yet...
DenisMcDonough Block 4, attempt 3: No posts yet...
DenisMcDonough Block 4, attempt 4: No posts yet...
DenisMcDonough Block 4, attempt 5: No posts yet...
DenisMcDonough Block 4, attempt 6: No posts yet...
DenisMcDonough Block 4, attempt 7: No posts yet...
DenisMcDonough Block 4, attempt 8: No posts yet...
DenisMcDonough Block 4, attempt 9: No posts yet...
DenisMcDonough Block 4, attempt 10: No posts yet...
No posts found for DenisMcDonough Block 4, skipping save.
Task started for DenisMcDonough Block 5: 202
DenisMcDonough Block 5, attempt 1: No posts yet...
DenisMcDonough Block 5, attempt 2: No posts yet...
DenisMcDonough Block 5, attempt 3: No posts yet...
DenisMcDonough Block 5, attempt 4: No posts yet...
DenisMcDonough Block 5, attempt 5: No posts yet...
DenisMcDonough Block 5, attempt 6: No posts yet...
DenisMcDonough Block 5, attempt 7: No posts yet...
DenisMcDonough Block 5, attempt 8: No posts yet...
DenisMcDonough Block 5, attempt 9: No posts yet...
DenisMcDonough Block 5, attempt 10: No posts yet...
No posts found for DenisMcDonough Block 5, skipping save.
Task started for DenisMcDonough Block 6: 202
DenisMcDonough Block 6, attempt 1: No posts yet...
DenisMcDonough Block 6, attempt 2: No posts yet...
DenisMcDonough Block 6, attempt 3: No posts yet...
DenisMcDonough Block 6, attempt 4: No posts yet...
DenisMcDonough Block 6, attempt 5: No posts yet...
DenisMcDonough Block 6, attempt 6: No posts yet...
DenisMcDonough Block 6, attempt 7: No posts yet...
DenisMcDonough Block 6, attempt 8: No posts yet...
DenisMcDonough Block 6, attempt 9: No posts yet...
DenisMcDonough Block 6, attempt 10: No posts yet...
No posts found for DenisMcDonough Block 6, skipping save.

=== Processing AmbassadorTai ===
Task started for AmbassadorTai Block 1A: 202
AmbassadorTai Block 1A, attempt 1: No posts yet...
AmbassadorTai Block 1A, attempt 2: No posts yet...
AmbassadorTai Block 1A, attempt 3: No posts yet...
AmbassadorTai Block 1A, attempt 4: No posts yet...
AmbassadorTai Block 1A, attempt 5: No posts yet...
AmbassadorTai Block 1A, attempt 6: No posts yet...
AmbassadorTai Block 1A, attempt 7: No posts yet...
AmbassadorTai Block 1A: Retrieved 4 posts
Saved posts to AmbassadorTai Block 1A.json
Task started for AmbassadorTai Block 1B: 202
AmbassadorTai Block 1B, attempt 1: No posts yet...
AmbassadorTai Block 1B, attempt 2: No posts yet...
AmbassadorTai Block 1B, attempt 3: No posts yet...
AmbassadorTai Block 1B, attempt 4: No posts yet...
AmbassadorTai Block 1B, attempt 5: No posts yet...
AmbassadorTai Block 1B, attempt 6: No posts yet...
AmbassadorTai Block 1B, attempt 7: No posts yet...
AmbassadorTai Block 1B, attempt 8: No posts yet...
AmbassadorTai Block 1B, attempt 9: No posts yet...
AmbassadorTai Block 1B, attempt 10: No posts yet...
No posts found for AmbassadorTai Block 1B, skipping save.
Task started for AmbassadorTai Block 2A: 202
AmbassadorTai Block 2A, attempt 1: No posts yet...
AmbassadorTai Block 2A, attempt 2: No posts yet...
AmbassadorTai Block 2A, attempt 3: No posts yet...
AmbassadorTai Block 2A, attempt 4: No posts yet...
AmbassadorTai Block 2A, attempt 5: No posts yet...
AmbassadorTai Block 2A, attempt 6: No posts yet...
AmbassadorTai Block 2A, attempt 7: No posts yet...
AmbassadorTai Block 2A, attempt 8: No posts yet...
AmbassadorTai Block 2A: Retrieved 1 posts
Saved posts to AmbassadorTai Block 2A.json
Task started for AmbassadorTai Block 2B: 202
AmbassadorTai Block 2B, attempt 1: No posts yet...
AmbassadorTai Block 2B, attempt 2: No posts yet...
AmbassadorTai Block 2B, attempt 3: No posts yet...
AmbassadorTai Block 2B, attempt 4: No posts yet...
AmbassadorTai Block 2B, attempt 5: No posts yet...
AmbassadorTai Block 2B, attempt 6: No posts yet...
AmbassadorTai Block 2B, attempt 7: No posts yet...
AmbassadorTai Block 2B, attempt 8: No posts yet...
AmbassadorTai Block 2B, attempt 9: No posts yet...
AmbassadorTai Block 2B, attempt 10: No posts yet...
No posts found for AmbassadorTai Block 2B, skipping save.
Task started for AmbassadorTai Block 3: 202
AmbassadorTai Block 3, attempt 1: No posts yet...
AmbassadorTai Block 3, attempt 2: No posts yet...
AmbassadorTai Block 3, attempt 3: No posts yet...
AmbassadorTai Block 3, attempt 4: No posts yet...
AmbassadorTai Block 3, attempt 5: No posts yet...
AmbassadorTai Block 3, attempt 6: No posts yet...
AmbassadorTai Block 3, attempt 7: No posts yet...
AmbassadorTai Block 3, attempt 8: No posts yet...
AmbassadorTai Block 3, attempt 9: No posts yet...
AmbassadorTai Block 3, attempt 10: No posts yet...
No posts found for AmbassadorTai Block 3, skipping save.
Task started for AmbassadorTai Block 4: 202
AmbassadorTai Block 4, attempt 1: No posts yet...
AmbassadorTai Block 4, attempt 2: No posts yet...
AmbassadorTai Block 4, attempt 3: No posts yet...
AmbassadorTai Block 4, attempt 4: No posts yet...
AmbassadorTai Block 4, attempt 5: No posts yet...
AmbassadorTai Block 4, attempt 6: No posts yet...
AmbassadorTai Block 4, attempt 7: No posts yet...

In [ ]:
AUTOMATING HEALTH-RELATED REPLIES

In [1019]:
import os
import json
import requests
import time

# ------------------------------------
# CONFIG
# ------------------------------------
BLOCKS = ["1A", "1B", "2A", "2B", "3", "4", "5", "6"]  # correct block names

# ------------------------------------
# START AT MayraFlores4TX AND GO DOWNWARD
# ------------------------------------
handles_series = final_df["X Handle"].dropna()

if "MayraFlores4TX" in handles_series.values:
    start_index = handles_series[handles_series == "MayraFlores4TX"].index[0]
    usernames_to_process = final_df.loc[start_index:, "X Handle"].dropna().unique()
else:
    print("MayraFlores4TX not found. Starting from top.")
    usernames_to_process = handles_series.unique()

# ------------------------------------
# LOOP THROUGH EACH POLITICIAN
# ------------------------------------
for username in usernames_to_process:

    print(f"\nProcessing politician: {username}")

    # ------------------------------------
    # LOOP THROUGH BLOCKS
    # ------------------------------------
    for block_name in BLOCKS:

        input_filename = f"{username} Block {block_name}.json"
        output_filename = f"{username} Block {block_name} Replies.json"

        # ------------------------------------
        # SKIP IF FILE DOESN'T EXIST
        # ------------------------------------
        if not os.path.exists(input_filename):
            print(f"Skipping {input_filename} (file not found)")
            continue

        # ------------------------------------
        # OPEN BLOCK FILE
        # ------------------------------------
        with open(input_filename, "r", encoding="utf-8") as f:
            block_data = json.load(f)

        posts = block_data.get("data", {}).get("items", [])

        # Skip if no posts
        if not posts:
            print(f"Skipping {input_filename} (no posts found)")
            continue

        all_replies_output = []

        # ------------------------------------
        # FETCH REPLIES FOR EACH POST
        # ------------------------------------
        for post in posts:
            conversation_id = post.get("conversation_id")

            if not conversation_id:
                continue

            print(f"Fetching replies for {username} Block {block_name} - {conversation_id}")

            replies_url = (
                f"{API_BASE_URL}{API_VERSION}/twitter/profile/"
                f"{username}/feed/posts/{conversation_id}/replies"
            )

            params = {
                "order_by": "date_desc",
                "max_page_size": 50,
                "access_token": API_AUTHORIZATION_TOKEN
            }

            response = requests.get(replies_url, params=params)

            if response.status_code == 200:
                replies_json = response.json()
                replies_items = replies_json.get("data", {}).get("items", [])

                all_replies_output.append({
                    "conversation_id": conversation_id,
                    "replies": replies_items
                })
            else:
                print(f"Failed for {conversation_id}: {response.status_code}")

            time.sleep(1)  # rate limit safety

        # ------------------------------------
        # SAVE OUTPUT ONLY IF REPLIES EXIST
        # ------------------------------------
        if all_replies_output:

            final_output = {
                "politician": username,
                "block": block_name,
                "posts": all_replies_output
            }

            with open(output_filename, "w", encoding="utf-8") as f:
                json.dump(final_output, f, indent=4)

            print(f"Saved: {output_filename}")
        else:
            print(f"No replies found for {username} Block {block_name}")

print("\nAll politicians processed.")

Processing politician: MayraFlores4TX
Fetching replies for MayraFlores4TX Block 1A - 1508451806187302924
Fetching replies for MayraFlores4TX Block 1A - 1520137165434404865
Fetching replies for MayraFlores4TX Block 1A - 1540478880309460993
Fetching replies for MayraFlores4TX Block 1A - 1557397296484175874
Fetching replies for MayraFlores4TX Block 1A - 1558984034377760776
Fetching replies for MayraFlores4TX Block 1A - 1575972354936950784
Fetching replies for MayraFlores4TX Block 1A - 1576271103781376006
Fetching replies for MayraFlores4TX Block 1A - 1643790685277921283
Fetching replies for MayraFlores4TX Block 1A - 1646993385507500034
Fetching replies for MayraFlores4TX Block 1A - 1661018805269852166
Fetching replies for MayraFlores4TX Block 1A - 1694432554412048692
Fetching replies for MayraFlores4TX Block 1A - 1770471980510101606
Fetching replies for MayraFlores4TX Block 1A - 1792558727272313065
Fetching replies for MayraFlores4TX Block 1A - 1807053284403802280
Fetching replies for MayraFlores4TX Block 1A - 1819747419564761340
Fetching replies for MayraFlores4TX Block 1A - 1912207347734159761
Fetching replies for MayraFlores4TX Block 1A - 1912852758723522879
Fetching replies for MayraFlores4TX Block 1A - 1981187034128802297
Saved: MayraFlores4TX Block 1A Replies.json
Skipping MayraFlores4TX Block 1B.json (file not found)
Skipping MayraFlores4TX Block 2A.json (file not found)
Skipping MayraFlores4TX Block 2B.json (file not found)
Skipping MayraFlores4TX Block 3.json (file not found)
Skipping MayraFlores4TX Block 4.json (file not found)
Skipping MayraFlores4TX Block 5.json (file not found)
Skipping MayraFlores4TX Block 6.json (file not found)

Processing politician: RepStephMurphy
Skipping RepStephMurphy Block 1A.json (file not found)
Skipping RepStephMurphy Block 1B.json (file not found)
Skipping RepStephMurphy Block 2A.json (file not found)
Skipping RepStephMurphy Block 2B.json (file not found)
Skipping RepStephMurphy Block 3.json (file not found)
Skipping RepStephMurphy Block 4.json (file not found)
Skipping RepStephMurphy Block 5.json (file not found)
Skipping RepStephMurphy Block 6.json (file not found)

Processing politician: RepTedLieu
Skipping RepTedLieu Block 1A.json (file not found)
Skipping RepTedLieu Block 1B.json (file not found)
Skipping RepTedLieu Block 2A.json (file not found)
Skipping RepTedLieu Block 2B.json (file not found)
Skipping RepTedLieu Block 3.json (file not found)
Skipping RepTedLieu Block 4.json (file not found)
Skipping RepTedLieu Block 5.json (file not found)
Skipping RepTedLieu Block 6.json (file not found)

Processing politician: RepJamesComer
Skipping RepJamesComer Block 1A.json (file not found)
Skipping RepJamesComer Block 1B.json (file not found)
Skipping RepJamesComer Block 2A.json (file not found)
Fetching replies for RepJamesComer Block 2B - 1511774042218450944
Fetching replies for RepJamesComer Block 2B - 1514630058639597568
Fetching replies for RepJamesComer Block 2B - 1516777607475380227
Fetching replies for RepJamesComer Block 2B - 1645834311206043656
Fetching replies for RepJamesComer Block 2B - 1813325782262968532
Fetching replies for RepJamesComer Block 2B - 1824166850034536601
Fetching replies for RepJamesComer Block 2B - 1831696683203445217
Fetching replies for RepJamesComer Block 2B - 1902385771098550299
Fetching replies for RepJamesComer Block 2B - 1999235350523158663
Fetching replies for RepJamesComer Block 2B - 1999587670259855666
Saved: RepJamesComer Block 2B Replies.json
Skipping RepJamesComer Block 3.json (file not found)
Skipping RepJamesComer Block 4.json (file not found)
Skipping RepJamesComer Block 5.json (file not found)
Fetching replies for RepJamesComer Block 6 - 1623330415888027650
Saved: RepJamesComer Block 6 Replies.json

Processing politician: RepJohnnyO
Fetching replies for RepJohnnyO Block 1A - 1940154662847750408
Fetching replies for RepJohnnyO Block 1A - 1940485633660895655
Fetching replies for RepJohnnyO Block 1A - 1942624874557792590
Fetching replies for RepJohnnyO Block 1A - 1942953421721817297
Fetching replies for RepJohnnyO Block 1A - 1943029556807442911
Fetching replies for RepJohnnyO Block 1A - 1946298684443926699
Fetching replies for RepJohnnyO Block 1A - 1947839371723350273
Fetching replies for RepJohnnyO Block 1A - 1948768310947893648
Fetching replies for RepJohnnyO Block 1A - 1950557596190175363
Fetching replies for RepJohnnyO Block 1A - 1952475782485512261
Fetching replies for RepJohnnyO Block 1A - 1966543176413352106
Fetching replies for RepJohnnyO Block 1A - 1968407457425678566
Fetching replies for RepJohnnyO Block 1A - 1970167576618483959
Fetching replies for RepJohnnyO Block 1A - 1972749762807152867
Fetching replies for RepJohnnyO Block 1A - 1972800175451300094
Fetching replies for RepJohnnyO Block 1A - 1978520129836098019
Fetching replies for RepJohnnyO Block 1A - 1979217491004968991
Fetching replies for RepJohnnyO Block 1A - 1980000307280015484
Fetching replies for RepJohnnyO Block 1A - 1995191095446401387
Fetching replies for RepJohnnyO Block 1A - 2001737692069908533
Saved: RepJohnnyO Block 1A Replies.json
Fetching replies for RepJohnnyO Block 1B - 1895589693192110316
Fetching replies for RepJohnnyO Block 1B - 1924232267708153880
Fetching replies for RepJohnnyO Block 1B - 1975711298672599189
Fetching replies for RepJohnnyO Block 1B - 1996233265359819007
Saved: RepJohnnyO Block 1B Replies.json
Fetching replies for RepJohnnyO Block 2A - 1942953421721817297
Fetching replies for RepJohnnyO Block 2A - 1943029556807442911
Fetching replies for RepJohnnyO Block 2A - 1945112579946209289
Fetching replies for RepJohnnyO Block 2A - 1950557596190175363
Fetching replies for RepJohnnyO Block 2A - 1966543176413352106
Fetching replies for RepJohnnyO Block 2A - 1970566473144750325
Fetching replies for RepJohnnyO Block 2A - 1970926335305654772
Fetching replies for RepJohnnyO Block 2A - 1973120026111778871
Fetching replies for RepJohnnyO Block 2A - 1975656694970491285
Fetching replies for RepJohnnyO Block 2A - 1976690025724101050
Fetching replies for RepJohnnyO Block 2A - 1979283478899507519
Fetching replies for RepJohnnyO Block 2A - 1983231230020632957
Fetching replies for RepJohnnyO Block 2A - 1985738337836019817
Fetching replies for RepJohnnyO Block 2A - 1987605567477571736
Fetching replies for RepJohnnyO Block 2A - 1988733178551619694
Fetching replies for RepJohnnyO Block 2A - 1988742675445789100
Fetching replies for RepJohnnyO Block 2A - 1988778202677047497
Fetching replies for RepJohnnyO Block 2A - 1988956498924286089
Fetching replies for RepJohnnyO Block 2A - 1989086067048476967
Fetching replies for RepJohnnyO Block 2A - 2001737692069908533
Saved: RepJohnnyO Block 2A Replies.json
Fetching replies for RepJohnnyO Block 2B - 1922299021743292843
Fetching replies for RepJohnnyO Block 2B - 1932105592258314285
Fetching replies for RepJohnnyO Block 2B - 1936091674033152165
Fetching replies for RepJohnnyO Block 2B - 1951784449894482249
Fetching replies for RepJohnnyO Block 2B - 1968407457425678566
Fetching replies for RepJohnnyO Block 2B - 1972749762807152867
Fetching replies for RepJohnnyO Block 2B - 1979217491004968991
Fetching replies for RepJohnnyO Block 2B - 1989086067048476967
Fetching replies for RepJohnnyO Block 2B - 2001737692069908533
Saved: RepJohnnyO Block 2B Replies.json
Skipping RepJohnnyO Block 3.json (file not found)
Skipping RepJohnnyO Block 4.json (file not found)
Skipping RepJohnnyO Block 5.json (file not found)
Skipping RepJohnnyO Block 6.json (file not found)

Processing politician: RepEmiliaSykes
Fetching replies for RepEmiliaSykes Block 1A - 1980422536904208465
Fetching replies for RepEmiliaSykes Block 1A - 1981435027574464557
Fetching replies for RepEmiliaSykes Block 1A - 1981868268173545814
Fetching replies for RepEmiliaSykes Block 1A - 1983993386823565680
Fetching replies for RepEmiliaSykes Block 1A - 1984043793864389049
Fetching replies for RepEmiliaSykes Block 1A - 1988734631936684308
Fetching replies for RepEmiliaSykes Block 1A - 1989098020970090556
Fetching replies for RepEmiliaSykes Block 1A - 1989489536234123283
Fetching replies for RepEmiliaSykes Block 1A - 1990563100647698631
Fetching replies for RepEmiliaSykes Block 1A - 1990899468460319010
Fetching replies for RepEmiliaSykes Block 1A - 1991943845584515110
Fetching replies for RepEmiliaSykes Block 1A - 1993114649416368474
Fetching replies for RepEmiliaSykes Block 1A - 1993477629744169205
Fetching replies for RepEmiliaSykes Block 1A - 1994473023634559062
Fetching replies for RepEmiliaSykes Block 1A - 1998144344054960513
Fetching replies for RepEmiliaSykes Block 1A - 1998494894940139824
Fetching replies for RepEmiliaSykes Block 1A - 1999123102551212406
Fetching replies for RepEmiliaSykes Block 1A - 1999555683562246413
Fetching replies for RepEmiliaSykes Block 1A - 2002144398906188251
Fetching replies for RepEmiliaSykes Block 1A - 2003238263411376415
Saved: RepEmiliaSykes Block 1A Replies.json
Skipping RepEmiliaSykes Block 1B.json (file not found)
Fetching replies for RepEmiliaSykes Block 2A - 1978936628929290464
Fetching replies for RepEmiliaSykes Block 2A - 1980422536904208465
Fetching replies for RepEmiliaSykes Block 2A - 1981117192017236015
Fetching replies for RepEmiliaSykes Block 2A - 1981146917099749468
Fetching replies for RepEmiliaSykes Block 2A - 1985469943832338655
Fetching replies for RepEmiliaSykes Block 2A - 1985861252904526325
Fetching replies for RepEmiliaSykes Block 2A - 1986195863224418323
Fetching replies for RepEmiliaSykes Block 2A - 1988792512438497783
Fetching replies for RepEmiliaSykes Block 2A - 1989001315008053284
Fetching replies for RepEmiliaSykes Block 2A - 1989098020970090556
Fetching replies for RepEmiliaSykes Block 2A - 1989489536234123283
Fetching replies for RepEmiliaSykes Block 2A - 1992606349721825370
Fetching replies for RepEmiliaSykes Block 2A - 1993114649416368474
Fetching replies for RepEmiliaSykes Block 2A - 1993477629744169205
Fetching replies for RepEmiliaSykes Block 2A - 1994473023634559062
Fetching replies for RepEmiliaSykes Block 2A - 1998494894940139824
Fetching replies for RepEmiliaSykes Block 2A - 1999555683562246413
Fetching replies for RepEmiliaSykes Block 2A - 1999963607547990281
Fetching replies for RepEmiliaSykes Block 2A - 2000690293272695063
Fetching replies for RepEmiliaSykes Block 2A - 2001051961701843018
Saved: RepEmiliaSykes Block 2A Replies.json
Fetching replies for RepEmiliaSykes Block 2B - 1920594405825663002
Fetching replies for RepEmiliaSykes Block 2B - 1927761554021216495
Fetching replies for RepEmiliaSykes Block 2B - 1930381133172068428
Fetching replies for RepEmiliaSykes Block 2B - 1933239025856373215
Fetching replies for RepEmiliaSykes Block 2B - 1936165903995162717
Fetching replies for RepEmiliaSykes Block 2B - 1937665686475800760
Fetching replies for RepEmiliaSykes Block 2B - 1940497712660861412
Fetching replies for RepEmiliaSykes Block 2B - 1942298089252888977
Fetching replies for RepEmiliaSykes Block 2B - 1949865876657967108
Fetching replies for RepEmiliaSykes Block 2B - 1949912712852754874
Fetching replies for RepEmiliaSykes Block 2B - 1968347408913293603
Fetching replies for RepEmiliaSykes Block 2B - 1969160528900530177
Fetching replies for RepEmiliaSykes Block 2B - 1971681181583245619
Fetching replies for RepEmiliaSykes Block 2B - 1975335263074460137
Fetching replies for RepEmiliaSykes Block 2B - 1976379639020081516
Fetching replies for RepEmiliaSykes Block 2B - 1988734631936684308
Fetching replies for RepEmiliaSykes Block 2B - 1994473023634559062
Fetching replies for RepEmiliaSykes Block 2B - 1999123102551212406
Fetching replies for RepEmiliaSykes Block 2B - 1999555683562246413
Fetching replies for RepEmiliaSykes Block 2B - 1999963607547990281
Saved: RepEmiliaSykes Block 2B Replies.json
Skipping RepEmiliaSykes Block 3.json (file not found)
Skipping RepEmiliaSykes Block 4.json (file not found)
Skipping RepEmiliaSykes Block 5.json (file not found)
Fetching replies for RepEmiliaSykes Block 6 - 1697369925151535182
Fetching replies for RepEmiliaSykes Block 6 - 1698329594846126518
Fetching replies for RepEmiliaSykes Block 6 - 1717899951798100070
Fetching replies for RepEmiliaSykes Block 6 - 1762842604637446399
Fetching replies for RepEmiliaSykes Block 6 - 1867678180062244932
Fetching replies for RepEmiliaSykes Block 6 - 1893054892345839888
Fetching replies for RepEmiliaSykes Block 6 - 1905313365238382772
Fetching replies for RepEmiliaSykes Block 6 - 1907805563544592606
Fetching replies for RepEmiliaSykes Block 6 - 1907836545106645108
Fetching replies for RepEmiliaSykes Block 6 - 1910040944423940401
Fetching replies for RepEmiliaSykes Block 6 - 1960120056773325020
Saved: RepEmiliaSykes Block 6 Replies.json

Processing politician: GrangerCampaign
Skipping GrangerCampaign Block 1A.json (file not found)
Skipping GrangerCampaign Block 1B.json (file not found)
Skipping GrangerCampaign Block 2A.json (file not found)
Skipping GrangerCampaign Block 2B.json (file not found)
Skipping GrangerCampaign Block 3.json (file not found)
Skipping GrangerCampaign Block 4.json (file not found)
Skipping GrangerCampaign Block 5.json (file not found)
Skipping GrangerCampaign Block 6.json (file not found)

Processing politician: MaryPeltola
Fetching replies for MaryPeltola Block 1A - 1623709274051342337
Fetching replies for MaryPeltola Block 1A - 1623789566359470081
Fetching replies for MaryPeltola Block 1A - 1658970916246679555
Fetching replies for MaryPeltola Block 1A - 1660711193848193032
Fetching replies for MaryPeltola Block 1A - 1682851366190841857
Fetching replies for MaryPeltola Block 1A - 1683988640194519042
Fetching replies for MaryPeltola Block 1A - 1729304535309365497
Fetching replies for MaryPeltola Block 1A - 1731086316455055637
Fetching replies for MaryPeltola Block 1A - 1750232464054689997
Fetching replies for MaryPeltola Block 1A - 1750987513437569145
Fetching replies for MaryPeltola Block 1A - 1755343233628983796
Fetching replies for MaryPeltola Block 1A - 1775624989149991143
Fetching replies for MaryPeltola Block 1A - 1780688208226836735
Fetching replies for MaryPeltola Block 1A - 1785022425383543113
Fetching replies for MaryPeltola Block 1A - 1787284745497325845
Fetching replies for MaryPeltola Block 1A - 1803199228958707958
Fetching replies for MaryPeltola Block 1A - 1805703716219027859
Fetching replies for MaryPeltola Block 1A - 1812185443586191621
Fetching replies for MaryPeltola Block 1A - 1813635461585211429
Fetching replies for MaryPeltola Block 1A - 1843750628146954666
Saved: MaryPeltola Block 1A Replies.json
Skipping MaryPeltola Block 1B.json (file not found)
Fetching replies for MaryPeltola Block 2A - 1683988640194519042
Fetching replies for MaryPeltola Block 2A - 1729636980718174362
Fetching replies for MaryPeltola Block 2A - 1730346544690266174
Fetching replies for MaryPeltola Block 2A - 1734016031423610939
Fetching replies for MaryPeltola Block 2A - 1771997635546619912
Fetching replies for MaryPeltola Block 2A - 1776385224697401756
Fetching replies for MaryPeltola Block 2A - 1777112636275966410
Fetching replies for MaryPeltola Block 2A - 1785022425383543113
Fetching replies for MaryPeltola Block 2A - 1788660796672672100
Fetching replies for MaryPeltola Block 2A - 1791214942407790754
Fetching replies for MaryPeltola Block 2A - 1796704514273165682
Fetching replies for MaryPeltola Block 2A - 1805703716219027859
Fetching replies for MaryPeltola Block 2A - 1811461136753000596
Fetching replies for MaryPeltola Block 2A - 1811823471413854469
Fetching replies for MaryPeltola Block 2A - 1812910640152854947
Fetching replies for MaryPeltola Block 2A - 1813635461585211429
Fetching replies for MaryPeltola Block 2A - 1818040444061638925
Fetching replies for MaryPeltola Block 2A - 1822709734698340635
Fetching replies for MaryPeltola Block 2A - 1843750628146954666
Fetching replies for MaryPeltola Block 2A - 1940181401065685282
Saved: MaryPeltola Block 2A Replies.json
Fetching replies for MaryPeltola Block 2B - 1600566220188798981
Fetching replies for MaryPeltola Block 2B - 1787284745497325845
Fetching replies for MaryPeltola Block 2B - 1788660796672672100
Saved: MaryPeltola Block 2B Replies.json
Skipping MaryPeltola Block 3.json (file not found)
Skipping MaryPeltola Block 4.json (file not found)
Skipping MaryPeltola Block 5.json (file not found)
Fetching replies for MaryPeltola Block 6 - 1586161047202938881
Fetching replies for MaryPeltola Block 6 - 1588592375613558784
Fetching replies for MaryPeltola Block 6 - 1613974549950758920
Fetching replies for MaryPeltola Block 6 - 1619048076794118150
Fetching replies for MaryPeltola Block 6 - 1677442679410679809
Fetching replies for MaryPeltola Block 6 - 1750594875047764252
Fetching replies for MaryPeltola Block 6 - 1850266442358268026
Saved: MaryPeltola Block 6 Replies.json

Processing politician: RepTeresaLF
Fetching replies for RepTeresaLF Block 1A - 1972399491329515806
Fetching replies for RepTeresaLF Block 1A - 1973117010922852756
Fetching replies for RepTeresaLF Block 1A - 1973566604718862762
Fetching replies for RepTeresaLF Block 1A - 1973902892307525643
Fetching replies for RepTeresaLF Block 1A - 1974154606545457403
Fetching replies for RepTeresaLF Block 1A - 1976028863986884631
Fetching replies for RepTeresaLF Block 1A - 1978184578201174201
Fetching replies for RepTeresaLF Block 1A - 1982854756164075894
Fetching replies for RepTeresaLF Block 1A - 1985772968186720476
Fetching replies for RepTeresaLF Block 1A - 1987730910049886314
Fetching replies for RepTeresaLF Block 1A - 1988036578367721480
Fetching replies for RepTeresaLF Block 1A - 1988349175528911336
Fetching replies for RepTeresaLF Block 1A - 1988426902642872538
Fetching replies for RepTeresaLF Block 1A - 1988427050303320552
Fetching replies for RepTeresaLF Block 1A - 1988652636682502545
Fetching replies for RepTeresaLF Block 1A - 1996992227319459956
Fetching replies for RepTeresaLF Block 1A - 1998836526063493554
Fetching replies for RepTeresaLF Block 1A - 2001066615652159779
Fetching replies for RepTeresaLF Block 1A - 2001076942636785872
Fetching replies for RepTeresaLF Block 1A - 2001322944337715682
Saved: RepTeresaLF Block 1A Replies.json
Skipping RepTeresaLF Block 1B.json (file not found)
Fetching replies for RepTeresaLF Block 2A - 1978513451690463625
Fetching replies for RepTeresaLF Block 2A - 1980774900299145427
Fetching replies for RepTeresaLF Block 2A - 1981463955533963627
Fetching replies for RepTeresaLF Block 2A - 1981503601479733742
Fetching replies for RepTeresaLF Block 2A - 1981801722772435286
Fetching replies for RepTeresaLF Block 2A - 1983982319599022423
Fetching replies for RepTeresaLF Block 2A - 1985772968186720476
Fetching replies for RepTeresaLF Block 2A - 1985851505719537925
Fetching replies for RepTeresaLF Block 2A - 1986137656154288286
Fetching replies for RepTeresaLF Block 2A - 1986595109442330969
Fetching replies for RepTeresaLF Block 2A - 1988279145781182676
Fetching replies for RepTeresaLF Block 2A - 1988352929548693726
Fetching replies for RepTeresaLF Block 2A - 1989061309384802647
Fetching replies for RepTeresaLF Block 2A - 1990580047061922164
Fetching replies for RepTeresaLF Block 2A - 1991123816848753023
Fetching replies for RepTeresaLF Block 2A - 1998156154887663783
Fetching replies for RepTeresaLF Block 2A - 1998516070324342856
Fetching replies for RepTeresaLF Block 2A - 1998781463840362578
Fetching replies for RepTeresaLF Block 2A - 2001076942636785872
Fetching replies for RepTeresaLF Block 2A - 2003639195483668699
Saved: RepTeresaLF Block 2A Replies.json
Fetching replies for RepTeresaLF Block 2B - 1939030702814527773
Fetching replies for RepTeresaLF Block 2B - 1939126291091050677
Fetching replies for RepTeresaLF Block 2B - 1963645222006465001
Fetching replies for RepTeresaLF Block 2B - 1965753956472402399
Fetching replies for RepTeresaLF Block 2B - 1968116794138431961
Fetching replies for RepTeresaLF Block 2B - 1970525270483361969
Fetching replies for RepTeresaLF Block 2B - 1971236456468214203
Fetching replies for RepTeresaLF Block 2B - 1971952847718961269

In [ ]:
GET NON-HEALTH TWEETS FOR FIRST HALF

In [1023]:
import pandas as pd
import requests
import time
import json

API_BASE_URL = "https://api.data365.co"
API_VERSION = "/v1.1"
API_AUTHORIZATION_TOKEN = "ZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKSVV6STFOaUo5LmV5SnpkV0lpT2lKSWFXSmhRV3hwSWl3aWFXRjBJam94TnpZNU5UQTNOamcyTGpBd05UQXhPSDAuNmpTLTZtbVBGV0F1ZS1McHhXaUIwbUtDUWFDemU4VkRNZVhOSkZ2ckJRTQ=="

# ------------------------
# Function to fetch top posts (no keywords)
# ------------------------
def fetch_top_posts(username, max_attempts=10, sleep_time=2):

    update_url = f"{API_BASE_URL}{API_VERSION}/twitter/search/post/update"
    posts_url = f"{API_BASE_URL}{API_VERSION}/twitter/search/post/posts"

    params = {
        "from_profile": username,
        "from_date": "2022-01-01",
        "to_date": "2025-12-31",
        "lang": "en",
        "max_posts": 20,
        "search_type": "top",   # change to "top" if API supports it
        "max_replies": 3,
        "load_replies": "true",
        "access_token": API_AUTHORIZATION_TOKEN
    }

    # Start search task
    post_response = requests.post(update_url, params=params)
    print(f"Task started for {username}: {post_response.status_code}")

    attempt = 0
    data = {}

    while attempt < max_attempts:
        posts_response = requests.get(posts_url, params=params)

        if posts_response.status_code == 200:
            data = posts_response.json()
            items = data.get("data", {}).get("items", [])

            if items:
                print(f"{username}: Retrieved {len(items)} posts")
                break
            else:
                print(f"{username}, attempt {attempt+1}: No posts yet...")
        else:
            print(f"Failed for {username} (attempt {attempt+1}): {posts_response.status_code}")

        attempt += 1
        time.sleep(sleep_time)

    items = data.get("data", {}).get("items", [])

    if items:
        filename = f"{username}.json"
        with open(filename, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4)
        print(f"Saved posts to {filename}")
    else:
        print(f"No posts found for {username}, skipping save.")

    return items


# ------------------------
# MAIN EXECUTION
# ------------------------

start_username = "RepWexton"

# Find starting index
start_index = final_df.index[final_df["X Handle"] == start_username][0]

# Loop downward from RepWexton
for username in final_df["X Handle"].iloc[start_index:]:
    print(f"\n=== Processing {username} ===")
    fetch_top_posts(username)

print("\nAll politicians processed.")

=== Processing RepWexton ===
Task started for RepWexton: 202
RepWexton: Retrieved 25 posts
Saved posts to RepWexton.json

=== Processing TomColeOK04 ===
Task started for TomColeOK04: 202
TomColeOK04: Retrieved 25 posts
Saved posts to TomColeOK04.json

=== Processing RepLoisFrankel ===
Task started for RepLoisFrankel: 202
RepLoisFrankel: Retrieved 25 posts
Saved posts to RepLoisFrankel.json

=== Processing RepJillTokuda ===
Task started for RepJillTokuda: 202
RepJillTokuda: Retrieved 25 posts
Saved posts to RepJillTokuda.json

=== Processing michaelgwaltz ===
Task started for michaelgwaltz: 202
michaelgwaltz: Retrieved 25 posts
Saved posts to michaelgwaltz.json

=== Processing RepTerriSewell ===
Task started for RepTerriSewell: 202
RepTerriSewell: Retrieved 25 posts
Saved posts to RepTerriSewell.json

=== Processing RepJeffHurd ===
Task started for RepJeffHurd: 202
RepJeffHurd: Retrieved 25 posts
Saved posts to RepJeffHurd.json

=== Processing RepSheriBiggs ===
Task started for RepSheriBiggs: 202
RepSheriBiggs: Retrieved 12 posts
Saved posts to RepSheriBiggs.json

=== Processing RepDanCrenshaw ===
Task started for RepDanCrenshaw: 202
RepDanCrenshaw: Retrieved 25 posts
Saved posts to RepDanCrenshaw.json

=== Processing RepMann ===
Task started for RepMann: 202
RepMann: Retrieved 25 posts
Saved posts to RepMann.json

=== Processing Carolyn4GA7 ===
Task started for Carolyn4GA7: 202
Carolyn4GA7: Retrieved 25 posts
Saved posts to Carolyn4GA7.json

=== Processing RepKweisiMfume ===
Task started for RepKweisiMfume: 202
RepKweisiMfume: Retrieved 25 posts
Saved posts to RepKweisiMfume.json

=== Processing RepMarkGreen ===
Task started for RepMarkGreen: 202
RepMarkGreen: Retrieved 25 posts
Saved posts to RepMarkGreen.json

=== Processing CongressMin ===
Task started for CongressMin: 202
CongressMin: Retrieved 25 posts
Saved posts to CongressMin.json

=== Processing Liz_Cheney ===
Task started for Liz_Cheney: 202
Liz_Cheney, attempt 1: No posts yet...
Liz_Cheney, attempt 2: No posts yet...
Liz_Cheney, attempt 3: No posts yet...
Liz_Cheney, attempt 4: No posts yet...
Liz_Cheney, attempt 5: No posts yet...
Liz_Cheney, attempt 6: No posts yet...
Liz_Cheney, attempt 7: No posts yet...
Liz_Cheney, attempt 8: No posts yet...
Liz_Cheney, attempt 9: No posts yet...
Liz_Cheney, attempt 10: No posts yet...
No posts found for Liz_Cheney, skipping save.

=== Processing RepJasonCrow ===
Task started for RepJasonCrow: 202
RepJasonCrow: Retrieved 25 posts
Saved posts to RepJasonCrow.json

=== Processing RepMcClintock ===
Task started for RepMcClintock: 202
RepMcClintock: Retrieved 13 posts
Saved posts to RepMcClintock.json

=== Processing RepAbeHamadeh ===
Task started for RepAbeHamadeh: 202
RepAbeHamadeh: Retrieved 25 posts
Saved posts to RepAbeHamadeh.json

=== Processing RepDonaldsPress ===
Task started for RepDonaldsPress: 202
RepDonaldsPress: Retrieved 25 posts
Saved posts to RepDonaldsPress.json

=== Processing RepMaryMiller ===
Task started for RepMaryMiller: 202
RepMaryMiller: Retrieved 25 posts
Saved posts to RepMaryMiller.json

=== Processing RepHerbConaway ===
Task started for RepHerbConaway: 202
RepHerbConaway: Retrieved 25 posts
Saved posts to RepHerbConaway.json

=== Processing RepJoeWilson ===
Task started for RepJoeWilson: 202
RepJoeWilson: Retrieved 22 posts
Saved posts to RepJoeWilson.json

=== Processing RepTiffany ===
Task started for RepTiffany: 202
RepTiffany: Retrieved 25 posts
Saved posts to RepTiffany.json

=== Processing cathymcmorris ===
Task started for cathymcmorris: 202
cathymcmorris: Retrieved 25 posts
Saved posts to cathymcmorris.json

=== Processing repkmr ===
Task started for repkmr: 202
repkmr: Retrieved 25 posts
Saved posts to repkmr.json

=== Processing RepJoeCourtney ===
Task started for RepJoeCourtney: 202
RepJoeCourtney: Retrieved 25 posts
Saved posts to RepJoeCourtney.json

=== Processing MayraFlores4TX ===
Task started for MayraFlores4TX: 202
MayraFlores4TX: Retrieved 25 posts
Saved posts to MayraFlores4TX.json

=== Processing RepStephMurphy ===
Task started for RepStephMurphy: 202
RepStephMurphy: Retrieved 21 posts
Saved posts to RepStephMurphy.json

=== Processing RepTedLieu ===
Task started for RepTedLieu: 202
RepTedLieu: Retrieved 25 posts
Saved posts to RepTedLieu.json

=== Processing RepJamesComer ===
Task started for RepJamesComer: 202
RepJamesComer: Retrieved 25 posts
Saved posts to RepJamesComer.json

=== Processing RepJohnnyO ===
Task started for RepJohnnyO: 202
RepJohnnyO: Retrieved 25 posts
Saved posts to RepJohnnyO.json

=== Processing RepEmiliaSykes ===
Task started for RepEmiliaSykes: 202
RepEmiliaSykes: Retrieved 25 posts
Saved posts to RepEmiliaSykes.json

=== Processing GrangerCampaign ===
Task started for GrangerCampaign: 202
GrangerCampaign, attempt 1: No posts yet...
GrangerCampaign, attempt 2: No posts yet...
GrangerCampaign, attempt 3: No posts yet...
GrangerCampaign, attempt 4: No posts yet...
GrangerCampaign, attempt 5: No posts yet...
GrangerCampaign, attempt 6: No posts yet...
GrangerCampaign, attempt 7: No posts yet...
GrangerCampaign, attempt 8: No posts yet...
GrangerCampaign, attempt 9: No posts yet...
GrangerCampaign, attempt 10: No posts yet...
No posts found for GrangerCampaign, skipping save.

=== Processing MaryPeltola ===
Task started for MaryPeltola: 202
MaryPeltola: Retrieved 25 posts
Saved posts to MaryPeltola.json

=== Processing RepTeresaLF ===
Task started for RepTeresaLF: 202
RepTeresaLF: Retrieved 25 posts
Saved posts to RepTeresaLF.json

=== Processing RepCasten ===
Task started for RepCasten: 202
RepCasten: Retrieved 25 posts
Saved posts to RepCasten.json

=== Processing RepBrianBabin ===
Task started for RepBrianBabin: 202
RepBrianBabin: Retrieved 25 posts
Saved posts to RepBrianBabin.json

=== Processing rep_jackson ===
Task started for rep_jackson: 202
rep_jackson: Retrieved 25 posts
Saved posts to rep_jackson.json

=== Processing MarkAmodeiNV2 ===
Task started for MarkAmodeiNV2: 202
MarkAmodeiNV2: Retrieved 7 posts
Saved posts to MarkAmodeiNV2.json

=== Processing RepDean ===
Task started for RepDean: 202
RepDean: Retrieved 25 posts
Saved posts to RepDean.json

=== Processing RepChuckEdwards ===
Task started for RepChuckEdwards: 202
RepChuckEdwards: Retrieved 25 posts
Saved posts to RepChuckEdwards.json

=== Processing RepKimSchrier ===
Task started for RepKimSchrier: 202
RepKimSchrier: Retrieved 25 posts
Saved posts to RepKimSchrier.json

=== Processing RepShreve ===
Task started for RepShreve: 202
RepShreve: Retrieved 9 posts
Saved posts to RepShreve.json

=== Processing RepJames ===
Task started for RepJames: 202
RepJames: Retrieved 25 posts
Saved posts to RepJames.json

=== Processing RepGuthrie ===
Task started for RepGuthrie: 202
RepGuthrie: Retrieved 25 posts
Saved posts to RepGuthrie.json

=== Processing RepEspaillat ===
Task started for RepEspaillat: 202
RepEspaillat: Retrieved 25 posts
Saved posts to RepEspaillat.json

=== Processing PatrickMcHenry ===
Task started for PatrickMcHenry: 202
PatrickMcHenry: Retrieved 8 posts
Saved posts to PatrickMcHenry.json

=== Processing StevenPalazzo ===
Task started for StevenPalazzo: 202
StevenPalazzo, attempt 1: No posts yet...
StevenPalazzo, attempt 2: No posts yet...
StevenPalazzo, attempt 3: No posts yet...
StevenPalazzo, attempt 4: No posts yet...
StevenPalazzo, attempt 5: No posts yet...
StevenPalazzo, attempt 6: No posts yet...
StevenPalazzo, attempt 7: No posts yet...
StevenPalazzo, attempt 8: No posts yet...
StevenPalazzo, attempt 9: No posts yet...
StevenPalazzo, attempt 10: No posts yet...
No posts found for StevenPalazzo, skipping save.

=== Processing RepHaridopolos ===
Task started for RepHaridopolos: 202
RepHaridopolos: Retrieved 25 posts
Saved posts to RepHaridopolos.json

=== Processing RepRileyMoore ===
Task started for RepRileyMoore: 202
RepRileyMoore: Retrieved 25 posts
Saved posts to RepRileyMoore.json

=== Processing RepBradWenstrup ===
Task started for RepBradWenstrup: 202
RepBradWenstrup: Retrieved 25 posts
Saved posts to RepBradWenstrup.json

=== Processing RepGusBilirakis ===
Task started for RepGusBilirakis: 202
RepGusBilirakis: Retrieved 25 posts
Saved posts to RepGusBilirakis.json

=== Processing RepJoshG ===
Task started for RepJoshG: 202
RepJoshG: Retrieved 25 posts
Saved posts to RepJoshG.json

=== Processing RepDanGoldman ===
Task started for RepDanGoldman: 202
RepDanGoldman: Retrieved 25 posts
Saved posts to RepDanGoldman.json

=== Processing RepPettersen ===
Task started for RepPettersen: 202
RepPettersen: Retrieved 25 posts
Saved posts to RepPettersen.json

=== Processing CongressmanGT ===
Task started for CongressmanGT: 202
CongressmanGT: Retrieved 13 posts
Saved posts to CongressmanGT.json

=== Processing repjulialetlow ===
Task started for repjulialetlow: 202
repjulialetlow: Retrieved 25 posts
Saved posts to repjulialetlow.json

=== Processing RepJasmine ===
Task started for RepJasmine: 202
RepJasmine: Retrieved 25 posts
Saved posts to RepJasmine.json

=== Processing RepBrownley ===
Task started for RepBrownley: 202
RepBrownley: Retrieved 25 posts
Saved posts to RepBrownley.json

=== Processing mtgreenee ===
Task started for mtgreenee: 202
mtgreenee: Retrieved 25 posts
Saved posts to mtgreenee.json

=== Processing RepJeffCrank ===
Task started for RepJeffCrank: 202
RepJeffCrank: Retrieved 18 posts
Saved posts to RepJeffCrank.json

=== Processing RepPeteAguilar ===
Task started for RepPeteAguilar: 202
RepPeteAguilar: Retrieved 25 posts
Saved posts to RepPeteAguilar.json

=== Processing RepCardenas ===
Task started for RepCardenas: 202
RepCardenas: Retrieved 25 posts
Saved posts to RepCardenas.json

=== Processing RepDerekTranCA ===
Task started for RepDerekTranCA: 202
RepDerekTranCA: Retrieved 25 posts
Saved posts to RepDerekTranCA.json

=== Processing RepDaveJoyce ===
Task started for RepDaveJoyce: 202
RepDaveJoyce: Retrieved 25 posts
Saved posts to RepDaveJoyce.json

=== Processing RepKathleenRice ===
Task started for RepKathleenRice: 202
RepKathleenRice: Retrieved 25 posts
Saved posts to RepKathleenRice.json

=== Processing repscfigures ===
Task started for repscfigures: 202
repscfigures: Retrieved 25 posts
Saved posts to repscfigures.json

=== Processing RepEliCrane ===
Task started for RepEliCrane: 202
RepEliCrane: Retrieved 25 posts
Saved posts to RepEliCrane.json

=== Processing RepKimKingHinds ===
Task started for RepKimKingHinds: 202
RepKimKingHinds: Retrieved 9 posts
Saved posts to RepKimKingHinds.json

=== Processing AdamKinzinger ===
Task started for AdamKinzinger: 202
AdamKinzinger: Retrieved 25 posts
Saved posts to AdamKinzinger.json

=== Processing RepMikeQuigley ===
Task started for RepMikeQuigley: 202
RepMikeQuigley: Retrieved 25 posts
Saved posts to RepMikeQuigley.json

=== Processing RepDonBacon ===
Task started for RepDonBacon: 202
RepDonBacon: Retrieved 25 posts
Saved posts to RepDonBacon.json

=== Processing repdinatitus ===
Task started for repdinatitus: 202
repdinatitus: Retrieved 25 posts
Saved posts to repdinatitus.json

=== Processing RepWesterman ===
Task started for RepWesterman: 202
RepWesterman: Retrieved 25 posts
Saved posts to RepWesterman.json

=== Processing DonaldNorcross ===
Task started for DonaldNorcross: 202
DonaldNorcross: Retrieved 25 posts
Saved posts to DonaldNorcross.json

=== Processing RepChipRoy ===
Task started for RepChipRoy: 202
RepChipRoy: Retrieved 25 posts
Saved posts to RepChipRoy.json

=== Processing RepBobOnder ===
Task started for RepBobOnder: 202
RepBobOnder: Retrieved 25 posts
Saved posts to RepBobOnder.json

=== Processing RepMcCaul ===
Task started for RepMcCaul: 202
RepMcCaul: Retrieved 25 posts
Saved posts to RepMcCaul.json

=== Processing RepMGP ===
Task started for RepMGP: 202
RepMGP: Retrieved 25 posts
Saved posts to RepMGP.json

=== Processing RepStricklandWA ===
Task started for RepStricklandWA: 202
RepStricklandWA: Retrieved 25 posts
Saved posts to RepStricklandWA.json

=== Processing RepFranklin ===
Task started for RepFranklin: 202
RepFranklin: Retrieved 25 posts
Saved posts to RepFranklin.json

=== Processing RepRichHudson ===
Task started for RepRichHudson: 202
RepRichHudson: Retrieved 25 posts
Saved posts to RepRichHudson.json

=== Processing WarrenDavidson ===
Task started for WarrenDavidson: 202
WarrenDavidson: Retrieved 25 posts
Saved posts to WarrenDavidson.json

=== Processing RepLaurelLee ===
Task started for RepLaurelLee: 202
RepLaurelLee: Retrieved 25 posts
Saved posts to RepLaurelLee.json

=== Processing USRepKeating ===
Task started for USRepKeating: 202
USRepKeating: Retrieved 23 posts
Saved posts to USRepKeating.json

=== Processing RepAprilDelaney ===
Task started for RepAprilDelaney: 202
RepAprilDelaney: Retrieved 25 posts
Saved posts to RepAprilDelaney.json

=== Processing RepAuchincloss ===
Task started for RepAuchincloss: 202
RepAuchincloss: Retrieved 25 posts
Saved posts to RepAuchincloss.json

=== Processing RepDanBishop ===
Task started for RepDanBishop: 202
RepDanBishop: Retrieved 23 posts
Saved posts to RepDanBishop.json

=== Processing RepBowman ===
Task started for RepBowman: 202
RepBowman: Retrieved 25 posts
Saved posts to RepBowman.json

=== Processing Congressman_JVD ===
Task started for Congressman_JVD: 202
Congressman_JVD: Retrieved 25 posts
Saved posts to Congressman_JVD.json

=== Processing RepCuellar ===
Task started for RepCuellar: 202
RepCuellar: Retrieved 25 posts
Saved posts to RepCuellar.json

=== Processing RepDaleStrong ===
Task started for RepDaleStrong: 202
RepDaleStrong: Retrieved 13 posts
Saved posts to RepDaleStrong.json

=== Processing RepHalRogers ===
Task started for RepHalRogers: 202
RepHalRogers: Retrieved 9 posts
Saved posts to RepHalRogers.json

=== Processing CoriBush ===
Task started for CoriBush: 202
CoriBush: Retrieved 25 posts
Saved posts to CoriBush.json

=== Processing RepRileyNY ===
Task started for RepRileyNY: 202
RepRileyNY: Retrieved 25 posts
Saved posts to RepRileyNY.json

=== Processing RepRonEstes ===
Task started for RepRonEstes: 202
RepRonEstes: Retrieved 25 posts
Saved posts to RepRonEstes.json

=== Processing RepValDemings ===
Task started for RepValDemings: 202
RepValDemings: Retrieved 25 posts
Saved posts to RepValDemings.json

=== Processing RepJohnJoyce ===
Task started for RepJohnJoyce: 202
RepJohnJoyce: Retrieved 25 posts
Saved posts to RepJohnJoyce.json

=== Processing MikeKellyPA ===
Task started for MikeKellyPA: 202
MikeKellyPA: Retrieved 25 posts
Saved posts to MikeKellyPA.json

=== Processing RepGoodlander ===
Task started for RepGoodlander: 202
RepGoodlander: Retrieved 25 posts
Saved posts to RepGoodlander.json

=== Processing RepLuzRivas ===
Task started for RepLuzRivas: 202
RepLuzRivas: Retrieved 25 posts
Saved posts to RepLuzRivas.json

=== Processing RepSylviaGarcia ===
Task started for RepSylviaGarcia: 202
RepSylviaGarcia: Retrieved 25 posts
Saved posts to RepSylviaGarcia.json

=== Processing RepAngieCraig ===
Task started for RepAngieCraig: 202
RepAngieCraig: Retrieved 25 posts
Saved posts to RepAngieCraig.json

=== Processing RepVanOrden ===
Task started for RepVanOrden: 202
RepVanOrden: Retrieved 18 posts
Saved posts to RepVanOrden.json

=== Processing RepLucyMcBath ===
Task started for RepLucyMcBath: 202
RepLucyMcBath: Retrieved 25 posts
Saved posts to RepLucyMcBath.json

=== Processing RepConnieConway ===
Task started for RepConnieConway: 202
RepConnieConway, attempt 1: No posts yet...
RepConnieConway, attempt 2: No posts yet...
RepConnieConway, attempt 3: No posts yet...
RepConnieConway, attempt 4: No posts yet...
RepConnieConway, attempt 5: No posts yet...
RepConnieConway, attempt 6: No posts yet...
RepConnieConway, attempt 7: No posts yet...
RepConnieConway, attempt 8: No posts yet...
RepConnieConway, attempt 9: No posts yet...
RepConnieConway, attempt 10: No posts yet...
No posts found for RepConnieConway, skipping save.

=== Processing RepSpartz ===
Task started for RepSpartz: 202
RepSpartz: Retrieved 25 posts
Saved posts to RepSpartz.json

=== Processing RepFrenchHill ===
Task started for RepFrenchHill: 202
RepFrenchHill: Retrieved 25 posts
Saved posts to RepFrenchHill.json

=== Processing RepChrisStewart ===
Task started for RepChrisStewart: 202
RepChrisStewart: Retrieved 22 posts
Saved posts to RepChrisStewart.json

=== Processing RepHankJohnson ===
Task started for RepHankJohnson: 202
RepHankJohnson: Retrieved 25 posts
Saved posts to RepHankJohnson.json

=== Processing RepJimCosta ===
Task started for RepJimCosta: 202
RepJimCosta: Retrieved 25 posts
Saved posts to RepJimCosta.json

=== Processing RepMaloyUtah ===
Task started for RepMaloyUtah: 202
RepMaloyUtah: Retrieved 17 posts
Saved posts to RepMaloyUtah.json

=== Processing RepMaxineWaters ===
Task started for RepMaxineWaters: 202
RepMaxineWaters: Retrieved 19 posts
Saved posts to RepMaxineWaters.json

=== Processing RepKeithSelf ===
Task started for RepKeithSelf: 202
RepKeithSelf: Retrieved 25 posts
Saved posts to RepKeithSelf.json

=== Processing Rep_Clyde ===
Task started for Rep_Clyde: 202
Rep_Clyde: Retrieved 25 posts
Saved posts to Rep_Clyde.json

=== Processing RepStenyHoyer ===
Task started for RepStenyHoyer: 202
RepStenyHoyer: Retrieved 25 posts
Saved posts to RepStenyHoyer.json

=== Processing RepYvetteClarke ===
Task started for RepYvetteClarke: 202
RepYvetteClarke: Retrieved 25 posts
Saved posts to RepYvetteClarke.json

=== Processing RepAlGreen ===
Task started for RepAlGreen: 202
RepAlGreen: Retrieved 25 posts
Saved posts to RepAlGreen.json

=== Processing RepCiscomani ===
Task started for RepCiscomani: 202
RepCiscomani: Retrieved 25 posts
Saved posts to RepCiscomani.json

=== Processing RepAndyBarr ===
Task started for RepAndyBarr: 202
RepAndyBarr: Retrieved 25 posts
Saved posts to RepAndyBarr.json

=== Processing RepBillJohnson ===
Task started for RepBillJohnson: 202
RepBillJohnson: Retrieved 25 posts
Saved posts to RepBillJohnson.json

=== Processing RepGaramendi ===
Task started for RepGaramendi: 202
RepGaramendi: Retrieved 25 posts
Saved posts to RepGaramendi.json

=== Processing RepDerekKilmer ===
Task started for RepDerekKilmer: 202
RepDerekKilmer: Retrieved 25 posts
Saved posts to RepDerekKilmer.json

=== Processing RepLowenthal ===
Task started for RepLowenthal: 202
RepLowenthal: Retrieved 25 posts
Saved posts to RepLowenthal.json

=== Processing RepDonDavis ===
Task started for RepDonDavis: 202
RepDonDavis: Retrieved 25 posts
Saved posts to RepDonDavis.json

=== Processing RepBlaine ===
Task started for RepBlaine: 202
RepBlaine: Retrieved 13 posts
Saved posts to RepBlaine.json

=== Processing RepFields ===
Task started for RepFields: 202
RepFields: Retrieved 15 posts
Saved posts to RepFields.json

=== Processing RepNikema ===
Task started for RepNikema: 202
RepNikema: Retrieved 25 posts
Saved posts to RepNikema.json

=== Processing RepRickCrawford ===
Task started for RepRickCrawford: 202
RepRickCrawford: Retrieved 15 posts
Saved posts to RepRickCrawford.json

=== Processing RepBonamici ===
Task started for RepBonamici: 202
RepBonamici: Retrieved 25 posts
Saved posts to RepBonamici.json

=== Processing RepAdams ===
Task started for RepAdams: 202
RepAdams: Retrieved 25 posts
Saved posts to RepAdams.json

=== Processing Malinowski ===
Task started for Malinowski: 202
Malinowski: Retrieved 25 posts
Saved posts to Malinowski.json

=== Processing DebbieLesko ===
Task started for DebbieLesko: 202
DebbieLesko: Retrieved 25 posts
Saved posts to DebbieLesko.json

=== Processing RepBurgessOwens ===
Task started for RepBurgessOwens: 202
RepBurgessOwens: Retrieved 25 posts
Saved posts to RepBurgessOwens.json

=== Processing RepRobinKelly ===
Task started for RepRobinKelly: 202
RepRobinKelly: Retrieved 25 posts
Saved posts to RepRobinKelly.json

=== Processing RepWesleyBellMO ===
Task started for RepWesleyBellMO: 202
RepWesleyBellMO: Retrieved 25 posts
Saved posts to RepWesleyBellMO.json

=== Processing RepRashida ===
Task started for RepRashida: 202
RepRashida: Retrieved 25 posts
Saved posts to RepRashida.json


In [ ]:
AUTOMATING REPLIES FOR NON-HEALTH TWEETS

In [1025]:
import os
import json
import requests
import time

# ------------------------------------
# START AT RepWexton AND GO DOWNWARD
# ------------------------------------
handles_series = final_df["X Handle"].dropna()

if "RepWexton" in handles_series.values:
    start_index = handles_series[handles_series == "RepWexton"].index[0]
    usernames_to_process = final_df.loc[start_index:, "X Handle"].dropna().unique()
else:
    print("RepWexton not found. Starting from top.")
    usernames_to_process = handles_series.unique()

# ------------------------------------
# LOOP THROUGH EACH POLITICIAN
# ------------------------------------
for username in usernames_to_process:

    print(f"\nProcessing politician: {username}")

    input_filename = f"{username}.json"
    output_filename = f"{username} Replies.json"

    # ------------------------------------
    # SKIP IF POSTS FILE DOESN'T EXIST
    # ------------------------------------
    if not os.path.exists(input_filename):
        print(f"Skipping {input_filename} (file not found)")
        continue

    # ------------------------------------
    # OPEN POSTS FILE
    # ------------------------------------
    with open(input_filename, "r", encoding="utf-8") as f:
        post_data = json.load(f)

    posts = post_data.get("data", {}).get("items", [])

    if not posts:
        print(f"No posts found in {input_filename}, skipping.")
        continue

    all_replies_output = []

    # ------------------------------------
    # FETCH REPLIES FOR EACH POST
    # ------------------------------------
    for post in posts:
        conversation_id = post.get("conversation_id")

        if not conversation_id:
            continue

        print(f"Fetching replies for {username} - {conversation_id}")

        replies_url = (
            f"{API_BASE_URL}{API_VERSION}/twitter/profile/"
            f"{username}/feed/posts/{conversation_id}/replies"
        )

        params = {
            "order_by": "date_desc",
            "max_page_size": 50,
            "access_token": API_AUTHORIZATION_TOKEN
        }

        response = requests.get(replies_url, params=params)

        if response.status_code == 200:
            replies_json = response.json()
            replies_items = replies_json.get("data", {}).get("items", [])

            all_replies_output.append({
                "conversation_id": conversation_id,
                "replies": replies_items
            })
        else:
            print(f"Failed for {conversation_id}: {response.status_code}")

        time.sleep(1)  # rate limit safety

    # ------------------------------------
    # SAVE OUTPUT
    # ------------------------------------
    if all_replies_output:

        final_output = {
            "politician": username,
            "posts": all_replies_output
        }

        with open(output_filename, "w", encoding="utf-8") as f:
            json.dump(final_output, f, indent=4)

        print(f"Saved: {output_filename}")
    else:
        print(f"No replies found for {username}")

print("\nAll politicians processed.")

Processing politician: RepWexton
Fetching replies for RepWexton - 1479151898661953543
Fetching replies for RepWexton - 1484643995011661825
Fetching replies for RepWexton - 1487554754976825348
Fetching replies for RepWexton - 1499444166085984259
Fetching replies for RepWexton - 1500955342859030535
Fetching replies for RepWexton - 1506686389148176395
Fetching replies for RepWexton - 1509233047257985034
Fetching replies for RepWexton - 1509654794306265090
Fetching replies for RepWexton - 1511431850903883787
Fetching replies for RepWexton - 1524409962318946304
Fetching replies for RepWexton - 1529159267898499076
Fetching replies for RepWexton - 1554585009570340864
Fetching replies for RepWexton - 1558117201885945856
Fetching replies for RepWexton - 1560679337833025537
Fetching replies for RepWexton - 1567557199660040194
Fetching replies for RepWexton - 1574824888807952391
Fetching replies for RepWexton - 1580269879793315842
Fetching replies for RepWexton - 1587535844361093120
Fetching replies for RepWexton - 1587560267218817024
Fetching replies for RepWexton - 1599899376893456384
Fetching replies for RepWexton - 1610692108339515393
Fetching replies for RepWexton - 1611409369538924544
Fetching replies for RepWexton - 1613217471653367809
Fetching replies for RepWexton - 1615858251241000960
Fetching replies for RepWexton - 1618373394118086657
Saved: RepWexton Replies.json

Processing politician: TomColeOK04
Fetching replies for TomColeOK04 - 1481698296213221382
Fetching replies for TomColeOK04 - 1504883512536616966
Fetching replies for TomColeOK04 - 1506027923433742345
Fetching replies for TomColeOK04 - 1509216300211613699
Fetching replies for TomColeOK04 - 1522653498545946627
Fetching replies for TomColeOK04 - 1526230277227429888
Fetching replies for TomColeOK04 - 1527051135848169475
Fetching replies for TomColeOK04 - 1540001748139622404
Fetching replies for TomColeOK04 - 1540081519804485635
Fetching replies for TomColeOK04 - 1540344909592510466
Fetching replies for TomColeOK04 - 1546898698113884160
Fetching replies for TomColeOK04 - 1569820557327179776
Fetching replies for TomColeOK04 - 1572603061700530176
Fetching replies for TomColeOK04 - 1579936158574071809
Fetching replies for TomColeOK04 - 1587913099952410624
Fetching replies for TomColeOK04 - 1593352196330078210
Fetching replies for TomColeOK04 - 1626007965122560005
Fetching replies for TomColeOK04 - 1653791558318039044
Fetching replies for TomColeOK04 - 1659565771457024004
Fetching replies for TomColeOK04 - 1696642888224882737
Fetching replies for TomColeOK04 - 1696642888224882737
Fetching replies for TomColeOK04 - 1706311747949179322
Fetching replies for TomColeOK04 - 1706311747949179322
Fetching replies for TomColeOK04 - 1715414215593165066
Fetching replies for TomColeOK04 - 1733152084411744554
Saved: TomColeOK04 Replies.json

Processing politician: RepLoisFrankel
Fetching replies for RepLoisFrankel - 1479101113517416450
Fetching replies for RepLoisFrankel - 1481749531184275456
Fetching replies for RepLoisFrankel - 1482071607900262400
Fetching replies for RepLoisFrankel - 1483560105203441665
Fetching replies for RepLoisFrankel - 1484537853073838082
Fetching replies for RepLoisFrankel - 1486718716922380301
Fetching replies for RepLoisFrankel - 1489684506743300096
Fetching replies for RepLoisFrankel - 1501979773492506627
Fetching replies for RepLoisFrankel - 1528813522146283524
Fetching replies for RepLoisFrankel - 1530196375392210945
Fetching replies for RepLoisFrankel - 1537478002497421314
Fetching replies for RepLoisFrankel - 1539692974988316677
Fetching replies for RepLoisFrankel - 1540427822430388224
Fetching replies for RepLoisFrankel - 1540427822430388224
Fetching replies for RepLoisFrankel - 1552368335526002688
Fetching replies for RepLoisFrankel - 1567506557239263233
Fetching replies for RepLoisFrankel - 1571939106459992064
Fetching replies for RepLoisFrankel - 1572623589194747907
Fetching replies for RepLoisFrankel - 1575902993915977734
Fetching replies for RepLoisFrankel - 1588255870009323520
Fetching replies for RepLoisFrankel - 1598364183695069184
Fetching replies for RepLoisFrankel - 1622635480897421314
Fetching replies for RepLoisFrankel - 1631372761623830532
Fetching replies for RepLoisFrankel - 1625586072636776451
Fetching replies for RepLoisFrankel - 1633479537093754882
Saved: RepLoisFrankel Replies.json

Processing politician: RepJillTokuda
Fetching replies for RepJillTokuda - 1717663899799961690
Fetching replies for RepJillTokuda - 1717663899799961690
Fetching replies for RepJillTokuda - 1722301700206174296
Fetching replies for RepJillTokuda - 1745898763259084909
Fetching replies for RepJillTokuda - 1765440055282434147
Fetching replies for RepJillTokuda - 1773838859455094971
Fetching replies for RepJillTokuda - 1806061538660487590
Fetching replies for RepJillTokuda - 1808699133496283262
Fetching replies for RepJillTokuda - 1810503185158865399
Fetching replies for RepJillTokuda - 1814476469227475253
Fetching replies for RepJillTokuda - 1815556152282726821
Fetching replies for RepJillTokuda - 1817005532760207668
Fetching replies for RepJillTokuda - 1818025904888758746
Fetching replies for RepJillTokuda - 1818432326440825085
Fetching replies for RepJillTokuda - 1833295333712908715
Fetching replies for RepJillTokuda - 1836126974122557608
Fetching replies for RepJillTokuda - 1838343613584974118
Fetching replies for RepJillTokuda - 1839757023505744149
Fetching replies for RepJillTokuda - 1840930492377444551
Fetching replies for RepJillTokuda - 1842998202016080087
Fetching replies for RepJillTokuda - 1846995458717372877
Fetching replies for RepJillTokuda - 1849201654211518727
Fetching replies for RepJillTokuda - 1852462228248653965
Fetching replies for RepJillTokuda - 1853929413575942268
Fetching replies for RepJillTokuda - 1857199344803307736
Saved: RepJillTokuda Replies.json

Processing politician: michaelgwaltz
Fetching replies for michaelgwaltz - 1478482039234039812
Fetching replies for michaelgwaltz - 1479851137146798083
Fetching replies for michaelgwaltz - 1481735104342986759
Fetching replies for michaelgwaltz - 1484612260198817795
Fetching replies for michaelgwaltz - 1489229202150805508
Fetching replies for michaelgwaltz - 1501659813599748103
Fetching replies for michaelgwaltz - 1507024691835244544
Fetching replies for michaelgwaltz - 1511791472625995784
Fetching replies for michaelgwaltz - 1523849241642340363
Fetching replies for michaelgwaltz - 1549042387636604928
Fetching replies for michaelgwaltz - 1575479448236953603
Fetching replies for michaelgwaltz - 1577700894849630213
Fetching replies for michaelgwaltz - 1583511625721843712
Fetching replies for michaelgwaltz - 1595779518949912576
Fetching replies for michaelgwaltz - 1653386572169990150
Fetching replies for michaelgwaltz - 1666534132619280385
Fetching replies for michaelgwaltz - 1678434237949542401
Fetching replies for michaelgwaltz - 1678435298374557696
Fetching replies for michaelgwaltz - 1701595160549937501
Fetching replies for michaelgwaltz - 1707005690483487107
Fetching replies for michaelgwaltz - 1725692177399902484
Fetching replies for michaelgwaltz - 1737128654654820662
Fetching replies for michaelgwaltz - 1745616158819004641
Fetching replies for michaelgwaltz - 1749536050634957307
Fetching replies for michaelgwaltz - 1765930562521293250
Saved: michaelgwaltz Replies.json

Processing politician: RepTerriSewell
Fetching replies for RepTerriSewell - 1488955345644965896
Fetching replies for RepTerriSewell - 1488960600151855104
Fetching replies for RepTerriSewell - 1494330279384653824
Fetching replies for RepTerriSewell - 1502393378641698819
Fetching replies for RepTerriSewell - 1506715826942095362
Fetching replies for RepTerriSewell - 1514351753826910214
Fetching replies for RepTerriSewell - 1516557100889124867
Fetching replies for RepTerriSewell - 1527308170342834176
Fetching replies for RepTerriSewell - 1536830649239326720
Fetching replies for RepTerriSewell - 1536830649239326720
Fetching replies for RepTerriSewell - 1540003984135561217
Fetching replies for RepTerriSewell - 1570573897774530560
Fetching replies for RepTerriSewell - 1595224117917122560
Fetching replies for RepTerriSewell - 1600519071631659009
Fetching replies for RepTerriSewell - 1606441840512729093
Fetching replies for RepTerriSewell - 1606441840512729093
Fetching replies for RepTerriSewell - 1656701554781462528
Fetching replies for RepTerriSewell - 1699538724315422814
Fetching replies for RepTerriSewell - 1699880848885969390
Fetching replies for RepTerriSewell - 1750584607664185767
Fetching replies for RepTerriSewell - 1753523714417693169
Fetching replies for RepTerriSewell - 1754304785140863421
Fetching replies for RepTerriSewell - 1760728302682296592
Fetching replies for RepTerriSewell - 1777811150211596714
Fetching replies for RepTerriSewell - 1780971123422744711
Saved: RepTerriSewell Replies.json

Processing politician: RepJeffHurd
Fetching replies for RepJeffHurd - 1884293586034028588
Fetching replies for RepJeffHurd - 1885112307719536770
Fetching replies for RepJeffHurd - 1885364298093859331
Fetching replies for RepJeffHurd - 1887653456426500354
Fetching replies for RepJeffHurd - 1888622749469294798
Fetching replies for RepJeffHurd - 1891974786248548435
Fetching replies for RepJeffHurd - 1892213913665548347
Fetching replies for RepJeffHurd - 1893332459237917127
Fetching replies for RepJeffHurd - 1894130449170985461
Fetching replies for RepJeffHurd - 1897073374628601945
Fetching replies for RepJeffHurd - 1910384282729873579
Fetching replies for RepJeffHurd - 1911828122132947402
Fetching replies for RepJeffHurd - 1913393417859539415
Fetching replies for RepJeffHurd - 1915050675811078215
Fetching replies for RepJeffHurd - 1915080878641893563
Fetching replies for RepJeffHurd - 1915443281837670720
Fetching replies for RepJeffHurd - 1915474536469844412
Fetching replies for RepJeffHurd - 1919814987830182399
Fetching replies for RepJeffHurd - 1936189068003463413
Fetching replies for RepJeffHurd - 1960840343814898126
Fetching replies for RepJeffHurd - 1965828779034419396
Fetching replies for RepJeffHurd - 1970879727670894797
Fetching replies for RepJeffHurd - 1972756943929217270
Fetching replies for RepJeffHurd - 1975950630591111612
Fetching replies for RepJeffHurd - 1976800061255282762
Saved: RepJeffHurd Replies.json

Processing politician: RepSheriBiggs
Fetching replies for RepSheriBiggs - 1902328119110869125
Fetching replies for RepSheriBiggs - 1919802191461699584
Fetching replies for RepSheriBiggs - 1927060663941148909
Fetching replies for RepSheriBiggs - 1948468391712620875
Fetching replies for RepSheriBiggs - 1960083562079863185
Fetching replies for RepSheriBiggs - 1960767592085512602
Fetching replies for RepSheriBiggs - 1972707723864154399
Fetching replies for RepSheriBiggs - 1974177730498306532
Fetching replies for RepSheriBiggs - 1976699945492070831
Fetching replies for RepSheriBiggs - 1993817734501568837
Fetching replies for RepSheriBiggs - 1996701702037336573
Fetching replies for RepSheriBiggs - 2000635116498940201
Saved: RepSheriBiggs Replies.json

Processing politician: RepDanCrenshaw
Fetching replies for RepDanCrenshaw - 1648067040849145856
Fetching replies for RepDanCrenshaw - 1786078054382551091
Fetching replies for RepDanCrenshaw - 1798786864746467782
Fetching replies for RepDanCrenshaw - 1859329523155685605
Fetching replies for RepDanCrenshaw - 1866557616895521162
Fetching replies for RepDanCrenshaw - 1868097152309961158
Fetching replies for RepDanCrenshaw - 1868097152309961158
Fetching replies for RepDanCrenshaw - 1869048114817978859
Fetching replies for RepDanCrenshaw - 1869444947893489953
Fetching replies for RepDanCrenshaw - 1877748340516880402
Fetching replies for RepDanCrenshaw - 1881795196847071520
Fetching replies for RepDanCrenshaw - 1884414187612643402
Fetching replies for RepDanCrenshaw - 1886585362216104121
Fetching replies for RepDanCrenshaw - 1889347710148374987
Fetching replies for RepDanCrenshaw - 1899251776290713712
Fetching replies for RepDanCrenshaw - 1899949999749837282
Fetching replies for RepDanCrenshaw - 1904710894069698650
Fetching replies for RepDanCrenshaw - 1907436334261690766
Fetching replies for RepDanCrenshaw - 1909753962183409747
Fetching replies for RepDanCrenshaw - 1918091777459757563
Fetching replies for RepDanCrenshaw - 1918091777459757563
Fetching replies for RepDanCrenshaw - 1922400295969005578
Fetching replies for RepDanCrenshaw - 1925257955319906710
Fetching replies for RepDanCrenshaw - 1927727594377519596
Fetching replies for RepDanCrenshaw - 1927727594377519596
Saved: RepDanCrenshaw Replies.json

Processing politician: RepMann
Fetching replies for RepMann - 1853784330230771936
Fetching replies for RepMann - 1858986106408366204
Fetching replies for RepMann - 1907153493955133859
Fetching replies for RepMann - 1915103889767924121
Fetching replies for RepMann - 1919889921877348563
Fetching replies for RepMann - 1922804124053049828
Fetching replies for RepMann - 1923439732073054244
Fetching replies for RepMann - 1924880550193725622
Fetching replies for RepMann - 1926043154538496420
Fetching replies for RepMann - 1927787454960128411
Fetching replies for RepMann - 1929974616077873393
Fetching replies for RepMann - 1930254460426825953
Fetching replies for RepMann - 1930677565737304202
Fetching replies for RepMann - 1932886702328062344
Fetching replies for RepMann - 1942725673782485343
Fetching replies for RepMann - 1943336242889777418
Fetching replies for RepMann - 1945646624656822448
Fetching replies for RepMann - 1948748321209942312
Fetching replies for RepMann - 1951295516462964745
Fetching replies for RepMann - 1957529923674866050
Fetching replies for RepMann - 1958256026794230005
Fetching replies for RepMann - 1961164383503171974
Fetching replies for RepMann - 1961519224717021441
Fetching replies for RepMann - 1963974949422661837
Fetching replies for RepMann - 1965159624828449069
Saved: RepMann Replies.json

Processing politician: Carolyn4GA7
Fetching replies for Carolyn4GA7 - 1482057967222591493
Fetching replies for Carolyn4GA7 - 1487125573180739584
Fetching replies for Carolyn4GA7 - 1489253096408567818
Fetching replies for Carolyn4GA7 - 1489318276136112132
Fetching replies for Carolyn4GA7 - 1491105805927686151
Fetching replies for Carolyn4GA7 - 1494741021808340993
Fetching replies for Carolyn4GA7 - 1495814078899671040
Fetching replies for Carolyn4GA7 - 1496580037776134153
Fetching replies for Carolyn4GA7 - 1496584267706552320
Fetching replies for Carolyn4GA7 - 1498714631430410246
Fetching replies for Carolyn4GA7 - 1499778450126692353
Fetching replies for Carolyn4GA7 - 1501656577538990087
Fetching replies for Carolyn4GA7 - 1501939898231627782
Fetching replies for Carolyn4GA7 - 1501969887916437505
Fetching replies for Carolyn4GA7 - 1502306283793395712
Fetching replies for Carolyn4GA7 - 1502365924694839297
Fetching replies for Carolyn4GA7 - 1504512910080544773
Fetching replies for Carolyn4GA7 - 1508524828738953222
Fetching replies for Carolyn4GA7 - 1511127284794724363
Fetching replies for Carolyn4GA7 - 1511826095225647109
Fetching replies for Carolyn4GA7 - 1511826095225647109
Fetching replies for Carolyn4GA7 - 1512083033830019086
Fetching replies for Carolyn4GA7 - 1512083033830019086
Fetching replies for Carolyn4GA7 - 1513456832605474817
Fetching replies for Carolyn4GA7 - 1513867530623803399
Saved: Carolyn4GA7 Replies.json

Processing politician: RepKweisiMfume
Fetching replies for RepKweisiMfume - 1522670660073447424
Fetching replies for RepKweisiMfume - 1552682283596922882
Fetching replies for RepKweisiMfume - 1564260649307455490
Fetching replies for RepKweisiMfume - 1568338888154034176
Fetching replies for RepKweisiMfume - 1571932724340068353
Fetching replies for RepKweisiMfume - 1575154454269239296
Fetching replies for RepKweisiMfume - 1585333366744043520
Fetching replies for RepKweisiMfume - 1597322757498613760
Fetching replies for RepKweisiMfume - 1600899606795075584
Fetching replies for RepKweisiMfume - 1603209773125488640
Fetching replies for RepKweisiMfume - 1623405044979597312
Fetching replies for RepKweisiMfume - 1686382902765096960
Fetching replies for RepKweisiMfume - 1687810934746521600
Fetching replies for RepKweisiMfume - 1691951388505317636
Fetching replies for RepKweisiMfume - 1738631181824823795
Fetching replies for RepKweisiMfume - 1748440858242720080
Fetching replies for RepKweisiMfume - 1756768798055497919
Fetching replies for RepKweisiMfume - 1781021554270204139
Fetching replies for RepKweisiMfume - 1824272928214794390
Fetching replies for RepKweisiMfume - 1831317097512865929
Fetching replies for RepKweisiMfume - 1874528269317681294
Fetching replies for RepKweisiMfume - 1890525028258611420
Fetching replies for RepKweisiMfume - 1890844215036506324
Fetching replies for RepKweisiMfume - 1892335278314156195
Fetching replies for RepKweisiMfume - 1893745635897352647
Saved: RepKweisiMfume Replies.json

Processing politician: RepMarkGreen
Fetching replies for RepMarkGreen - 1537922398334251011
Fetching replies for RepMarkGreen - 1559961799079985152
Fetching replies for RepMarkGreen - 1595146066038779906
Fetching replies for RepMarkGreen - 1689758522383519744
Fetching replies for RepMarkGreen - 1691953594495304122
Fetching replies for RepMarkGreen - 1751620055773639156
Fetching replies for RepMarkGreen - 1770865742272971167
Fetching replies for RepMarkGreen - 1773757579329495228
Fetching replies for RepMarkGreen - 1796533410556747788
Fetching replies for RepMarkGreen - 1840140287601193246
Fetching replies for RepMarkGreen - 1841139537071743357
Fetching replies for RepMarkGreen - 1851323117165305963
Fetching replies for RepMarkGreen - 1852063325594808407
Fetching replies for RepMarkGreen - 1859311196123385875
Fetching replies for RepMarkGreen - 1859718431542542731
Fetching replies for RepMarkGreen - 1884315915405173103
Fetching replies for RepMarkGreen - 1886777007964303523
Fetching replies for RepMarkGreen - 1887501717207490631
Fetching replies for RepMarkGreen - 1892937634093084883
Fetching replies for RepMarkGreen - 1895172839260463322
Fetching replies for RepMarkGreen - 1902103037126066469
Fetching replies for RepMarkGreen - 1905379545567355076
Fetching replies for RepMarkGreen - 1905600324456378873
Fetching replies for RepMarkGreen - 1905642236659777930
Fetching replies for RepMarkGreen - 1905644768899502399
Saved: RepMarkGreen Replies.json

Processing politician: CongressMin
Fetching replies for CongressMin - 1902128222143435094
Fetching replies for CongressMin - 1903913999932039425
Fetching replies for CongressMin - 1910826701711437908
Fetching replies for CongressMin - 1924472002246484176
Fetching replies for CongressMin - 1936116737193431144
Fetching replies for CongressMin - 1937676102106792066
Fetching replies for CongressMin - 1938324607741702217
Fetching replies for CongressMin - 1939705370240274490
Fetching replies for CongressMin - 1940101401352310786
Fetching replies for CongressMin - 1940512820807786830
Fetching replies for CongressMin - 1940841468840890802
Fetching replies for CongressMin - 1945964593492209968
Fetching replies for CongressMin - 1950678001609240783
Fetching replies for CongressMin - 1952381636047458461
Fetching replies for CongressMin - 1961086345633243621
Fetching replies for CongressMin - 1966612063364464774
Fetching replies for CongressMin - 1967680016449523841
Fetching replies for CongressMin - 1973045126462079280
Fetching replies for CongressMin - 1973795336511799754
Fetching replies for CongressMin - 1974222152820732352
Fetching replies for CongressMin - 1976011340750913979
Fetching replies for CongressMin - 1976039357644714059
Fetching replies for CongressMin - 1978138694407074014
Fetching replies for CongressMin - 1978938878506512649
Fetching replies for CongressMin - 1980373692069867830
Saved: CongressMin Replies.json

Processing politician: Liz_Cheney
Skipping Liz_Cheney.json (file not found)

Processing politician: RepJasonCrow
Fetching replies for RepJasonCrow - 1491078304983826433

In [23]:
politicians = """
AlLawsonJr
AlbioSiresNJ
Andy_Levin
Axne4Congress
BHigginsBflo
BennieGThompson
BettyMcCollum04
BillPoseyFL
BobbyLRush
BobbyScott
BradSherman
Call_Me_Dutch
CarlForAlabama
ColinAllredTX
CongBoyle
CongMikeSimpson
CongressmanKean
CongressmanRaja
CongresswomanSC
ConorLambPA
DPrice4Congress
DesJarlaisTN04
DorisMatsui
DrNealDunnFL2
ElaineLuriaVA
EleanorNorton
FrankPallone
GKButterfield
GOPMajorityWhip
GerryConnolly
Hill4MNHouse
Ilhan
JacksonLeeTX18
JakeLaTurner
JayObernolte
JimLangevin
Jim_Jordan
JoaquinCastrotx
JodyHiceFRCA
JohnMannionNY22
JohnYarmuth
JudgeCarter
KellyMorrisonMN
KenCalvert
Kilili_Sablan
MarioDB
MattForMontana
MichelleSteelCA
MikeGarciaCA27
NydiaVelazquez
OAGMaryland
PatronisFL
PeterMeijer
RepAOC
RepAdamGrayCA
RepAdamSmith
RepAdrianSmith
RepAlexMooney
RepAndyBiggsAZ
RepAndyHarrisMD
RepAnnWagner
RepAnnieKuster
RepArrington
RepAshleyHinson
RepBalderson
RepBarbaraLee
RepBarragan
RepBarryMoore
RepBeatty
RepBeccaB
RepBenCline
RepBentz
RepBera
RepBice
RepBillFoster
RepBlakeMoore
RepBobGood
RepBoebert
RepBonnie
RepBost
RepBrandonGill
RepBrecheen
RepBresnahan
RepBrianFitz
RepBrianJack
RepBrianMast
RepBryanSteil
RepBynum
RepCarbajal
RepCarolMiller
RepCartwright
RepCasar
RepCheri
RepClayHiggins
RepCraigGoldman
RepDLamborn
RepDWStweets
RepDanKildee
RepDannyDavis
RepDarrenSoto
RepDaveTaylor
RepDavid
RepDavidKustoff
RepDavidRouzer
RepDavidValadao
RepDavids
RepDeSaulnier
RepDebDingell
RepDeborahRoss
RepDeluzio
RepDerekSchmidt
RepDexterOR
RepDianaDeGette
RepDonBeyer
RepDonaldPayne
RepDrewFerguson
RepDustyJohnson
RepDwightEvans
RepEBJ
RepEllzey
RepEricBurlison
RepEricSorensen
RepEzell
RepFedorchak
RepFeenstra
RepFine
RepFischbach
RepFitzgerald
RepFletcher
RepFrankLucas
RepFredKeller
RepFredUpton
RepFriedmanCA
RepGLatimer
RepGabeAmo
RepGabeVasquez
RepGarbarino
RepGarretGraves
RepGilCisneros
RepGlennIvey
RepGolden
RepGonzalez
RepGosar
RepGregLandsman
RepGregMurphy
RepGregStanton
RepGregSteube
RepGregoryMeeks
RepGrothman
RepGwenMoore
RepHageman
RepHaleyStevens
RepHarshbarger
RepHartzler
RepHorsford
RepHouchin
RepHuizenga
RepJacobs
RepJasonSmith
RepJeffDuncan
RepJeffries
RepJerryNadler
RepJimBaird
RepJimmyPanetta
RepJoeNeguse
RepJohnLarson
RepJohnMcGuire
RepJoshHarder
RepJudyChu
RepJulieJohnson
RepKManning
RepKahele
RepKamlagerDove
RepKatiePorter
RepKenBuck
RepKevinMullin
RepKiggans
RepKiley
RepKnott
RepLSimon
RepLaHood
RepLaLota
RepLaMalfa
RepLaMonica
RepLangworthy
RepLarryBucshon
RepLauraGillen
RepLawrence
RepLiccardo
RepLindaSanchez
RepLisaMcClain
RepLloydDoggett
RepLoriTrahan
RepLouCorrea
RepLoudermilk
RepLuna
RepLuttrell
RepMGS
RepMGriffith
RepMMM
RepMackenzie
RepMalliotakis
RepMaloney
RepMarcyKaptur
RepMariaSalazar
RepMarkAlford
RepMarkHarrisNC
RepMarkTakano
RepMaxMiller
RepMaxwellFrost
RepMcClellan
RepMcDowell
RepMcGarvey
RepMcGovern
RepMcKinley
RepMessmer
RepMeuser
RepMichaelCloud
RepMichaelGuest
RepMichaelRulli
RepMikeCarey
RepMikeCollins
RepMikeKennedy
RepMikeLawler
RepMikeLevin
RepMikeRogersAL
RepMikeTurner
RepMillsPress
RepMoBrooks
RepMoolenaar
RepMoulton
RepMoylan
RepMrvan
RepNancyMace
RepNateMoran
RepNellie
RepNewhouse
RepNickBegich
RepNikkiB
RepOHalleran
RepOgles
RepPabloJose
RepPatHarrigan
RepPatRyanNY
RepPaulTonko
RepPeteStauber
RepPeterDeFazio
RepPressley
RepRalphNorman
RepRaskin
RepRaulRuizMD
RepRichardNeal
RepRickAllen
RepRickLarsen
RepRitchie
RepRoKhanna
RepRobertGarcia
RepRonKind
RepRonnyJackson
RepRoybalAllard
RepRudyYakym
RepRussFulcher
RepRussellFry
RepRutherfordFL
RepRyanZinke
RepSalinas
RepSamGraves
RepSaraJacobs
RepSarahElfreth
RepSchakowsky
RepSchneider
RepScholten
RepSchrader
RepScottPerry
RepScottPeters
RepSeanMaloney
RepSempolinski
RepShontelBrown
RepShriThanedar
RepSpeier
RepStefanik
RepSteveChabot
RepStutzman
RepSuhas
RepSummerLee
RepSusanWild
RepSusieLee
RepSwalwell
RepTenney
RepThomasMassie
RepTimBurchett
RepTimKennedy
RepTimMooreNC
RepTimmons
RepTomBarrett
RepTomSuozzi
RepTonyGonzales
RepTonyWied
RepTroyCarter
RepTroyDowning
RepTroyNehls
RepUnderwood
RepVanTaylor
RepVinceFong
RepVindman
RepWalberg
RepWesleyHunt
RepWilson
RepYoungKim
RepZoeLofgren
Rep_Grijalva
Rep_McBride
Rep_Stansbury
Rep_Walkinshaw
Rep_Whitesides
RobWittman
Robert_Aderholt
RodneyDavis
SanfordBishop
SenMcNerney
SpeakerJohnson
SpeakerMcCarthy
SpeakerPelosi
StaceyPlaskett
SteveScalise
TXRandy14
TimRyan
USRepGaryPalmer
USRepMikeDoyle
USRepMikeFlood
ValerieFoushee
VernBuchanan
WhipClyburn
WhipKClark
auctnr1
boblatta
chelliepingree
davidjtrone
gracenapolitano
jimcoopertn
mattgaetz
michaelcburgess
rep_stevewomack
repblumenauer
repcleaver
repdarrellissa
repdavidscott
repdeliaramirez
repfinstad
repgabeevans
repkevinhern
repmarkpocan
repvalhoyle
rosadelauro
virginiafoxx
"""

politician_list = [p.strip() for p in politicians.split("\n") if p.strip()]

new_df = pd.DataFrame({
    "X Handle": politician_list
})

In [ ]:
AUTOMATE HEALTH-RELATED TWEETS FOR SECOND HALF

In [29]:
import pandas as pd
import requests
import time
import json

API_BASE_URL = "https://api.data365.co"
API_VERSION = "/v1.1"
API_AUTHORIZATION_TOKEN = "ZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKSVV6STFOaUo5LmV5SnpkV0lpT2lKSWFXSmhRV3hwSWl3aWFXRjBJam94TnpZNU5UQTNOamcyTGpBd05UQXhPSDAuNmpTLTZtbVBGV0F1ZS1McHhXaUIwbUtDUWFDemU4VkRNZVhOSkZ2ckJRTQ=="

# Keyword blocks
KEYWORD_BLOCKS = {
    "1A": "health OR medicine OR medical OR medication",
    "1B": "treatment OR symptoms OR diagnosis",
    "2A": "healthcare OR insurance OR medicare OR medicaid",
    "2B": "premiums OR coverage OR patients OR hospitals",
    "3": "flu OR pneumonia OR bronchitis OR strep throat OR sore throat OR cough OR fever OR infection OR contagious",
    "4": "high blood pressure OR hypertension OR heart OR heart disease OR heart rate OR stroke OR cholesterol OR diabetes OR cancer",
    "5": "lupus OR autoimmune OR chronic illness OR inflammation OR immune system",
    "6": "hydration OR diet OR nutrition OR exercise OR workout OR sleep OR wellness"
}

# ------------------------
# Function to fetch posts only
# ------------------------
def fetch_posts(username, block_name, keywords, max_attempts=10, sleep_time=2):
    update_url = f"{API_BASE_URL}{API_VERSION}/twitter/search/post/update"
    posts_url = f"{API_BASE_URL}{API_VERSION}/twitter/search/post/posts"

    params = {
        "from_profile": username,
        "from_date": "2022-01-01",
        "to_date": "2025-12-31",
        "lang": "en",
        "max_posts": 20,
        "search_type": "latest",
        "max_replies": 3,
        "load_replies": "true",
        "keywords": keywords,
        "access_token": API_AUTHORIZATION_TOKEN
    }

    # Start the search task
    post_response = requests.post(update_url, params=params)
    print(f"Task started for {username} Block {block_name}: {post_response.status_code}")

    attempt = 0
    data = {}
    while attempt < max_attempts:
        posts_response = requests.get(posts_url, params=params)
        if posts_response.status_code == 200:
            data = posts_response.json()
            items = data.get("data", {}).get("items", [])
            if items:
                print(f"{username} Block {block_name}: Retrieved {len(items)} posts")
                break
            else:
                print(f"{username} Block {block_name}, attempt {attempt+1}: No posts yet...")
        else:
            print(f"Failed to fetch posts for {username} (attempt {attempt+1}): {posts_response.status_code}")
        attempt += 1
        time.sleep(sleep_time)

    items = data.get("data", {}).get("items", [])
    if items:
        filename = f"{username} Block {block_name}.json"
        with open(filename, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4)
        print(f"Saved posts to {filename}")
    else:
        print(f"No posts found for {username} Block {block_name}, skipping save.")

    return items

# ------------------------
# Main Execution
# ------------------------
# Assuming final_df is your DataFrame with a 'X Handle' column
start_username = "RepCasar"
start_index = new_df.index[new_df['X Handle'] == start_username][0]

for username in new_df['X Handle'].iloc[start_index:]:
    print(f"\n=== Processing {username} ===")
    for block_name, keywords in KEYWORD_BLOCKS.items():
        fetch_posts(username, block_name, keywords)

=== Processing RepCasar ===
Task started for RepCasar Block 1A: 202
RepCasar Block 1A: Retrieved 20 posts
Saved posts to RepCasar Block 1A.json
Task started for RepCasar Block 1B: 202
RepCasar Block 1B, attempt 1: No posts yet...
RepCasar Block 1B, attempt 2: No posts yet...
RepCasar Block 1B, attempt 3: No posts yet...
RepCasar Block 1B, attempt 4: No posts yet...
RepCasar Block 1B, attempt 5: No posts yet...
RepCasar Block 1B, attempt 6: No posts yet...
RepCasar Block 1B, attempt 7: No posts yet...
RepCasar Block 1B: Retrieved 14 posts
Saved posts to RepCasar Block 1B.json
Task started for RepCasar Block 2A: 202
RepCasar Block 2A, attempt 1: No posts yet...
RepCasar Block 2A, attempt 2: No posts yet...
RepCasar Block 2A, attempt 3: No posts yet...
RepCasar Block 2A, attempt 4: No posts yet...
RepCasar Block 2A: Retrieved 20 posts
Saved posts to RepCasar Block 2A.json
Task started for RepCasar Block 2B: 202
RepCasar Block 2B, attempt 1: No posts yet...
RepCasar Block 2B, attempt 2: No posts yet...
RepCasar Block 2B, attempt 3: No posts yet...
RepCasar Block 2B, attempt 4: No posts yet...
RepCasar Block 2B: Retrieved 20 posts
Saved posts to RepCasar Block 2B.json
Task started for RepCasar Block 3: 202
RepCasar Block 3, attempt 1: No posts yet...
RepCasar Block 3, attempt 2: No posts yet...
RepCasar Block 3, attempt 3: No posts yet...
RepCasar Block 3, attempt 4: No posts yet...
RepCasar Block 3, attempt 5: No posts yet...
RepCasar Block 3, attempt 6: No posts yet...
RepCasar Block 3, attempt 7: No posts yet...
RepCasar Block 3, attempt 8: No posts yet...
RepCasar Block 3, attempt 9: No posts yet...
RepCasar Block 3, attempt 10: No posts yet...
No posts found for RepCasar Block 3, skipping save.
Task started for RepCasar Block 4: 202
RepCasar Block 4, attempt 1: No posts yet...
RepCasar Block 4, attempt 2: No posts yet...
RepCasar Block 4, attempt 3: No posts yet...
RepCasar Block 4, attempt 4: No posts yet...
RepCasar Block 4, attempt 5: No posts yet...
RepCasar Block 4, attempt 6: No posts yet...
RepCasar Block 4, attempt 7: No posts yet...
RepCasar Block 4, attempt 8: No posts yet...
RepCasar Block 4, attempt 9: No posts yet...
RepCasar Block 4, attempt 10: No posts yet...
No posts found for RepCasar Block 4, skipping save.
Task started for RepCasar Block 5: 202
RepCasar Block 5, attempt 1: No posts yet...
RepCasar Block 5, attempt 2: No posts yet...
RepCasar Block 5, attempt 3: No posts yet...
RepCasar Block 5, attempt 4: No posts yet...
RepCasar Block 5, attempt 5: No posts yet...
RepCasar Block 5, attempt 6: No posts yet...
RepCasar Block 5, attempt 7: No posts yet...
RepCasar Block 5, attempt 8: No posts yet...
RepCasar Block 5, attempt 9: No posts yet...
RepCasar Block 5, attempt 10: No posts yet...
No posts found for RepCasar Block 5, skipping save.
Task started for RepCasar Block 6: 202
RepCasar Block 6, attempt 1: No posts yet...
RepCasar Block 6, attempt 2: No posts yet...
RepCasar Block 6, attempt 3: No posts yet...
RepCasar Block 6, attempt 4: No posts yet...
RepCasar Block 6, attempt 5: No posts yet...
RepCasar Block 6: Retrieved 2 posts
Saved posts to RepCasar Block 6.json

=== Processing RepCheri ===
Task started for RepCheri Block 1A: 202
RepCheri Block 1A, attempt 1: No posts yet...
RepCheri Block 1A, attempt 2: No posts yet...
RepCheri Block 1A, attempt 3: No posts yet...
RepCheri Block 1A, attempt 4: No posts yet...
RepCheri Block 1A, attempt 5: No posts yet...
RepCheri Block 1A: Retrieved 20 posts
Saved posts to RepCheri Block 1A.json
Task started for RepCheri Block 1B: 202
RepCheri Block 1B, attempt 1: No posts yet...
RepCheri Block 1B, attempt 2: No posts yet...
RepCheri Block 1B, attempt 3: No posts yet...
RepCheri Block 1B, attempt 4: No posts yet...
RepCheri Block 1B, attempt 5: No posts yet...
RepCheri Block 1B, attempt 6: No posts yet...
RepCheri Block 1B, attempt 7: No posts yet...
RepCheri Block 1B: Retrieved 5 posts
Saved posts to RepCheri Block 1B.json
Task started for RepCheri Block 2A: 202
RepCheri Block 2A, attempt 1: No posts yet...
RepCheri Block 2A, attempt 2: No posts yet...
RepCheri Block 2A, attempt 3: No posts yet...
RepCheri Block 2A, attempt 4: No posts yet...
RepCheri Block 2A, attempt 5: No posts yet...
RepCheri Block 2A, attempt 6: No posts yet...
RepCheri Block 2A: Retrieved 16 posts
Saved posts to RepCheri Block 2A.json
Task started for RepCheri Block 2B: 202
RepCheri Block 2B, attempt 1: No posts yet...
RepCheri Block 2B, attempt 2: No posts yet...
RepCheri Block 2B, attempt 3: No posts yet...
RepCheri Block 2B, attempt 4: No posts yet...
RepCheri Block 2B, attempt 5: No posts yet...
RepCheri Block 2B, attempt 6: No posts yet...
RepCheri Block 2B, attempt 7: No posts yet...
RepCheri Block 2B, attempt 8: No posts yet...
RepCheri Block 2B: Retrieved 13 posts
Saved posts to RepCheri Block 2B.json
Task started for RepCheri Block 3: 202
RepCheri Block 3, attempt 1: No posts yet...
RepCheri Block 3, attempt 2: No posts yet...
RepCheri Block 3, attempt 3: No posts yet...
RepCheri Block 3, attempt 4: No posts yet...
RepCheri Block 3, attempt 5: No posts yet...
RepCheri Block 3, attempt 6: No posts yet...
RepCheri Block 3, attempt 7: No posts yet...
RepCheri Block 3, attempt 8: No posts yet...
RepCheri Block 3, attempt 9: No posts yet...
RepCheri Block 3, attempt 10: No posts yet...
No posts found for RepCheri Block 3, skipping save.
Task started for RepCheri Block 4: 202
RepCheri Block 4, attempt 1: No posts yet...
RepCheri Block 4, attempt 2: No posts yet...
RepCheri Block 4, attempt 3: No posts yet...
RepCheri Block 4, attempt 4: No posts yet...
RepCheri Block 4, attempt 5: No posts yet...
RepCheri Block 4, attempt 6: No posts yet...
RepCheri Block 4, attempt 7: No posts yet...
RepCheri Block 4, attempt 8: No posts yet...
RepCheri Block 4, attempt 9: No posts yet...
RepCheri Block 4, attempt 10: No posts yet...
No posts found for RepCheri Block 4, skipping save.
Task started for RepCheri Block 5: 202
RepCheri Block 5, attempt 1: No posts yet...
RepCheri Block 5, attempt 2: No posts yet...
RepCheri Block 5, attempt 3: No posts yet...
RepCheri Block 5, attempt 4: No posts yet...
RepCheri Block 5, attempt 5: No posts yet...
RepCheri Block 5, attempt 6: No posts yet...
RepCheri Block 5, attempt 7: No posts yet...
RepCheri Block 5, attempt 8: No posts yet...
RepCheri Block 5, attempt 9: No posts yet...
RepCheri Block 5, attempt 10: No posts yet...
No posts found for RepCheri Block 5, skipping save.
Task started for RepCheri Block 6: 202
RepCheri Block 6, attempt 1: No posts yet...
RepCheri Block 6, attempt 2: No posts yet...
RepCheri Block 6, attempt 3: No posts yet...
RepCheri Block 6, attempt 4: No posts yet...
RepCheri Block 6, attempt 5: No posts yet...
RepCheri Block 6: Retrieved 5 posts
Saved posts to RepCheri Block 6.json

=== Processing RepClayHiggins ===
Task started for RepClayHiggins Block 1A: 202
RepClayHiggins Block 1A, attempt 1: No posts yet...
RepClayHiggins Block 1A, attempt 2: No posts yet...
RepClayHiggins Block 1A, attempt 3: No posts yet...
RepClayHiggins Block 1A, attempt 4: No posts yet...
RepClayHiggins Block 1A, attempt 5: No posts yet...
RepClayHiggins Block 1A, attempt 6: No posts yet...
RepClayHiggins Block 1A, attempt 7: No posts yet...
RepClayHiggins Block 1A, attempt 8: No posts yet...
RepClayHiggins Block 1A: Retrieved 17 posts
Saved posts to RepClayHiggins Block 1A.json
Task started for RepClayHiggins Block 1B: 202
RepClayHiggins Block 1B, attempt 1: No posts yet...
RepClayHiggins Block 1B, attempt 2: No posts yet...
RepClayHiggins Block 1B, attempt 3: No posts yet...
RepClayHiggins Block 1B, attempt 4: No posts yet...
RepClayHiggins Block 1B, attempt 5: No posts yet...
RepClayHiggins Block 1B, attempt 6: No posts yet...
RepClayHiggins Block 1B, attempt 7: No posts yet...
RepClayHiggins Block 1B, attempt 8: No posts yet...
RepClayHiggins Block 1B, attempt 9: No posts yet...
RepClayHiggins Block 1B, attempt 10: No posts yet...
No posts found for RepClayHiggins Block 1B, skipping save.
Task started for RepClayHiggins Block 2A: 202
RepClayHiggins Block 2A, attempt 1: No posts yet...
RepClayHiggins Block 2A, attempt 2: No posts yet...
RepClayHiggins Block 2A, attempt 3: No posts yet...
RepClayHiggins Block 2A, attempt 4: No posts yet...
RepClayHiggins Block 2A, attempt 5: No posts yet...
RepClayHiggins Block 2A, attempt 6: No posts yet...
RepClayHiggins Block 2A, attempt 7: No posts yet...
RepClayHiggins Block 2A, attempt 8: No posts yet...
RepClayHiggins Block 2A, attempt 9: No posts yet...
RepClayHiggins Block 2A: Retrieved 14 posts
Saved posts to RepClayHiggins Block 2A.json
Task started for RepClayHiggins Block 2B: 202
RepClayHiggins Block 2B, attempt 1: No posts yet...
RepClayHiggins Block 2B, attempt 2: No posts yet...
RepClayHiggins Block 2B, attempt 3: No posts yet...
RepClayHiggins Block 2B, attempt 4: No posts yet...
RepClayHiggins Block 2B, attempt 5: No posts yet...
RepClayHiggins Block 2B, attempt 6: No posts yet...
RepClayHiggins Block 2B, attempt 7: No posts yet...
RepClayHiggins Block 2B, attempt 8: No posts yet...
RepClayHiggins Block 2B, attempt 9: No posts yet...
RepClayHiggins Block 2B, attempt 10: No posts yet...
No posts found for RepClayHiggins Block 2B, skipping save.
Task started for RepClayHiggins Block 3: 202
RepClayHiggins Block 3, attempt 1: No posts yet...
RepClayHiggins Block 3, attempt 2: No posts yet...
RepClayHiggins Block 3, attempt 3: No posts yet...
RepClayHiggins Block 3, attempt 4: No posts yet...
RepClayHiggins Block 3, attempt 5: No posts yet...
RepClayHiggins Block 3, attempt 6: No posts yet...
RepClayHiggins Block 3, attempt 7: No posts yet...
RepClayHiggins Block 3, attempt 8: No posts yet...
RepClayHiggins Block 3, attempt 9: No posts yet...
RepClayHiggins Block 3, attempt 10: No posts yet...
No posts found for RepClayHiggins Block 3, skipping save.
Task started for RepClayHiggins Block 4: 202
RepClayHiggins Block 4, attempt 1: No posts yet...
RepClayHiggins Block 4, attempt 2: No posts yet...
RepClayHiggins Block 4, attempt 3: No posts yet...
RepClayHiggins Block 4, attempt 4: No posts yet...
RepClayHiggins Block 4, attempt 5: No posts yet...
RepClayHiggins Block 4, attempt 6: No posts yet...
RepClayHiggins Block 4, attempt 7: No posts yet...
RepClayHiggins Block 4, attempt 8: No posts yet...
RepClayHiggins Block 4, attempt 9: No posts yet...
RepClayHiggins Block 4, attempt 10: No posts yet...
No posts found for RepClayHiggins Block 4, skipping save.
Task started for RepClayHiggins Block 5: 202
RepClayHiggins Block 5, attempt 1: No posts yet...
RepClayHiggins Block 5, attempt 2: No posts yet...
RepClayHiggins Block 5, attempt 3: No posts yet...
RepClayHiggins Block 5, attempt 4: No posts yet...
RepClayHiggins Block 5, attempt 5: No posts yet...
RepClayHiggins Block 5, attempt 6: No posts yet...
RepClayHiggins Block 5, attempt 7: No posts yet...
RepClayHiggins Block 5, attempt 8: No posts yet...
RepClayHiggins Block 5, attempt 9: No posts yet...
RepClayHiggins Block 5, attempt 10: No posts yet...
No posts found for RepClayHiggins Block 5, skipping save.
Task started for RepClayHiggins Block 6: 202
RepClayHiggins Block 6, attempt 1: No posts yet...
RepClayHiggins Block 6, attempt 2: No posts yet...
RepClayHiggins Block 6, attempt 3: No posts yet...
RepClayHiggins Block 6, attempt 4: No posts yet...
RepClayHiggins Block 6, attempt 5: No posts yet...
RepClayHiggins Block 6, attempt 6: No posts yet...
RepClayHiggins Block 6, attempt 7: No posts yet...
RepClayHiggins Block 6, attempt 8: No posts yet...
RepClayHiggins Block 6, attempt 9: No posts yet...
RepClayHiggins Block 6, attempt 10: No posts yet...
No posts found for RepClayHiggins Block 6, skipping save.

=== Processing RepCraigGoldman ===
Task started for RepCraigGoldman Block 1A: 202
RepCraigGoldman Block 1A, attempt 1: No posts yet...
RepCraigGoldman Block 1A, attempt 2: No posts yet...
RepCraigGoldman Block 1A, attempt 3: No posts yet...
RepCraigGoldman Block 1A, attempt 4: No posts yet...
RepCraigGoldman Block 1A, attempt 5: No posts yet...
RepCraigGoldman Block 1A, attempt 6: No posts yet...
RepCraigGoldman Block 1A, attempt 7: No posts yet...
RepCraigGoldman Block 1A, attempt 8: No posts yet...
RepCraigGoldman Block 1A, attempt 9: No posts yet...
RepCraigGoldman Block 1A, attempt 10: No posts yet...
No posts found for RepCraigGoldman Block 1A, skipping save.
Task started for RepCraigGoldman Block 1B: 202
RepCraigGoldman Block 1B, attempt 1: No posts yet...
RepCraigGoldman Block 1B, attempt 2: No posts yet...
RepCraigGoldman Block 1B, attempt 3: No posts yet...
RepCraigGoldman Block 1B, attempt 4: No posts yet...
RepCraigGoldman Block 1B, attempt 5: No posts yet...
RepCraigGoldman Block 1B, attempt 6: No posts yet...
RepCraigGoldman Block 1B, attempt 7: No posts yet...
RepCraigGoldman Block 1B, attempt 8: No posts yet...
RepCraigGoldman Block 1B, attempt 9: No posts yet...
RepCraigGoldman Block 1B, attempt 10: No posts yet...
No posts found for RepCraigGoldman Block 1B, skipping save.
Task started for RepCraigGoldman Block 2A: 202
RepCraigGoldman Block 2A, attempt 1: No posts yet...
RepCraigGoldman Block 2A, attempt 2: No posts yet...
RepCraigGoldman Block 2A, attempt 3: No posts yet...
RepCraigGoldman Block 2A, attempt 4: No posts yet...
RepCraigGoldman Block 2A, attempt 5: No posts yet...
RepCraigGoldman Block 2A, attempt 6: No posts yet...
RepCraigGoldman Block 2A, attempt 7: No posts yet...
RepCraigGoldman Block 2A, attempt 8: No posts yet...
RepCraigGoldman Block 2A, attempt 9: No posts yet...
RepCraigGoldman Block 2A, attempt 10: No posts yet...
No posts found for RepCraigGoldman Block 2A, skipping save.
Task started for RepCraigGoldman Block 2B: 202
RepCraigGoldman Block 2B, attempt 1: No posts yet...
RepCraigGoldman Block 2B, attempt 2: No posts yet...
RepCraigGoldman Block 2B, attempt 3: No posts yet...
RepCraigGoldman Block 2B, attempt 4: No posts yet...
RepCraigGoldman Block 2B, attempt 5: No posts yet...
RepCraigGoldman Block 2B, attempt 6: No posts yet...
RepCraigGoldman Block 2B, attempt 7: No posts yet...
RepCraigGoldman Block 2B, attempt 8: No posts yet...
RepCraigGoldman Block 2B, attempt 9: No posts yet...
RepCraigGoldman Block 2B, attempt 10: No posts yet...
No posts found for RepCraigGoldman Block 2B, skipping save.
Task started for RepCraigGoldman Block 3: 202
RepCraigGoldman Block 3, attempt 1: No posts yet...
RepCraigGoldman Block 3, attempt 2: No posts yet...
RepCraigGoldman Block 3, attempt 3: No posts yet...
RepCraigGoldman Block 3, attempt 4: No posts yet...
RepCraigGoldman Block 3, attempt 5: No posts yet...
RepCraigGoldman Block 3, attempt 6: No posts yet...
RepCraigGoldman Block 3, attempt 7: No posts yet...
RepCraigGoldman Block 3, attempt 8: No posts yet...
RepCraigGoldman Block 3, attempt 9: No posts yet...
RepCraigGoldman Block 3, attempt 10: No posts yet...
No posts found for RepCraigGoldman Block 3, skipping save.
Task started for RepCraigGoldman Block 4: 202
RepCraigGoldman Block 4, attempt 1: No posts yet...
RepCraigGoldman Block 4, attempt 2: No posts yet...
RepCraigGoldman Block 4, attempt 3: No posts yet...
RepCraigGoldman Block 4, attempt 4: No posts yet...
RepCraigGoldman Block 4, attempt 5: No posts yet...
RepCraigGoldman Block 4, attempt 6: No posts yet...
RepCraigGoldman Block 4, attempt 7: No posts yet...
RepCraigGoldman Block 4, attempt 8: No posts yet...
RepCraigGoldman Block 4, attempt 9: No posts yet...
RepCraigGoldman Block 4, attempt 10: No posts yet...
No posts found for RepCraigGoldman Block 4, skipping save.
Task started for RepCraigGoldman Block 5: 202
RepCraigGoldman Block 5, attempt 1: No posts yet...
RepCraigGoldman Block 5, attempt 2: No posts yet...
RepCraigGoldman Block 5, attempt 3: No posts yet...
RepCraigGoldman Block 5, attempt 4: No posts yet...
RepCraigGoldman Block 5, attempt 5: No posts yet...
RepCraigGoldman Block 5, attempt 6: No posts yet...
RepCraigGoldman Block 5, attempt 7: No posts yet...
RepCraigGoldman Block 5, attempt 8: No posts yet...
RepCraigGoldman Block 5, attempt 9: No posts yet...
RepCraigGoldman Block 5, attempt 10: No posts yet...
No posts found for RepCraigGoldman Block 5, skipping save.
Task started for RepCraigGoldman Block 6: 202
RepCraigGoldman Block 6, attempt 1: No posts yet...
RepCraigGoldman Block 6, attempt 2: No posts yet...
RepCraigGoldman Block 6, attempt 3: No posts yet...
RepCraigGoldman Block 6, attempt 4: No posts yet...
RepCraigGoldman Block 6, attempt 5: No posts yet...
RepCraigGoldman Block 6, attempt 6: No posts yet...
RepCraigGoldman Block 6, attempt 7: No posts yet...
RepCraigGoldman Block 6, attempt 8: No posts yet...
RepCraigGoldman Block 6: Retrieved 1 posts
Saved posts to RepCraigGoldman Block 6.json

=== Processing RepDLamborn ===
Task started for RepDLamborn Block 1A: 202
RepDLamborn Block 1A, attempt 1: No posts yet...
RepDLamborn Block 1A, attempt 2: No posts yet...
RepDLamborn Block 1A, attempt 3: No posts yet...
RepDLamborn Block 1A, attempt 4: No posts yet...
RepDLamborn Block 1A, attempt 5: No posts yet...
RepDLamborn Block 1A, attempt 6: No posts yet...
RepDLamborn Block 1A, attempt 7: No posts yet...
RepDLamborn Block 1A, attempt 8: No posts yet...
RepDLamborn Block 1A, attempt 9: No posts yet...
RepDLamborn Block 1A, attempt 10: No posts yet...
No posts found for RepDLamborn Block 1A, skipping save.
Task started for RepDLamborn Block 1B: 202
RepDLamborn Block 1B, attempt 1: No posts yet...
RepDLamborn Block 1B, attempt 2: No posts yet...
RepDLamborn Block 1B, attempt 3: No posts yet...
RepDLamborn Block 1B, attempt 4: No posts yet...
RepDLamborn Block 1B, attempt 5: No posts yet...
RepDLamborn Block 1B, attempt 6: No posts yet...
RepDLamborn Block 1B, attempt 7: No posts yet...
RepDLamborn Block 1B, attempt 8: No posts yet...
RepDLamborn Block 1B, attempt 9: No posts yet...
RepDLamborn Block 1B, attempt 10: No posts yet...
No posts found for RepDLamborn Block 1B, skipping save.
Task started for RepDLamborn Block 2A: 202
RepDLamborn Block 2A, attempt 1: No posts yet...
RepDLamborn Block 2A, attempt 2: No posts yet...
RepDLamborn Block 2A, attempt 3: No posts yet...
RepDLamborn Block 2A, attempt 4: No posts yet...
RepDLamborn Block 2A, attempt 5: No posts yet...
RepDLamborn Block 2A, attempt 6: No posts yet...
RepDLamborn Block 2A, attempt 7: No posts yet...
RepDLamborn Block 2A, attempt 8: No posts yet...
RepDLamborn Block 2A, attempt 9: No posts yet...
RepDLamborn Block 2A, attempt 10: No posts yet...
No posts found for RepDLamborn Block 2A, skipping save.
Task started for RepDLamborn Block 2B: 202
RepDLamborn Block 2B, attempt 1: No posts yet...
RepDLamborn Block 2B, attempt 2: No posts yet...
RepDLamborn Block 2B, attempt 3: No posts yet...
RepDLamborn Block 2B, attempt 4: No posts yet...
RepDLamborn Block 2B, attempt 5: No posts yet...
RepDLamborn Block 2B, attempt 6: No posts yet...
RepDLamborn Block 2B, attempt 7: No posts yet...
RepDLamborn Block 2B, attempt 8: No posts yet...
RepDLamborn Block 2B, attempt 9: No posts yet...
RepDLamborn Block 2B, attempt 10: No posts yet...
No posts found for RepDLamborn Block 2B, skipping save.
Task started for RepDLamborn Block 3: 202
RepDLamborn Block 3, attempt 1: No posts yet...
RepDLamborn Block 3, attempt 2: No posts yet...
RepDLamborn Block 3, attempt 3: No posts yet...
RepDLamborn Block 3, attempt 4: No posts yet...
RepDLamborn Block 3, attempt 5: No posts yet...
RepDLamborn Block 3, attempt 6: No posts yet...
RepDLamborn Block 3, attempt 7: No posts yet...
RepDLamborn Block 3, attempt 8: No posts yet...
RepDLamborn Block 3, attempt 9: No posts yet...
RepDLamborn Block 3, attempt 10: No posts yet...
No posts found for RepDLamborn Block 3, skipping save.
Task started for RepDLamborn Block 4: 202
RepDLamborn Block 4, attempt 1: No posts yet...
RepDLamborn Block 4, attempt 2: No posts yet...
RepDLamborn Block 4, attempt 3: No posts yet...
RepDLamborn Block 4, attempt 4: No posts yet...
RepDLamborn Block 4, attempt 5: No posts yet...

In [ ]:
AUTOMATING HEALTH-RELATED REPLIES FOR SECOND HALF

In [35]:
import os
import json
import requests
import time

# ------------------------------------
# CONFIG
# ------------------------------------
BLOCKS = ["1A", "1B", "2A", "2B", "3", "4", "5", "6"]  # correct block names

# ------------------------------------
# START AT AlLawsonJr AND GO DOWNWARD
# ------------------------------------
handles_series = new_df["X Handle"].dropna()

if "RepWalberg" in handles_series.values:
    start_index = handles_series[handles_series == "RepWalberg"].index[0]
    usernames_to_process = new_df.loc[start_index:, "X Handle"].dropna().unique()
else:
    print("RepWalberg not found. Starting from top.")
    usernames_to_process = handles_series.unique()

# ------------------------------------
# LOOP THROUGH EACH POLITICIAN
# ------------------------------------
for username in usernames_to_process:

    print(f"\nProcessing politician: {username}")

    # ------------------------------------
    # LOOP THROUGH BLOCKS
    # ------------------------------------
    for block_name in BLOCKS:

        input_filename = f"{username} Block {block_name}.json"
        output_filename = f"{username} Block {block_name} Replies.json"

        # ------------------------------------
        # SKIP IF FILE DOESN'T EXIST
        # ------------------------------------
        if not os.path.exists(input_filename):
            print(f"Skipping {input_filename} (file not found)")
            continue

        # ------------------------------------
        # OPEN BLOCK FILE
        # ------------------------------------
        with open(input_filename, "r", encoding="utf-8") as f:
            block_data = json.load(f)

        posts = block_data.get("data", {}).get("items", [])

        # Skip if no posts
        if not posts:
            print(f"Skipping {input_filename} (no posts found)")
            continue

        all_replies_output = []

        # ------------------------------------
        # FETCH REPLIES FOR EACH POST
        # ------------------------------------
        for post in posts:
            conversation_id = post.get("conversation_id")

            if not conversation_id:
                continue

            print(f"Fetching replies for {username} Block {block_name} - {conversation_id}")

            replies_url = (
                f"{API_BASE_URL}{API_VERSION}/twitter/profile/"
                f"{username}/feed/posts/{conversation_id}/replies"
            )

            params = {
                "order_by": "date_desc",
                "max_page_size": 50,
                "access_token": API_AUTHORIZATION_TOKEN
            }

            response = requests.get(replies_url, params=params)

            if response.status_code == 200:
                replies_json = response.json()
                replies_items = replies_json.get("data", {}).get("items", [])

                all_replies_output.append({
                    "conversation_id": conversation_id,
                    "replies": replies_items
                })
            else:
                print(f"Failed for {conversation_id}: {response.status_code}")

            time.sleep(1)  # rate limit safety

        # ------------------------------------
        # SAVE OUTPUT ONLY IF REPLIES EXIST
        # ------------------------------------
        if all_replies_output:

            final_output = {
                "politician": username,
                "block": block_name,
                "posts": all_replies_output
            }

            with open(output_filename, "w", encoding="utf-8") as f:
                json.dump(final_output, f, indent=4)

            print(f"Saved: {output_filename}")
        else:
            print(f"No replies found for {username} Block {block_name}")

print("\nAll politicians processed.")

Processing politician: RepWalberg
Fetching replies for RepWalberg Block 1A - 1801340623963779134
Fetching replies for RepWalberg Block 1A - 1807801464544494068
Fetching replies for RepWalberg Block 1A - 1811856379516276792
Fetching replies for RepWalberg Block 1A - 1897761856447451278
Fetching replies for RepWalberg Block 1A - 1907154293779484686
Fetching replies for RepWalberg Block 1A - 1907461308078764475
Fetching replies for RepWalberg Block 1A - 1920851620784373850
Fetching replies for RepWalberg Block 1A - 1926274305689551198
Fetching replies for RepWalberg Block 1A - 1937934872443564186
Fetching replies for RepWalberg Block 1A - 1937962901140062531
Fetching replies for RepWalberg Block 1A - 1938598465258324160
Fetching replies for RepWalberg Block 1A - 1944778177001189791
Fetching replies for RepWalberg Block 1A - 1950903233850880236
Fetching replies for RepWalberg Block 1A - 1961085362983620658
Fetching replies for RepWalberg Block 1A - 1973486977220813168
Fetching replies for RepWalberg Block 1A - 1975239901625843881
Fetching replies for RepWalberg Block 1A - 1991221367073898502
Fetching replies for RepWalberg Block 1A - 1991885901207675049
Fetching replies for RepWalberg Block 1A - 2000676852495736904
Fetching replies for RepWalberg Block 1A - 2001434806945460656
Saved: RepWalberg Block 1A Replies.json
Skipping RepWalberg Block 1B.json (file not found)
Skipping RepWalberg Block 2A.json (file not found)
Fetching replies for RepWalberg Block 2B - 1651251908479180801
Fetching replies for RepWalberg Block 2B - 1656710248978169856
Fetching replies for RepWalberg Block 2B - 1682036136569634816
Fetching replies for RepWalberg Block 2B - 1693616944933707925
Fetching replies for RepWalberg Block 2B - 1785012976136937960
Fetching replies for RepWalberg Block 2B - 1833920070566953315
Fetching replies for RepWalberg Block 2B - 1907154293779484686
Fetching replies for RepWalberg Block 2B - 1907461308078764475
Fetching replies for RepWalberg Block 2B - 1930373247758950487
Fetching replies for RepWalberg Block 2B - 1975239901625843881
Fetching replies for RepWalberg Block 2B - 2001434806945460656
Saved: RepWalberg Block 2B Replies.json
Skipping RepWalberg Block 3.json (file not found)
Skipping RepWalberg Block 4.json (file not found)
Skipping RepWalberg Block 5.json (file not found)
Fetching replies for RepWalberg Block 6 - 1527391370805137409
Fetching replies for RepWalberg Block 6 - 1537893221866479617
Fetching replies for RepWalberg Block 6 - 1583469432113811459
Fetching replies for RepWalberg Block 6 - 1923389109403373667
Fetching replies for RepWalberg Block 6 - 2000676852495736904
Saved: RepWalberg Block 6 Replies.json

Processing politician: RepWesleyHunt
Skipping RepWesleyHunt Block 1A.json (file not found)
Skipping RepWesleyHunt Block 1B.json (file not found)
Skipping RepWesleyHunt Block 2A.json (file not found)
Skipping RepWesleyHunt Block 2B.json (file not found)
Skipping RepWesleyHunt Block 3.json (file not found)
Skipping RepWesleyHunt Block 4.json (file not found)
Skipping RepWesleyHunt Block 5.json (file not found)
Skipping RepWesleyHunt Block 6.json (file not found)

Processing politician: RepWilson
Fetching replies for RepWilson Block 1A - 1932788771986325958
Fetching replies for RepWilson Block 1A - 1937483709986349090
Fetching replies for RepWilson Block 1A - 1940899907575161086
Fetching replies for RepWilson Block 1A - 1948880314824360300
Fetching replies for RepWilson Block 1A - 1954515376575861004
Fetching replies for RepWilson Block 1A - 1957559157953032433
Fetching replies for RepWilson Block 1A - 1957840025996964321
Fetching replies for RepWilson Block 1A - 1958676363059372520
Fetching replies for RepWilson Block 1A - 1960137904220782847
Fetching replies for RepWilson Block 1A - 1961091614715138230
Fetching replies for RepWilson Block 1A - 1961136574655078555
Fetching replies for RepWilson Block 1A - 1963333328242983091
Fetching replies for RepWilson Block 1A - 1969108607833714744
Fetching replies for RepWilson Block 1A - 1970254581843055021
Fetching replies for RepWilson Block 1A - 1976307458877403205
Fetching replies for RepWilson Block 1A - 1976376009542021197
Fetching replies for RepWilson Block 1A - 1976633481833627733
Fetching replies for RepWilson Block 1A - 1996353430630318456
Fetching replies for RepWilson Block 1A - 1999890782883570018
Fetching replies for RepWilson Block 1A - 2005637865691386283
Saved: RepWilson Block 1A Replies.json
Fetching replies for RepWilson Block 1B - 1490684047076569090
Fetching replies for RepWilson Block 1B - 1504534497697710082
Fetching replies for RepWilson Block 1B - 1509875054896631812
Fetching replies for RepWilson Block 1B - 1540020482912681985
Fetching replies for RepWilson Block 1B - 1598377367961243648
Fetching replies for RepWilson Block 1B - 1623088926608003073
Fetching replies for RepWilson Block 1B - 1628819083197022209
Fetching replies for RepWilson Block 1B - 1665792498688483331
Fetching replies for RepWilson Block 1B - 1708861943610487042
Fetching replies for RepWilson Block 1B - 1730659742517694657
Fetching replies for RepWilson Block 1B - 1761519400220319791
Fetching replies for RepWilson Block 1B - 1770569440368673267
Fetching replies for RepWilson Block 1B - 1771262863627145366
Fetching replies for RepWilson Block 1B - 1915910424945430770
Fetching replies for RepWilson Block 1B - 1918405636729012668
Fetching replies for RepWilson Block 1B - 1919444623354634265
Fetching replies for RepWilson Block 1B - 1995624150841569728
Saved: RepWilson Block 1B Replies.json
Fetching replies for RepWilson Block 2A - 1988062947466162519
Fetching replies for RepWilson Block 2A - 1988803568628117652
Fetching replies for RepWilson Block 2A - 1990439871635190224
Fetching replies for RepWilson Block 2A - 1990511703071863026
Fetching replies for RepWilson Block 2A - 1991244079003304062
Fetching replies for RepWilson Block 2A - 1992985264877117656
Fetching replies for RepWilson Block 2A - 1993369265395974588
Fetching replies for RepWilson Block 2A - 1993864223978664281
Fetching replies for RepWilson Block 2A - 1995509330268008946
Fetching replies for RepWilson Block 2A - 1995878618111562159
Fetching replies for RepWilson Block 2A - 1995998773957255375
Fetching replies for RepWilson Block 2A - 1996353430630318456
Fetching replies for RepWilson Block 2A - 1996598304495288391
Fetching replies for RepWilson Block 2A - 1998436494906687510
Fetching replies for RepWilson Block 2A - 2000693276932808859
Fetching replies for RepWilson Block 2A - 2001005949151273434
Fetching replies for RepWilson Block 2A - 2001313041556602917
Fetching replies for RepWilson Block 2A - 2001325610627637704
Fetching replies for RepWilson Block 2A - 2001793211665178850
Fetching replies for RepWilson Block 2A - 2005637865691386283
Saved: RepWilson Block 2A Replies.json
Fetching replies for RepWilson Block 2B - 1952836268402065783
Fetching replies for RepWilson Block 2B - 1954515376575861004
Fetching replies for RepWilson Block 2B - 1956355004945559698
Fetching replies for RepWilson Block 2B - 1956726105945317454
Fetching replies for RepWilson Block 2B - 1972752675143127171
Fetching replies for RepWilson Block 2B - 1976307458877403205
Fetching replies for RepWilson Block 2B - 1976376009542021197
Fetching replies for RepWilson Block 2B - 1976633481833627733
Fetching replies for RepWilson Block 2B - 1977508609564025275
Fetching replies for RepWilson Block 2B - 1977508609564025275
Fetching replies for RepWilson Block 2B - 1977508609564025275
Fetching replies for RepWilson Block 2B - 1978492753324449965
Fetching replies for RepWilson Block 2B - 1980697081187824128
Fetching replies for RepWilson Block 2B - 1988062947466162519
Fetching replies for RepWilson Block 2B - 1988803568628117652
Fetching replies for RepWilson Block 2B - 1996353430630318456
Fetching replies for RepWilson Block 2B - 1998436494906687510
Fetching replies for RepWilson Block 2B - 2001005949151273434
Fetching replies for RepWilson Block 2B - 2001313041556602917
Fetching replies for RepWilson Block 2B - 2001793211665178850
Saved: RepWilson Block 2B Replies.json
Skipping RepWilson Block 3.json (file not found)
Skipping RepWilson Block 4.json (file not found)
Skipping RepWilson Block 5.json (file not found)
Fetching replies for RepWilson Block 6 - 1486129333496389633
Fetching replies for RepWilson Block 6 - 1499076953072189450
Fetching replies for RepWilson Block 6 - 1559918917933490176
Fetching replies for RepWilson Block 6 - 1565039197483929602
Fetching replies for RepWilson Block 6 - 1629168347861463040
Fetching replies for RepWilson Block 6 - 1937948565055099127
Saved: RepWilson Block 6 Replies.json

Processing politician: RepYoungKim
Fetching replies for RepYoungKim Block 1A - 1924817967088308559
Fetching replies for RepYoungKim Block 1A - 1936191833148997942
Fetching replies for RepYoungKim Block 1A - 1936491306265747770
Fetching replies for RepYoungKim Block 1A - 1940164761502794074
Fetching replies for RepYoungKim Block 1A - 1940232709516746898
Fetching replies for RepYoungKim Block 1A - 1945551552413921625
Fetching replies for RepYoungKim Block 1A - 1947309389150396429
Fetching replies for RepYoungKim Block 1A - 1953867557330374915
Fetching replies for RepYoungKim Block 1A - 1953950022456013102
Fetching replies for RepYoungKim Block 1A - 1953981554168148214
Fetching replies for RepYoungKim Block 1A - 1955664142599323853
Fetching replies for RepYoungKim Block 1A - 1957548059367506179
Fetching replies for RepYoungKim Block 1A - 1957838468773736536
Fetching replies for RepYoungKim Block 1A - 1959332944532619382
Fetching replies for RepYoungKim Block 1A - 1965800651012833562
Fetching replies for RepYoungKim Block 1A - 1970156503459140057
Fetching replies for RepYoungKim Block 1A - 1970632814769918252
Fetching replies for RepYoungKim Block 1A - 1976682888390459750
Fetching replies for RepYoungKim Block 1A - 1985496636534243516
Fetching replies for RepYoungKim Block 1A - 2001733209529504171
Saved: RepYoungKim Block 1A Replies.json
Fetching replies for RepYoungKim Block 1B - 1572260546816008192
Fetching replies for RepYoungKim Block 1B - 1577101193712730112
Fetching replies for RepYoungKim Block 1B - 1580996867898449921
Fetching replies for RepYoungKim Block 1B - 1582805027155898370
Fetching replies for RepYoungKim Block 1B - 1599083540477378560
Fetching replies for RepYoungKim Block 1B - 1630241347708780549
Fetching replies for RepYoungKim Block 1B - 1630693074736238595
Fetching replies for RepYoungKim Block 1B - 1642308359713083392
Fetching replies for RepYoungKim Block 1B - 1654263384433360902
Fetching replies for RepYoungKim Block 1B - 1655973404371976203
Fetching replies for RepYoungKim Block 1B - 1712641805353713954
Fetching replies for RepYoungKim Block 1B - 1722660325416386574
Fetching replies for RepYoungKim Block 1B - 1782107030440038439
Fetching replies for RepYoungKim Block 1B - 1787559502050460009
Fetching replies for RepYoungKim Block 1B - 1795530731021795523
Fetching replies for RepYoungKim Block 1B - 1795915516655043003
Fetching replies for RepYoungKim Block 1B - 1844150854837993897
Fetching replies for RepYoungKim Block 1B - 1924233747164971511
Fetching replies for RepYoungKim Block 1B - 1929636207404691661
Fetching replies for RepYoungKim Block 1B - 2001805930707456247
Saved: RepYoungKim Block 1B Replies.json
Fetching replies for RepYoungKim Block 2A - 1908196615711842611
Fetching replies for RepYoungKim Block 2A - 1914849201269207121
Fetching replies for RepYoungKim Block 2A - 1917674064866599177
Fetching replies for RepYoungKim Block 2A - 1920923728000807209
Fetching replies for RepYoungKim Block 2A - 1923157446123471124
Fetching replies for RepYoungKim Block 2A - 1928155181880909885
Fetching replies for RepYoungKim Block 2A - 1930087610585886732
Fetching replies for RepYoungKim Block 2A - 1930805591489888467
Fetching replies for RepYoungKim Block 2A - 1936491306265747770
Fetching replies for RepYoungKim Block 2A - 1940842043401797696
Fetching replies for RepYoungKim Block 2A - 1943108408896602121
Fetching replies for RepYoungKim Block 2A - 1947309389150396429
Fetching replies for RepYoungKim Block 2A - 1952761825369485628
Fetching replies for RepYoungKim Block 2A - 1953535363873747033
Fetching replies for RepYoungKim Block 2A - 1954280658051768711
Fetching replies for RepYoungKim Block 2A - 1955664142599323853
Fetching replies for RepYoungKim Block 2A - 1965463248935018733
Fetching replies for RepYoungKim Block 2A - 1986173850992640088
Fetching replies for RepYoungKim Block 2A - 1986173850992640088
Fetching replies for RepYoungKim Block 2A - 1991579130299854973
Saved: RepYoungKim Block 2A Replies.json
Fetching replies for RepYoungKim Block 2B - 1810833817357173187
Fetching replies for RepYoungKim Block 2B - 1811439054786871675
Fetching replies for RepYoungKim Block 2B - 1814359557029970215
Fetching replies for RepYoungKim Block 2B - 1820565447118598465
Fetching replies for RepYoungKim Block 2B - 1825231184793575764
Fetching replies for RepYoungKim Block 2B - 1831761716264550421
Fetching replies for RepYoungKim Block 2B - 1836416135602016342
Fetching replies for RepYoungKim Block 2B - 1841901027932467543
Fetching replies for RepYoungKim Block 2B - 1842312488102039583
Fetching replies for RepYoungKim Block 2B - 1858608617919799413
Fetching replies for RepYoungKim Block 2B - 1860361516903465406
Fetching replies for RepYoungKim Block 2B - 1879321348918702491
Fetching replies for RepYoungKim Block 2B - 1889686072944111646
Fetching replies for RepYoungKim Block 2B - 1892673078179529117
Fetching replies for RepYoungKim Block 2B - 1919848391653110020
Fetching replies for RepYoungKim Block 2B - 1920923728000807209
Fetching replies for RepYoungKim Block 2B - 1959332944532619382
Fetching replies for RepYoungKim Block 2B - 1965146875931361737
Fetching replies for RepYoungKim Block 2B - 1976724415489638676
Fetching replies for RepYoungKim Block 2B - 2001733209529504171
Saved: RepYoungKim Block 2B Replies.json
Skipping RepYoungKim Block 3.json (file not found)
Skipping RepYoungKim Block 4.json (file not found)
Skipping RepYoungKim Block 5.json (file not found)
Fetching replies for RepYoungKim Block 6 - 1769527136325689707
Fetching replies for RepYoungKim Block 6 - 1783994717329293318
Fetching replies for RepYoungKim Block 6 - 1807807355209371950
Fetching replies for RepYoungKim Block 6 - 1811939854587981986
Fetching replies for RepYoungKim Block 6 - 1821260020664959024
Fetching replies for RepYoungKim Block 6 - 1821320421997781178
Fetching replies for RepYoungKim Block 6 - 1825903115536871513
Fetching replies for RepYoungKim Block 6 - 1837162123257909328
Fetching replies for RepYoungKim Block 6 - 1839447359446757650
Fetching replies for RepYoungKim Block 6 - 1844113102847213994
Fetching replies for RepYoungKim Block 6 - 1860095926049616335
Fetching replies for RepYoungKim Block 6 - 1867992957216829756
Fetching replies for RepYoungKim Block 6 - 1897423653408563518
Fetching replies for RepYoungKim Block 6 - 1912861104918643151
Fetching replies for RepYoungKim Block 6 - 1915861159216877681
Fetching replies for RepYoungKim Block 6 - 1936191833148997942
Fetching replies for RepYoungKim Block 6 - 1940164761502794074
Fetching replies for RepYoungKim Block 6 - 1940232709516746898
Fetching replies for RepYoungKim Block 6 - 1953950022456013102
Fetching replies for RepYoungKim Block 6 - 1970643090429059297
Saved: RepYoungKim Block 6 Replies.json

Processing politician: RepZoeLofgren
Skipping RepZoeLofgren Block 1A.json (file not found)
Fetching replies for RepZoeLofgren Block 1B - 1503070222927998977
Fetching replies for RepZoeLofgren Block 1B - 1527682117752307713
Fetching replies for RepZoeLofgren Block 1B - 1753468673790992818
Fetching replies for RepZoeLofgren Block 1B - 1767644722204389411
Fetching replies for RepZoeLofgren Block 1B - 1770857655780757719
Fetching replies for RepZoeLofgren Block 1B - 1909993228725584369
Fetching replies for RepZoeLofgren Block 1B - 1915059872606888266
Fetching replies for RepZoeLofgren Block 1B - 1943667694718378489
Fetching replies for RepZoeLofgren Block 1B - 1966509206866952457
Saved: RepZoeLofgren Block 1B Replies.json
Fetching replies for RepZoeLofgren Block 2A - 1986486384752775632
Fetching replies for RepZoeLofgren Block 2A - 1986919010085007644
Fetching replies for RepZoeLofgren Block 2A - 1987692918430147069
Fetching replies for RepZoeLofgren Block 2A - 1987998565554417794
Fetching replies for RepZoeLofgren Block 2A - 1988679171548254456
Fetching replies for RepZoeLofgren Block 2A - 1996254965296222412
Fetching replies for RepZoeLofgren Block 2A - 1996393187909529926
Fetching replies for RepZoeLofgren Block 2A - 1998428502438162758
Fetching replies for RepZoeLofgren Block 2A - 1998443821760237572
Fetching replies for RepZoeLofgren Block 2A - 1998522335905935542
Fetching replies for RepZoeLofgren Block 2A - 1998764668991500475
Fetching replies for RepZoeLofgren Block 2A - 1999126448729186532
Fetching replies for RepZoeLofgren Block 2A - 1999483577768255847
Fetching replies for RepZoeLofgren Block 2A - 2000650149295456737
Fetching replies for RepZoeLofgren Block 2A - 2000996729743868289
Fetching replies for RepZoeLofgren Block 2A - 2001297786013143550
Fetching replies for RepZoeLofgren Block 2A - 2001680149696196672
Fetching replies for RepZoeLofgren Block 2A - 2003153479351881972
Fetching replies for RepZoeLofgren Block 2A - 2003509586872181213
Fetching replies for RepZoeLofgren Block 2A - 2005675472546586674
Saved: RepZoeLofgren Block 2A Replies.json
Fetching replies for RepZoeLofgren Block 2B - 1547275054597251072
Fetching replies for RepZoeLofgren Block 2B - 1565386234335268865
Fetching replies for RepZoeLofgren Block 2B - 1753468673790992818
Fetching replies for RepZoeLofgren Block 2B - 1846950224066994460
Fetching replies for RepZoeLofgren Block 2B - 1848773674519663062
Fetching replies for RepZoeLofgren Block 2B - 1856771972145058024
Fetching replies for RepZoeLofgren Block 2B - 1880001410697425407
Fetching replies for RepZoeLofgren Block 2B - 1902188970597126443
Fetching replies for RepZoeLofgren Block 2B - 1936167332256080155
Fetching replies for RepZoeLofgren Block 2B - 1943667694718378489
Fetching replies for RepZoeLofgren Block 2B - 1973057547138473998
Fetching replies for RepZoeLofgren Block 2B - 1975599301913899132
Fetching replies for RepZoeLofgren Block 2B - 1976018128321867924
Fetching replies for RepZoeLofgren Block 2B - 1981010569974124918
Fetching replies for RepZoeLofgren Block 2B - 1981790570956898728
Fetching replies for RepZoeLofgren Block 2B - 1983588197662888246
Fetching replies for RepZoeLofgren Block 2B - 1986486384752775632
Fetching replies for RepZoeLofgren Block 2B - 1991910845140586623
Fetching replies for RepZoeLofgren Block 2B - 2003153479351881972
Fetching replies for RepZoeLofgren Block 2B - 2003509586872181213
Saved: RepZoeLofgren Block 2B Replies.json
Skipping RepZoeLofgren Block 3.json (file not found)
Skipping RepZoeLofgren Block 4.json (file not found)
Skipping RepZoeLofgren Block 5.json (file not found)
Fetching replies for RepZoeLofgren Block 6 - 1504822053337186305
Fetching replies for RepZoeLofgren Block 6 - 1524117595938766848
Fetching replies for RepZoeLofgren Block 6 - 1568324001747058688
Fetching replies for RepZoeLofgren Block 6 - 1577797600039899137
Fetching replies for RepZoeLofgren Block 6 - 1810752891746918797
Fetching replies for RepZoeLofgren Block 6 - 1825619941975847080
Fetching replies for RepZoeLofgren Block 6 - 1836764286363873432
Fetching replies for RepZoeLofgren Block 6 - 1899582853266190413
Saved: RepZoeLofgren Block 6 Replies.json

Processing politician: Rep_Grijalva
Fetching replies for Rep_Grijalva Block 1A - 2001357062803198185
Saved: Rep_Grijalva Block 1A Replies.json
Skipping Rep_Grijalva Block 1B.json (file not found)
Fetching replies for Rep_Grijalva Block 2A - 1992733123432644717
Fetching replies for Rep_Grijalva Block 2A - 2001096548944675197
Saved: Rep_Grijalva Block 2A Replies.json

In [ ]:
NON-HEALTH TWEETS FOR SECOND HALF:

In [37]:
import pandas as pd
import requests
import time
import json

API_BASE_URL = "https://api.data365.co"
API_VERSION = "/v1.1"
API_AUTHORIZATION_TOKEN = "ZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKSVV6STFOaUo5LmV5SnpkV0lpT2lKSWFXSmhRV3hwSWl3aWFXRjBJam94TnpZNU5UQTNOamcyTGpBd05UQXhPSDAuNmpTLTZtbVBGV0F1ZS1McHhXaUIwbUtDUWFDemU4VkRNZVhOSkZ2ckJRTQ=="

# ------------------------
# Function to fetch top posts (no keywords)
# ------------------------
def fetch_top_posts(username, max_attempts=10, sleep_time=2):

    update_url = f"{API_BASE_URL}{API_VERSION}/twitter/search/post/update"
    posts_url = f"{API_BASE_URL}{API_VERSION}/twitter/search/post/posts"

    params = {
        "from_profile": username,
        "from_date": "2022-01-01",
        "to_date": "2025-12-31",
        "lang": "en",
        "max_posts": 20,
        "search_type": "top",   # change to "top" if API supports it
        "max_replies": 3,
        "load_replies": "true",
        "access_token": API_AUTHORIZATION_TOKEN
    }

    # Start search task
    post_response = requests.post(update_url, params=params)
    print(f"Task started for {username}: {post_response.status_code}")

    attempt = 0
    data = {}

    while attempt < max_attempts:
        posts_response = requests.get(posts_url, params=params)

        if posts_response.status_code == 200:
            data = posts_response.json()
            items = data.get("data", {}).get("items", [])

            if items:
                print(f"{username}: Retrieved {len(items)} posts")
                break
            else:
                print(f"{username}, attempt {attempt+1}: No posts yet...")
        else:
            print(f"Failed for {username} (attempt {attempt+1}): {posts_response.status_code}")

        attempt += 1
        time.sleep(sleep_time)

    items = data.get("data", {}).get("items", [])

    if items:
        filename = f"{username}.json"
        with open(filename, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4)
        print(f"Saved posts to {filename}")
    else:
        print(f"No posts found for {username}, skipping save.")

    return items


# ------------------------
# MAIN EXECUTION
# ------------------------

start_username = "AlLawsonJr"

# Find starting index
start_index = new_df.index[new_df["X Handle"] == start_username][0]

# Loop downward from RepWexton
for username in new_df["X Handle"].iloc[start_index:]:
    print(f"\n=== Processing {username} ===")
    fetch_top_posts(username)

print("\nAll politicians processed.")

=== Processing AlLawsonJr ===
Task started for AlLawsonJr: 202
AlLawsonJr: Retrieved 12 posts
Saved posts to AlLawsonJr.json

=== Processing AlbioSiresNJ ===
Task started for AlbioSiresNJ: 202
AlbioSiresNJ, attempt 1: No posts yet...
AlbioSiresNJ, attempt 2: No posts yet...
AlbioSiresNJ, attempt 3: No posts yet...
AlbioSiresNJ, attempt 4: No posts yet...
AlbioSiresNJ, attempt 5: No posts yet...
AlbioSiresNJ, attempt 6: No posts yet...
AlbioSiresNJ, attempt 7: No posts yet...
AlbioSiresNJ, attempt 8: No posts yet...
AlbioSiresNJ, attempt 9: No posts yet...
AlbioSiresNJ, attempt 10: No posts yet...
No posts found for AlbioSiresNJ, skipping save.

=== Processing Andy_Levin ===
Task started for Andy_Levin: 202
Andy_Levin: Retrieved 25 posts
Saved posts to Andy_Levin.json

=== Processing Axne4Congress ===
Task started for Axne4Congress: 202
Axne4Congress: Retrieved 25 posts
Saved posts to Axne4Congress.json

=== Processing BHigginsBflo ===
Task started for BHigginsBflo: 202
BHigginsBflo: Retrieved 25 posts
Saved posts to BHigginsBflo.json

=== Processing BennieGThompson ===
Task started for BennieGThompson: 202
BennieGThompson: Retrieved 25 posts
Saved posts to BennieGThompson.json

=== Processing BettyMcCollum04 ===
Task started for BettyMcCollum04: 202
BettyMcCollum04: Retrieved 25 posts
Saved posts to BettyMcCollum04.json

=== Processing BillPoseyFL ===
Task started for BillPoseyFL: 202
BillPoseyFL: Retrieved 11 posts
Saved posts to BillPoseyFL.json

=== Processing BobbyLRush ===
Task started for BobbyLRush: 202
BobbyLRush: Retrieved 25 posts
Saved posts to BobbyLRush.json

=== Processing BobbyScott ===
Task started for BobbyScott: 202
BobbyScott: Retrieved 25 posts
Saved posts to BobbyScott.json

=== Processing BradSherman ===
Task started for BradSherman: 202
BradSherman: Retrieved 25 posts
Saved posts to BradSherman.json

=== Processing Call_Me_Dutch ===
Task started for Call_Me_Dutch: 202
Call_Me_Dutch: Retrieved 25 posts
Saved posts to Call_Me_Dutch.json

=== Processing CarlForAlabama ===
Task started for CarlForAlabama: 202
CarlForAlabama: Retrieved 2 posts
Saved posts to CarlForAlabama.json

=== Processing ColinAllredTX ===
Task started for ColinAllredTX: 202
ColinAllredTX: Retrieved 25 posts
Saved posts to ColinAllredTX.json

=== Processing CongBoyle ===
Task started for CongBoyle: 202
CongBoyle: Retrieved 25 posts
Saved posts to CongBoyle.json

=== Processing CongMikeSimpson ===
Task started for CongMikeSimpson: 202
CongMikeSimpson: Retrieved 25 posts
Saved posts to CongMikeSimpson.json

=== Processing CongressmanKean ===
Task started for CongressmanKean: 202
CongressmanKean: Retrieved 25 posts
Saved posts to CongressmanKean.json

=== Processing CongressmanRaja ===
Task started for CongressmanRaja: 202
CongressmanRaja: Retrieved 25 posts
Saved posts to CongressmanRaja.json

=== Processing CongresswomanSC ===
Task started for CongresswomanSC: 202
CongresswomanSC: Retrieved 25 posts
Saved posts to CongresswomanSC.json

=== Processing ConorLambPA ===
Task started for ConorLambPA: 202
ConorLambPA: Retrieved 25 posts
Saved posts to ConorLambPA.json

=== Processing DPrice4Congress ===
Task started for DPrice4Congress: 202
DPrice4Congress, attempt 1: No posts yet...
DPrice4Congress, attempt 2: No posts yet...
DPrice4Congress, attempt 3: No posts yet...
DPrice4Congress, attempt 4: No posts yet...
DPrice4Congress, attempt 5: No posts yet...
DPrice4Congress, attempt 6: No posts yet...
DPrice4Congress, attempt 7: No posts yet...
DPrice4Congress, attempt 8: No posts yet...
DPrice4Congress, attempt 9: No posts yet...
DPrice4Congress, attempt 10: No posts yet...
No posts found for DPrice4Congress, skipping save.

=== Processing DesJarlaisTN04 ===
Task started for DesJarlaisTN04: 202
DesJarlaisTN04: Retrieved 25 posts
Saved posts to DesJarlaisTN04.json

=== Processing DorisMatsui ===
Task started for DorisMatsui: 202
DorisMatsui: Retrieved 25 posts
Saved posts to DorisMatsui.json

=== Processing DrNealDunnFL2 ===
Task started for DrNealDunnFL2: 202
DrNealDunnFL2: Retrieved 25 posts
Saved posts to DrNealDunnFL2.json

=== Processing ElaineLuriaVA ===
Task started for ElaineLuriaVA: 202
ElaineLuriaVA: Retrieved 24 posts
Saved posts to ElaineLuriaVA.json

=== Processing EleanorNorton ===
Task started for EleanorNorton: 202
EleanorNorton: Retrieved 25 posts
Saved posts to EleanorNorton.json

=== Processing FrankPallone ===
Task started for FrankPallone: 202
FrankPallone: Retrieved 25 posts
Saved posts to FrankPallone.json

=== Processing GKButterfield ===
Task started for GKButterfield: 202
GKButterfield: Retrieved 2 posts
Saved posts to GKButterfield.json

=== Processing GOPMajorityWhip ===
Task started for GOPMajorityWhip: 202
GOPMajorityWhip: Retrieved 25 posts
Saved posts to GOPMajorityWhip.json

=== Processing GerryConnolly ===
Task started for GerryConnolly: 202
GerryConnolly: Retrieved 25 posts
Saved posts to GerryConnolly.json

=== Processing Hill4MNHouse ===
Task started for Hill4MNHouse: 202
Hill4MNHouse: Retrieved 3 posts
Saved posts to Hill4MNHouse.json

=== Processing Ilhan ===
Task started for Ilhan: 202
Ilhan: Retrieved 25 posts
Saved posts to Ilhan.json

=== Processing JacksonLeeTX18 ===
Task started for JacksonLeeTX18: 202
JacksonLeeTX18: Retrieved 25 posts
Saved posts to JacksonLeeTX18.json

=== Processing JakeLaTurner ===
Task started for JakeLaTurner: 202
JakeLaTurner: Retrieved 4 posts
Saved posts to JakeLaTurner.json

=== Processing JayObernolte ===
Task started for JayObernolte: 202
JayObernolte: Retrieved 25 posts
Saved posts to JayObernolte.json

=== Processing JimLangevin ===
Task started for JimLangevin: 202
JimLangevin: Retrieved 25 posts
Saved posts to JimLangevin.json

=== Processing Jim_Jordan ===
Task started for Jim_Jordan: 202
Jim_Jordan: Retrieved 25 posts
Saved posts to Jim_Jordan.json

=== Processing JoaquinCastrotx ===
Task started for JoaquinCastrotx: 202
JoaquinCastrotx: Retrieved 25 posts
Saved posts to JoaquinCastrotx.json

=== Processing JodyHiceFRCA ===
Task started for JodyHiceFRCA: 202
JodyHiceFRCA: Retrieved 7 posts
Saved posts to JodyHiceFRCA.json

=== Processing JohnMannionNY22 ===
Task started for JohnMannionNY22: 202
JohnMannionNY22: Retrieved 25 posts
Saved posts to JohnMannionNY22.json

=== Processing JohnYarmuth ===
Task started for JohnYarmuth: 202
JohnYarmuth: Retrieved 25 posts
Saved posts to JohnYarmuth.json

=== Processing JudgeCarter ===
Task started for JudgeCarter: 202
JudgeCarter: Retrieved 25 posts
Saved posts to JudgeCarter.json

=== Processing KellyMorrisonMN ===
Task started for KellyMorrisonMN: 202
KellyMorrisonMN: Retrieved 25 posts
Saved posts to KellyMorrisonMN.json

=== Processing KenCalvert ===
Task started for KenCalvert: 202
KenCalvert: Retrieved 25 posts
Saved posts to KenCalvert.json

=== Processing Kilili_Sablan ===
Task started for Kilili_Sablan: 202
Kilili_Sablan: Retrieved 25 posts
Saved posts to Kilili_Sablan.json

=== Processing MarioDB ===
Task started for MarioDB: 202
MarioDB: Retrieved 25 posts
Saved posts to MarioDB.json

=== Processing MattForMontana ===
Task started for MattForMontana: 202
MattForMontana: Retrieved 3 posts
Saved posts to MattForMontana.json

=== Processing MichelleSteelCA ===
Task started for MichelleSteelCA: 202
MichelleSteelCA: Retrieved 25 posts
Saved posts to MichelleSteelCA.json

=== Processing MikeGarciaCA27 ===
Task started for MikeGarciaCA27: 202
MikeGarciaCA27: Retrieved 25 posts
Saved posts to MikeGarciaCA27.json

=== Processing NydiaVelazquez ===
Task started for NydiaVelazquez: 202
NydiaVelazquez: Retrieved 25 posts
Saved posts to NydiaVelazquez.json

=== Processing OAGMaryland ===
Task started for OAGMaryland: 202
OAGMaryland: Retrieved 25 posts
Saved posts to OAGMaryland.json

=== Processing PatronisFL ===
Task started for PatronisFL: 202
PatronisFL: Retrieved 10 posts
Saved posts to PatronisFL.json

=== Processing PeterMeijer ===
Task started for PeterMeijer: 202
PeterMeijer: Retrieved 25 posts
Saved posts to PeterMeijer.json

=== Processing RepAOC ===
Task started for RepAOC: 202
RepAOC: Retrieved 25 posts
Saved posts to RepAOC.json

=== Processing RepAdamGrayCA ===
Task started for RepAdamGrayCA: 202
RepAdamGrayCA: Retrieved 25 posts
Saved posts to RepAdamGrayCA.json

=== Processing RepAdamSmith ===
Task started for RepAdamSmith: 202
RepAdamSmith: Retrieved 25 posts
Saved posts to RepAdamSmith.json

=== Processing RepAdrianSmith ===
Task started for RepAdrianSmith: 202
RepAdrianSmith: Retrieved 25 posts
Saved posts to RepAdrianSmith.json

=== Processing RepAlexMooney ===
Task started for RepAlexMooney: 202
RepAlexMooney: Retrieved 25 posts
Saved posts to RepAlexMooney.json

=== Processing RepAndyBiggsAZ ===
Task started for RepAndyBiggsAZ: 202
RepAndyBiggsAZ: Retrieved 25 posts
Saved posts to RepAndyBiggsAZ.json

=== Processing RepAndyHarrisMD ===
Task started for RepAndyHarrisMD: 202
RepAndyHarrisMD: Retrieved 25 posts
Saved posts to RepAndyHarrisMD.json

=== Processing RepAnnWagner ===
Task started for RepAnnWagner: 202
RepAnnWagner: Retrieved 25 posts
Saved posts to RepAnnWagner.json

=== Processing RepAnnieKuster ===
Task started for RepAnnieKuster: 202
RepAnnieKuster: Retrieved 25 posts
Saved posts to RepAnnieKuster.json

=== Processing RepArrington ===
Task started for RepArrington: 202
RepArrington: Retrieved 25 posts
Saved posts to RepArrington.json

=== Processing RepAshleyHinson ===
Task started for RepAshleyHinson: 202
RepAshleyHinson: Retrieved 25 posts
Saved posts to RepAshleyHinson.json

=== Processing RepBalderson ===
Task started for RepBalderson: 202
RepBalderson: Retrieved 25 posts
Saved posts to RepBalderson.json

=== Processing RepBarbaraLee ===
Task started for RepBarbaraLee: 202
RepBarbaraLee: Retrieved 25 posts
Saved posts to RepBarbaraLee.json

=== Processing RepBarragan ===
Task started for RepBarragan: 202
RepBarragan: Retrieved 25 posts
Saved posts to RepBarragan.json

=== Processing RepBarryMoore ===
Task started for RepBarryMoore: 202
RepBarryMoore: Retrieved 25 posts
Saved posts to RepBarryMoore.json

=== Processing RepBeatty ===
Task started for RepBeatty: 202
RepBeatty: Retrieved 25 posts
Saved posts to RepBeatty.json

=== Processing RepBeccaB ===
Task started for RepBeccaB: 202
RepBeccaB: Retrieved 25 posts
Saved posts to RepBeccaB.json

=== Processing RepBenCline ===
Task started for RepBenCline: 202
RepBenCline: Retrieved 25 posts
Saved posts to RepBenCline.json

=== Processing RepBentz ===
Task started for RepBentz: 202
RepBentz: Retrieved 25 posts
Saved posts to RepBentz.json

=== Processing RepBera ===
Task started for RepBera: 202
RepBera: Retrieved 25 posts
Saved posts to RepBera.json

=== Processing RepBice ===
Task started for RepBice: 202
RepBice: Retrieved 25 posts
Saved posts to RepBice.json

=== Processing RepBillFoster ===
Task started for RepBillFoster: 202
RepBillFoster: Retrieved 25 posts
Saved posts to RepBillFoster.json

=== Processing RepBlakeMoore ===
Task started for RepBlakeMoore: 202
RepBlakeMoore: Retrieved 25 posts
Saved posts to RepBlakeMoore.json

=== Processing RepBobGood ===
Task started for RepBobGood: 202
RepBobGood: Retrieved 25 posts
Saved posts to RepBobGood.json

=== Processing RepBoebert ===
Task started for RepBoebert: 202
RepBoebert: Retrieved 25 posts
Saved posts to RepBoebert.json

=== Processing RepBonnie ===
Task started for RepBonnie: 202
RepBonnie: Retrieved 25 posts
Saved posts to RepBonnie.json

=== Processing RepBost ===
Task started for RepBost: 202
RepBost: Retrieved 25 posts
Saved posts to RepBost.json

=== Processing RepBrandonGill ===
Task started for RepBrandonGill: 202
RepBrandonGill: Retrieved 25 posts
Saved posts to RepBrandonGill.json

=== Processing RepBrecheen ===
Task started for RepBrecheen: 202
RepBrecheen: Retrieved 25 posts
Saved posts to RepBrecheen.json

=== Processing RepBresnahan ===
Task started for RepBresnahan: 202
RepBresnahan: Retrieved 25 posts
Saved posts to RepBresnahan.json

=== Processing RepBrianFitz ===
Task started for RepBrianFitz: 202
RepBrianFitz: Retrieved 25 posts
Saved posts to RepBrianFitz.json

=== Processing RepBrianJack ===
Task started for RepBrianJack: 202
RepBrianJack: Retrieved 2 posts
Saved posts to RepBrianJack.json

=== Processing RepBrianMast ===
Task started for RepBrianMast: 202
RepBrianMast: Retrieved 25 posts
Saved posts to RepBrianMast.json

=== Processing RepBryanSteil ===
Task started for RepBryanSteil: 202
RepBryanSteil: Retrieved 25 posts
Saved posts to RepBryanSteil.json

=== Processing RepBynum ===
Task started for RepBynum: 202
RepBynum: Retrieved 25 posts
Saved posts to RepBynum.json

=== Processing RepCarbajal ===
Task started for RepCarbajal: 202
RepCarbajal: Retrieved 25 posts
Saved posts to RepCarbajal.json

=== Processing RepCarolMiller ===
Task started for RepCarolMiller: 202
RepCarolMiller: Retrieved 25 posts
Saved posts to RepCarolMiller.json

=== Processing RepCartwright ===
Task started for RepCartwright: 202
RepCartwright: Retrieved 18 posts
Saved posts to RepCartwright.json

=== Processing RepCasar ===
Task started for RepCasar: 202
RepCasar: Retrieved 25 posts
Saved posts to RepCasar.json

=== Processing RepCheri ===
Task started for RepCheri: 202
RepCheri: Retrieved 25 posts
Saved posts to RepCheri.json

=== Processing RepClayHiggins ===
Task started for RepClayHiggins: 202
RepClayHiggins: Retrieved 25 posts
Saved posts to RepClayHiggins.json

=== Processing RepCraigGoldman ===
Task started for RepCraigGoldman: 202
RepCraigGoldman: Retrieved 12 posts
Saved posts to RepCraigGoldman.json

=== Processing RepDLamborn ===
Task started for RepDLamborn: 202
RepDLamborn: Retrieved 16 posts
Saved posts to RepDLamborn.json

=== Processing RepDWStweets ===
Task started for RepDWStweets: 202
RepDWStweets: Retrieved 25 posts
Saved posts to RepDWStweets.json

=== Processing RepDanKildee ===
Task started for RepDanKildee: 202
RepDanKildee: Retrieved 25 posts
Saved posts to RepDanKildee.json

=== Processing RepDannyDavis ===
Task started for RepDannyDavis: 202
RepDannyDavis: Retrieved 25 posts
Saved posts to RepDannyDavis.json

=== Processing RepDarrenSoto ===
Task started for RepDarrenSoto: 202
RepDarrenSoto: Retrieved 25 posts
Saved posts to RepDarrenSoto.json

=== Processing RepDaveTaylor ===
Task started for RepDaveTaylor: 202
RepDaveTaylor: Retrieved 25 posts
Saved posts to RepDaveTaylor.json

=== Processing RepDavid ===
Task started for RepDavid: 202
RepDavid: Retrieved 25 posts
Saved posts to RepDavid.json

=== Processing RepDavidKustoff ===
Task started for RepDavidKustoff: 202
RepDavidKustoff: Retrieved 25 posts
Saved posts to RepDavidKustoff.json

=== Processing RepDavidRouzer ===
Task started for RepDavidRouzer: 202
RepDavidRouzer: Retrieved 25 posts
Saved posts to RepDavidRouzer.json

=== Processing RepDavidValadao ===
Task started for RepDavidValadao: 202
RepDavidValadao: Retrieved 25 posts
Saved posts to RepDavidValadao.json

=== Processing RepDavids ===
Task started for RepDavids: 202
RepDavids: Retrieved 25 posts
Saved posts to RepDavids.json

=== Processing RepDeSaulnier ===
Task started for RepDeSaulnier: 202
RepDeSaulnier: Retrieved 25 posts
Saved posts to RepDeSaulnier.json

=== Processing RepDebDingell ===
Task started for RepDebDingell: 202
RepDebDingell: Retrieved 25 posts
Saved posts to RepDebDingell.json

=== Processing RepDeborahRoss ===
Task started for RepDeborahRoss: 202
RepDeborahRoss: Retrieved 25 posts
Saved posts to RepDeborahRoss.json

=== Processing RepDeluzio ===
Task started for RepDeluzio: 202
RepDeluzio: Retrieved 25 posts
Saved posts to RepDeluzio.json

=== Processing RepDerekSchmidt ===
Task started for RepDerekSchmidt: 202
RepDerekSchmidt: Retrieved 6 posts
Saved posts to RepDerekSchmidt.json

=== Processing RepDexterOR ===
Task started for RepDexterOR: 202
RepDexterOR: Retrieved 25 posts
Saved posts to RepDexterOR.json

=== Processing RepDianaDeGette ===
Task started for RepDianaDeGette: 202
RepDianaDeGette: Retrieved 25 posts
Saved posts to RepDianaDeGette.json

=== Processing RepDonBeyer ===
Task started for RepDonBeyer: 202
RepDonBeyer: Retrieved 25 posts
Saved posts to RepDonBeyer.json

=== Processing RepDonaldPayne ===
Task started for RepDonaldPayne: 202
RepDonaldPayne: Retrieved 25 posts
Saved posts to RepDonaldPayne.json

=== Processing RepDrewFerguson ===
Task started for RepDrewFerguson: 202
RepDrewFerguson: Retrieved 25 posts
Saved posts to RepDrewFerguson.json

=== Processing RepDustyJohnson ===
Task started for RepDustyJohnson: 202
RepDustyJohnson: Retrieved 25 posts
Saved posts to RepDustyJohnson.json

=== Processing RepDwightEvans ===
Task started for RepDwightEvans: 202
RepDwightEvans: Retrieved 25 posts
Saved posts to RepDwightEvans.json

=== Processing RepEBJ ===
Task started for RepEBJ: 202
RepEBJ: Retrieved 16 posts
Saved posts to RepEBJ.json

=== Processing RepEllzey ===
Task started for RepEllzey: 202
RepEllzey: Retrieved 14 posts
Saved posts to RepEllzey.json

=== Processing RepEricBurlison ===
Task started for RepEricBurlison: 202
RepEricBurlison: Retrieved 25 posts
Saved posts to RepEricBurlison.json

=== Processing RepEricSorensen ===
Task started for RepEricSorensen: 202
RepEricSorensen: Retrieved 25 posts
Saved posts to RepEricSorensen.json

=== Processing RepEzell ===
Task started for RepEzell: 202
RepEzell: Retrieved 20 posts
Saved posts to RepEzell.json

=== Processing RepFedorchak ===
Task started for RepFedorchak: 202
RepFedorchak: Retrieved 25 posts
Saved posts to RepFedorchak.json

=== Processing RepFeenstra ===
Task started for RepFeenstra: 202
RepFeenstra: Retrieved 25 posts
Saved posts to RepFeenstra.json

=== Processing RepFine ===
Task started for RepFine: 202
RepFine: Retrieved 25 posts
Saved posts to RepFine.json

=== Processing RepFischbach ===
Task started for RepFischbach: 202
RepFischbach: Retrieved 25 posts
Saved posts to RepFischbach.json

=== Processing RepFitzgerald ===
Task started for RepFitzgerald: 202
RepFitzgerald: Retrieved 25 posts
Saved posts to RepFitzgerald.json

=== Processing RepFletcher ===
Task started for RepFletcher: 202
RepFletcher: Retrieved 25 posts
Saved posts to RepFletcher.json

=== Processing RepFrankLucas ===
Task started for RepFrankLucas: 202
RepFrankLucas: Retrieved 20 posts
Saved posts to RepFrankLucas.json

=== Processing RepFredKeller ===
Task started for RepFredKeller: 202
RepFredKeller: Retrieved 12 posts
Saved posts to RepFredKeller.json

=== Processing RepFredUpton ===
Task started for RepFredUpton: 202
RepFredUpton: Retrieved 12 posts
Saved posts to RepFredUpton.json

=== Processing RepFriedmanCA ===
Task started for RepFriedmanCA: 202
RepFriedmanCA: Retrieved 25 posts
Saved posts to RepFriedmanCA.json

=== Processing RepGLatimer ===
Task started for RepGLatimer: 202
RepGLatimer: Retrieved 25 posts
Saved posts to RepGLatimer.json

=== Processing RepGabeAmo ===
Task started for RepGabeAmo: 202
RepGabeAmo: Retrieved 25 posts
Saved posts to RepGabeAmo.json

=== Processing RepGabeVasquez ===
Task started for RepGabeVasquez: 202
RepGabeVasquez: Retrieved 25 posts
Saved posts to RepGabeVasquez.json

=== Processing RepGarbarino ===
Task started for RepGarbarino: 202
RepGarbarino: Retrieved 25 posts
Saved posts to RepGarbarino.json

=== Processing RepGarretGraves ===
Task started for RepGarretGraves: 202
RepGarretGraves: Retrieved 25 posts
Saved posts to RepGarretGraves.json

=== Processing RepGilCisneros ===
Task started for RepGilCisneros: 202
RepGilCisneros: Retrieved 25 posts
Saved posts to RepGilCisneros.json

=== Processing RepGlennIvey ===
Task started for RepGlennIvey: 202
RepGlennIvey: Retrieved 25 posts
Saved posts to RepGlennIvey.json

=== Processing RepGolden ===
Task started for RepGolden: 202
RepGolden: Retrieved 25 posts
Saved posts to RepGolden.json

=== Processing RepGonzalez ===
Task started for RepGonzalez: 202
RepGonzalez: Retrieved 25 posts
Saved posts to RepGonzalez.json

=== Processing RepGosar ===
Task started for RepGosar: 202
RepGosar: Retrieved 25 posts
Saved posts to RepGosar.json

=== Processing RepGregLandsman ===

In [ ]:
NON-HEALTH TWEETS FOR SECOND HALF:

In [39]:
import os
import json
import requests
import time

# ------------------------------------
# START AT RepWexton AND GO DOWNWARD
# ------------------------------------
handles_series = new_df["X Handle"].dropna()

if "AlLawsonJr" in handles_series.values:
    start_index = handles_series[handles_series == "AlLawsonJr"].index[0]
    usernames_to_process = new_df.loc[start_index:, "X Handle"].dropna().unique()
else:
    print("AlLawsonJr not found. Starting from top.")
    usernames_to_process = handles_series.unique()

# ------------------------------------
# LOOP THROUGH EACH POLITICIAN
# ------------------------------------
for username in usernames_to_process:

    print(f"\nProcessing politician: {username}")

    input_filename = f"{username}.json"
    output_filename = f"{username} Replies.json"

    # ------------------------------------
    # SKIP IF POSTS FILE DOESN'T EXIST
    # ------------------------------------
    if not os.path.exists(input_filename):
        print(f"Skipping {input_filename} (file not found)")
        continue

    # ------------------------------------
    # OPEN POSTS FILE
    # ------------------------------------
    with open(input_filename, "r", encoding="utf-8") as f:
        post_data = json.load(f)

    posts = post_data.get("data", {}).get("items", [])

    if not posts:
        print(f"No posts found in {input_filename}, skipping.")
        continue

    all_replies_output = []

    # ------------------------------------
    # FETCH REPLIES FOR EACH POST
    # ------------------------------------
    for post in posts:
        conversation_id = post.get("conversation_id")

        if not conversation_id:
            continue

        print(f"Fetching replies for {username} - {conversation_id}")

        replies_url = (
            f"{API_BASE_URL}{API_VERSION}/twitter/profile/"
            f"{username}/feed/posts/{conversation_id}/replies"
        )

        params = {
            "order_by": "date_desc",
            "max_page_size": 50,
            "access_token": API_AUTHORIZATION_TOKEN
        }

        response = requests.get(replies_url, params=params)

        if response.status_code == 200:
            replies_json = response.json()
            replies_items = replies_json.get("data", {}).get("items", [])

            all_replies_output.append({
                "conversation_id": conversation_id,
                "replies": replies_items
            })
        else:
            print(f"Failed for {conversation_id}: {response.status_code}")

        time.sleep(1)  # rate limit safety

    # ------------------------------------
    # SAVE OUTPUT
    # ------------------------------------
    if all_replies_output:

        final_output = {
            "politician": username,
            "posts": all_replies_output
        }

        with open(output_filename, "w", encoding="utf-8") as f:
            json.dump(final_output, f, indent=4)

        print(f"Saved: {output_filename}")
    else:
        print(f"No replies found for {username}")

print("\nAll politicians processed.")

Processing politician: AlLawsonJr
Fetching replies for AlLawsonJr - 1553127999846989826
Fetching replies for AlLawsonJr - 1553473426085527554
Fetching replies for AlLawsonJr - 1554565066263089153
Fetching replies for AlLawsonJr - 1554565214229745664
Fetching replies for AlLawsonJr - 1554626594903396352
Fetching replies for AlLawsonJr - 1555186403360768001
Fetching replies for AlLawsonJr - 1559534224981491712
Fetching replies for AlLawsonJr - 1562036343005380608
Fetching replies for AlLawsonJr - 1570031195911749632
Fetching replies for AlLawsonJr - 1578527816831811584
Fetching replies for AlLawsonJr - 1580180550161047552
Fetching replies for AlLawsonJr - 1580181288723525633
Saved: AlLawsonJr Replies.json

Processing politician: AlbioSiresNJ
Skipping AlbioSiresNJ.json (file not found)

Processing politician: Andy_Levin
Fetching replies for Andy_Levin - 1484901000435707908
Fetching replies for Andy_Levin - 1493618115355320332
Fetching replies for Andy_Levin - 1496506383642079236
Fetching replies for Andy_Levin - 1498760723920531456
Fetching replies for Andy_Levin - 1501716858931712009
Fetching replies for Andy_Levin - 1507411997872336897
Fetching replies for Andy_Levin - 1508803807794413569
Fetching replies for Andy_Levin - 1508837211931881477
Fetching replies for Andy_Levin - 1511352393778315265
Fetching replies for Andy_Levin - 1511377399480467464
Fetching replies for Andy_Levin - 1513929537444360197
Fetching replies for Andy_Levin - 1514709121119014916
Fetching replies for Andy_Levin - 1516820833020399620
Fetching replies for Andy_Levin - 1516910368156704768
Fetching replies for Andy_Levin - 1516910521781571586
Fetching replies for Andy_Levin - 1516911210947661824
Fetching replies for Andy_Levin - 1516912825410666498
Fetching replies for Andy_Levin - 1516913976210296833
Fetching replies for Andy_Levin - 1523342645166321665
Fetching replies for Andy_Levin - 1524797214081667073
Fetching replies for Andy_Levin - 1525887893910261761
Fetching replies for Andy_Levin - 1527064391044169739
Fetching replies for Andy_Levin - 1532163052518486016
Fetching replies for Andy_Levin - 1533048417387220993
Fetching replies for Andy_Levin - 1535773754005114880
Saved: Andy_Levin Replies.json

Processing politician: Axne4Congress
Fetching replies for Axne4Congress - 1530907916710072320
Fetching replies for Axne4Congress - 1531986201271488515
Fetching replies for Axne4Congress - 1539661998559899649
Fetching replies for Axne4Congress - 1545447368123830273
Fetching replies for Axne4Congress - 1546856918555115520
Fetching replies for Axne4Congress - 1547618451782377472
Fetching replies for Axne4Congress - 1552431639254401028
Fetching replies for Axne4Congress - 1552741935042920449
Fetching replies for Axne4Congress - 1553050970430394369
Fetching replies for Axne4Congress - 1553383410864795649
Fetching replies for Axne4Congress - 1556308434227630082
Fetching replies for Axne4Congress - 1557405281608409089
Fetching replies for Axne4Congress - 1561111458200576001
Fetching replies for Axne4Congress - 1564307799760375809
Fetching replies for Axne4Congress - 1565067643748581377
Fetching replies for Axne4Congress - 1565770281313902592
Fetching replies for Axne4Congress - 1566470768850001921
Fetching replies for Axne4Congress - 1569818197473333251
Fetching replies for Axne4Congress - 1570140330954997762
Fetching replies for Axne4Congress - 1571244068855857152
Fetching replies for Axne4Congress - 1573702547885506560
Fetching replies for Axne4Congress - 1574543028383256577
Fetching replies for Axne4Congress - 1575530124451381249
Fetching replies for Axne4Congress - 1577019463995887616
Fetching replies for Axne4Congress - 1578113925815554048
Saved: Axne4Congress Replies.json

Processing politician: BHigginsBflo
Fetching replies for BHigginsBflo - 1489706880318459911
Fetching replies for BHigginsBflo - 1490763994340155396
Fetching replies for BHigginsBflo - 1498864421434585094
Fetching replies for BHigginsBflo - 1507077288084578307
Fetching replies for BHigginsBflo - 1509241548893995018
Fetching replies for BHigginsBflo - 1511772877556748295
Fetching replies for BHigginsBflo - 1523773553996296193
Fetching replies for BHigginsBflo - 1539324532816756736
Fetching replies for BHigginsBflo - 1550199448826945536
Fetching replies for BHigginsBflo - 1556636319987679233
Fetching replies for BHigginsBflo - 1564599568657956871
Fetching replies for BHigginsBflo - 1564969319569686528
Fetching replies for BHigginsBflo - 1572716099661086720
Fetching replies for BHigginsBflo - 1579925660164050945
Fetching replies for BHigginsBflo - 1582804770469056512
Fetching replies for BHigginsBflo - 1587818899525242880
Fetching replies for BHigginsBflo - 1590059564996534272
Fetching replies for BHigginsBflo - 1590398932324323329
Fetching replies for BHigginsBflo - 1590460757929447424
Fetching replies for BHigginsBflo - 1592168697481031680
Fetching replies for BHigginsBflo - 1592593313005473793
Fetching replies for BHigginsBflo - 1593311263198777344
Fetching replies for BHigginsBflo - 1594754812452933632
Fetching replies for BHigginsBflo - 1594764836105293825
Fetching replies for BHigginsBflo - 1595089211090149377
Saved: BHigginsBflo Replies.json

Processing politician: BennieGThompson
Fetching replies for BennieGThompson - 1490764257499172871
Fetching replies for BennieGThompson - 1549394522215522304
Fetching replies for BennieGThompson - 1626309932730515457
Fetching replies for BennieGThompson - 1715426237236047972
Fetching replies for BennieGThompson - 1720860879904809097
Fetching replies for BennieGThompson - 1770489099301818685
Fetching replies for BennieGThompson - 1800292054913753555
Fetching replies for BennieGThompson - 1833520817663095192
Fetching replies for BennieGThompson - 1848744602330636730
Fetching replies for BennieGThompson - 1878911288656662723
Fetching replies for BennieGThompson - 1884335660737393056
Fetching replies for BennieGThompson - 1894577481237037408
Fetching replies for BennieGThompson - 1899508756934787156
Fetching replies for BennieGThompson - 1902034765534130252
Fetching replies for BennieGThompson - 1915163106881241430
Fetching replies for BennieGThompson - 1920546852404867502
Fetching replies for BennieGThompson - 1925244308329812478
Fetching replies for BennieGThompson - 1925666035950063742
Fetching replies for BennieGThompson - 1930317377574428891
Fetching replies for BennieGThompson - 1930701158081073204
Fetching replies for BennieGThompson - 1937205718446408025
Fetching replies for BennieGThompson - 1940097656405029248
Fetching replies for BennieGThompson - 1940529725916827884
Fetching replies for BennieGThompson - 1940815979883516244
Fetching replies for BennieGThompson - 1944854664542838836
Saved: BennieGThompson Replies.json

Processing politician: BettyMcCollum04
Fetching replies for BettyMcCollum04 - 1505240718012526593
Fetching replies for BettyMcCollum04 - 1516496352561270789
Fetching replies for BettyMcCollum04 - 1518302755361808386
Fetching replies for BettyMcCollum04 - 1519407490290573314
Fetching replies for BettyMcCollum04 - 1527315078131097600
Fetching replies for BettyMcCollum04 - 1528094274386022400
Fetching replies for BettyMcCollum04 - 1536069072227549185
Fetching replies for BettyMcCollum04 - 1537858614127476736
Fetching replies for BettyMcCollum04 - 1543367664386686976
Fetching replies for BettyMcCollum04 - 1550856007235948546
Fetching replies for BettyMcCollum04 - 1555665013066665985
Fetching replies for BettyMcCollum04 - 1556644786131566592
Fetching replies for BettyMcCollum04 - 1557020641295060998
Fetching replies for BettyMcCollum04 - 1563316864717099009
Fetching replies for BettyMcCollum04 - 1563907003486912514
Fetching replies for BettyMcCollum04 - 1565457866844213254
Fetching replies for BettyMcCollum04 - 1566215464434278402
Fetching replies for BettyMcCollum04 - 1567294072313843712
Fetching replies for BettyMcCollum04 - 1568331910106910720
Fetching replies for BettyMcCollum04 - 1570141275860643840
Fetching replies for BettyMcCollum04 - 1571915272121769984
Fetching replies for BettyMcCollum04 - 1575118881475141634
Fetching replies for BettyMcCollum04 - 1575165121311014925
Fetching replies for BettyMcCollum04 - 1578835873285677062
Fetching replies for BettyMcCollum04 - 1587902241234632710
Saved: BettyMcCollum04 Replies.json

Processing politician: BillPoseyFL
Fetching replies for BillPoseyFL - 1481743158237138945
Fetching replies for BillPoseyFL - 1534620485778014208
Fetching replies for BillPoseyFL - 1720483056639701123
Fetching replies for BillPoseyFL - 1722681206842802644
Fetching replies for BillPoseyFL - 1726637554844475637
Fetching replies for BillPoseyFL - 1745852685297889510
Fetching replies for BillPoseyFL - 1777763018291429805
Fetching replies for BillPoseyFL - 1778077863272390723
Fetching replies for BillPoseyFL - 1781004473801855449
Fetching replies for BillPoseyFL - 1836072295560786097
Fetching replies for BillPoseyFL - 1965479881913098661
Saved: BillPoseyFL Replies.json

Processing politician: BobbyLRush
Fetching replies for BobbyLRush - 1482024751954636803
Fetching replies for BobbyLRush - 1484326925740875781
Fetching replies for BobbyLRush - 1486758866515906563
Fetching replies for BobbyLRush - 1489735940289482762
Fetching replies for BobbyLRush - 1490831726163148800
Fetching replies for BobbyLRush - 1491501404283969546
Fetching replies for BobbyLRush - 1495861687886528512
Fetching replies for BobbyLRush - 1500926425154695177
Fetching replies for BobbyLRush - 1502345250211352578
Fetching replies for BobbyLRush - 1517503502095953923
Fetching replies for BobbyLRush - 1519060091860828161
Fetching replies for BobbyLRush - 1521217374501879810
Fetching replies for BobbyLRush - 1521217374501879810
Fetching replies for BobbyLRush - 1521217374501879810
Fetching replies for BobbyLRush - 1522674608599707650
Fetching replies for BobbyLRush - 1525166125587349505
Fetching replies for BobbyLRush - 1534179510081540096
Fetching replies for BobbyLRush - 1539945513759514624
Fetching replies for BobbyLRush - 1540088709520973824
Fetching replies for BobbyLRush - 1540348119753396227
Fetching replies for BobbyLRush - 1545461936313274369
Fetching replies for BobbyLRush - 1546540448554049543
Fetching replies for BobbyLRush - 1548017878074474497
Fetching replies for BobbyLRush - 1548027518816464898
Fetching replies for BobbyLRush - 1554831167760658448
Saved: BobbyLRush Replies.json

Processing politician: BobbyScott
Fetching replies for BobbyScott - 1485985622057754624
Fetching replies for BobbyScott - 1488245775767412737
Fetching replies for BobbyScott - 1494358723422306308
Fetching replies for BobbyScott - 1501642561630396427
Fetching replies for BobbyScott - 1506642487078756362
Fetching replies for BobbyScott - 1511398609509662723
Fetching replies for BobbyScott - 1521851385301671936
Fetching replies for BobbyScott - 1539386830889619456
Fetching replies for BobbyScott - 1549837355934171136
Fetching replies for BobbyScott - 1549837355934171136
Fetching replies for BobbyScott - 1552386047664918528
Fetching replies for BobbyScott - 1560048486627872769
Fetching replies for BobbyScott - 1567341959483740167
Fetching replies for BobbyScott - 1571956832779882496
Fetching replies for BobbyScott - 1575148249840771074
Fetching replies for BobbyScott - 1575148249840771074
Fetching replies for BobbyScott - 1580238028659834880
Fetching replies for BobbyScott - 1588627162114183168
Fetching replies for BobbyScott - 1614024316588367874
Fetching replies for BobbyScott - 1614413923960377344
Fetching replies for BobbyScott - 1637250401794678784
Fetching replies for BobbyScott - 1655022404123459586
Fetching replies for BobbyScott - 1719766390008107316
Fetching replies for BobbyScott - 1726621596897689651
Fetching replies for BobbyScott - 1730681183346864307
Saved: BobbyScott Replies.json

Processing politician: BradSherman
Fetching replies for BradSherman - 1499444396630106115
Fetching replies for BradSherman - 1501330939154214913
Fetching replies for BradSherman - 1570943564410130434
Fetching replies for BradSherman - 1572690001510690816
Fetching replies for BradSherman - 1613727800757739520
Fetching replies for BradSherman - 1665771894258188297
Fetching replies for BradSherman - 1695196566376558711
Fetching replies for BradSherman - 1750664918037155845
Fetching replies for BradSherman - 1765185164974453115
Fetching replies for BradSherman - 1778487881515909247
Fetching replies for BradSherman - 1779981181137613252
Fetching replies for BradSherman - 1788666311515476095
Fetching replies for BradSherman - 1799224011278217650
Fetching replies for BradSherman - 1799224011278217650
Fetching replies for BradSherman - 1833200530987843998
Fetching replies for BradSherman - 1846962689437741277
Fetching replies for BradSherman - 1849245662073741584
Fetching replies for BradSherman - 1851353201129267572
Fetching replies for BradSherman - 1859639825491689959
Fetching replies for BradSherman - 1868772869419020581
Fetching replies for BradSherman - 1874466418487656836
Fetching replies for BradSherman - 1877150401230766091
Fetching replies for BradSherman - 1883221680744694137
Fetching replies for BradSherman - 1885964980320682415
Fetching replies for BradSherman - 1886517091626344781
Saved: BradSherman Replies.json

Processing politician: Call_Me_Dutch
Fetching replies for Call_Me_Dutch - 1480925492643569666
Fetching replies for Call_Me_Dutch - 1488559442278948868
Fetching replies for Call_Me_Dutch - 1488559442278948868
Fetching replies for Call_Me_Dutch - 1498382321048764418
Fetching replies for Call_Me_Dutch - 1501949602752172035
Fetching replies for Call_Me_Dutch - 1502004322816638976
Fetching replies for Call_Me_Dutch - 1506679344764178436
Fetching replies for Call_Me_Dutch - 1528829473038155776
Fetching replies for Call_Me_Dutch - 1539689387516198915
Fetching replies for Call_Me_Dutch - 1539967111325433856
Fetching replies for Call_Me_Dutch - 1542550540382601216
Fetching replies for Call_Me_Dutch - 1542882772838121472
Fetching replies for Call_Me_Dutch - 1542886320653090823
Fetching replies for Call_Me_Dutch - 1542889863715880960
Fetching replies for Call_Me_Dutch - 1549397841633853446
Fetching replies for Call_Me_Dutch - 1551645548700221447
Fetching replies for Call_Me_Dutch - 1552696360004091906
Fetching replies for Call_Me_Dutch - 1557383658872492035
Fetching replies for Call_Me_Dutch - 1558178311402127360
Fetching replies for Call_Me_Dutch - 1563245661184671744
Fetching replies for Call_Me_Dutch - 1563245661184671744
Fetching replies for Call_Me_Dutch - 1567931354347716610
Fetching replies for Call_Me_Dutch - 1585271769182732288
Fetching replies for Call_Me_Dutch - 1587810841449078786
Fetching replies for Call_Me_Dutch - 1599883670105780225
Saved: Call_Me_Dutch Replies.json

Processing politician: CarlForAlabama
Fetching replies for CarlForAlabama - 1481737775951065095
Fetching replies for CarlForAlabama - 1848448283439743132
Saved: CarlForAlabama Replies.json

Processing politician: ColinAllredTX
Fetching replies for ColinAllredTX - 1482419561882427398
Fetching replies for ColinAllredTX - 1488213346851737600
Fetching replies for ColinAllredTX - 1508185844997402633
Fetching replies for ColinAllredTX - 1525183511560331269
Fetching replies for ColinAllredTX - 1553125980948021249
Fetching replies for ColinAllredTX - 1558213401670828033
Fetching replies for ColinAllredTX - 1562804536955535361
Fetching replies for ColinAllredTX - 1570095135089741824
Fetching replies for ColinAllredTX - 1575903031451062272
Fetching replies for ColinAllredTX - 1598453696203051018
Fetching replies for ColinAllredTX - 1604937769809223685
Fetching replies for ColinAllredTX - 1614655309686898690
Fetching replies for ColinAllredTX - 1642926937994559488
Fetching replies for ColinAllredTX - 1643300446298071047
Fetching replies for ColinAllredTX - 1674236996611629056
Fetching replies for ColinAllredTX - 1675902970754465792
Fetching replies for ColinAllredTX - 1675902970754465792
Fetching replies for ColinAllredTX - 1683996169888841728
Fetching replies for ColinAllredTX - 1685690889698471936
Fetching replies for ColinAllredTX - 1687886184352276480
Fetching replies for ColinAllredTX - 1696900588636868807
Fetching replies for ColinAllredTX - 1699799684569842080
Fetching replies for ColinAllredTX - 1704541191490998368
Fetching replies for ColinAllredTX - 1708859394295820543
Fetching replies for ColinAllredTX - 1711052735406030862
Saved: ColinAllredTX Replies.json

Processing politician: CongBoyle
Fetching replies for CongBoyle - 1938610255539195983
Fetching replies for CongBoyle - 1940036972606562554
Fetching replies for CongBoyle - 1940495439767187745
Fetching replies for CongBoyle - 1940822144084066391
Fetching replies for CongBoyle - 1944544740231290880
Fetching replies for CongBoyle - 1944884282884862058
Fetching replies for CongBoyle - 1950599889538154809
Fetching replies for CongBoyle - 1950645324948623723
Fetching replies for CongBoyle - 1950666175987249214
Fetching replies for CongBoyle - 1953189235508523032
Fetching replies for CongBoyle - 1953189235508523032
Fetching replies for CongBoyle - 1956022011869716799
Fetching replies for CongBoyle - 1956390342275510365
Fetching replies for CongBoyle - 1962967130917257220
Fetching replies for CongBoyle - 1973139074325291241
Fetching replies for CongBoyle - 1973423500971868667
Fetching replies for CongBoyle - 1975211088795799944
Fetching replies for CongBoyle - 1975274872935760052
Fetching replies for CongBoyle - 1976328223320392172
Fetching replies for CongBoyle - 1976753760253690113
Fetching replies for CongBoyle - 1978856094400200879
Fetching replies for CongBoyle - 1978883878396801284
Fetching replies for CongBoyle - 1980258714088001642
Fetching replies for CongBoyle - 1980696406563426750
Fetching replies for CongBoyle - 1982850399229866194
Saved: CongBoyle Replies.json

Processing politician: CongMikeSimpson
Fetching replies for CongMikeSimpson - 1493996673143504898
Fetching replies for CongMikeSimpson - 1499904040485851137
Fetching replies for CongMikeSimpson - 1543026338520391680
Fetching replies for CongMikeSimpson - 1557057670036590592
Fetching replies for CongMikeSimpson - 1620565389561458688
Fetching replies for CongMikeSimpson - 1620943394108477440
Fetching replies for CongMikeSimpson - 1623724805152460800
Fetching replies for CongMikeSimpson - 1785078032249606281
Fetching replies for CongMikeSimpson - 1793699702820790769
Fetching replies for CongMikeSimpson - 1794062220596326859
Fetching replies for CongMikeSimpson - 1803828049244291134
Fetching replies for CongMikeSimpson - 1821599852431864251
Fetching replies for CongMikeSimpson - 1825895277972095140
Fetching replies for CongMikeSimpson - 1826620421791248705
Fetching replies for CongMikeSimpson - 1829893356660330548
Fetching replies for CongMikeSimpson - 1846883019484758129
Fetching replies for CongMikeSimpson - 1849472687829131291
Fetching replies for CongMikeSimpson - 1867591607899373869
Fetching replies for CongMikeSimpson - 1892311813624414480
Fetching replies for CongMikeSimpson - 1895220438814556551
Fetching replies for CongMikeSimpson - 1899561682650755296
Fetching replies for CongMikeSimpson - 1913018207113543764
Fetching replies for CongMikeSimpson - 1913239122077950293
Fetching replies for CongMikeSimpson - 1927446007140298928
Fetching replies for CongMikeSimpson - 1928564432407326950
Saved: CongMikeSimpson Replies.json

Processing politician: CongressmanKean
Fetching replies for CongressmanKean - 1697368463507886252
Fetching replies for CongressmanKean - 1719088668193775765
Fetching replies for CongressmanKean - 1763689420278862125
Fetching replies for CongressmanKean - 1782886507281371415
Fetching replies for CongressmanKean - 1797631160702697497
Fetching replies for CongressmanKean - 1799126811789365713
Fetching replies for CongressmanKean - 1844474479507849274
Fetching replies for CongressmanKean - 1860322414523306098
Fetching replies for CongressmanKean - 1937598307188252796
Fetching replies for CongressmanKean - 1944396403091894775

In [2]:
# 1. Imports
import os
import json
import pandas as pd

# 2. Storage container
master_data = {}

# 3. Loop through folder JSONs
for filename in os.listdir():
    if not filename.endswith(".json"):
        continue

    with open(filename, "r", encoding="utf-8") as f:
        data = json.load(f)

    # ---------- HEALTH TWEETS ----------
    if "Block" in filename and "Replies" not in filename:

        username = filename.split(" Block ")[0]
        block = filename.split("Block ")[1].replace(".json", "")

        posts = data.get("data", {}).get("items", [])

        for post in posts:

            conversation_id = post.get("conversation_id")

            key = (username, conversation_id)

            master_data[key] = {
                "username": username,
                "block": block,
                "tweet_type": "health",
                "tweet_text": post.get("text"),
                "created_time": post.get("created_time"),
                "favorite_count": post.get("favorite_count"),
                "reply_count": post.get("reply_count"),
                "retweet_count": post.get("retweet_count"),
                "quote_count": post.get("quote_count"),
                "view_count": post.get("view_count"),
                "replies": []
            }

    # ---------- HEALTH REPLIES ----------
    elif "Block" in filename and "Replies" in filename:

        username = filename.split(" Block ")[0]
        block = filename.split("Block ")[1].replace(" Replies.json", "")

        posts = data.get("posts", [])

        for post in posts:

            conversation_id = post.get("conversation_id")
            replies = post.get("replies", [])

            key = (username, conversation_id)

            if key in master_data:
                for reply in replies:
                    master_data[key]["replies"].append(reply.get("text"))

    # ---------- NON-HEALTH TWEETS ----------
    elif "Block" not in filename and "Replies" not in filename:

        username = filename.replace(".json", "")

        posts = data.get("data", {}).get("items", [])

        for post in posts:

            conversation_id = post.get("conversation_id")

            key = (username, conversation_id)

            master_data[key] = {
                "username": username,
                "block": None,
                "tweet_type": "non_health",
                "tweet_text": post.get("text"),
                "created_time": post.get("created_time"),
                "favorite_count": post.get("favorite_count"),
                "reply_count": post.get("reply_count"),
                "retweet_count": post.get("retweet_count"),
                "quote_count": post.get("quote_count"),
                "view_count": post.get("view_count"),
                "replies": []
            }

    # ---------- NON-HEALTH REPLIES ----------
    elif "Replies" in filename and "Block" not in filename:

        username = filename.replace(" Replies.json", "")

        posts = data.get("posts", [])

        for post in posts:

            conversation_id = post.get("conversation_id")
            replies = post.get("replies", [])

            key = (username, conversation_id)

            if key in master_data:
                for reply in replies:
                    master_data[key]["replies"].append(reply.get("text"))

# 4. Convert dictionary → dataframe (ONE ROW PER TWEET OR REPLY)

rows = []

for key, value in master_data.items():

    # ----- Add the original tweet row -----
    rows.append({
        "username": value["username"],
        "block": value["block"],
        "tweet_type": value["tweet_type"],
        "conversation_id": key[1],
        "text": value["tweet_text"],
        "row_type": "tweet",
        "created_time": value["created_time"],
        "favorite_count": value["favorite_count"],
        "reply_count": value["reply_count"],
        "retweet_count": value["retweet_count"],
        "quote_count": value["quote_count"],
        "view_count": value["view_count"]
    })

    # ----- Add one row per reply -----
    for reply in value["replies"]:
        if reply and reply.strip() != "":
            rows.append({
                "username": value["username"],
                "block": value["block"],
                "tweet_type": value["tweet_type"],
                "conversation_id": key[1],
                "text": reply,
                "row_type": "reply",
                "created_time": None,
                "favorite_count": None,
                "reply_count": None,
                "retweet_count": None,
                "quote_count": None,
                "view_count": None
            })

final_df = pd.DataFrame(rows)

# 5. Save output
final_df.to_csv("ALL_TWEETS_MASTER.csv", index=False)

print("Master dataset created!")

Master dataset created!

In [17]:
all_tweets = pd.read_csv("ALL_TWEETS_MASTER.csv")
all_tweets.head()

,username,block,tweet_type,conversation_id,text,row_type,created_time,favorite_count,reply_count,retweet_count,quote_count,view_count
0,RepGwenMoore,2B,health,1940143080637964748,What did the American people buy with the $4 t...,tweet,2025-07-01T20:18:51,22.0,12.0,14.0,2.0,1636.0
1,RepGwenMoore,2B,health,1940143080637964748,@RepGwenMoore https://t.co/g3hDlL5JSW,reply,NaN,NaN,NaN,NaN,NaN,NaN
2,RepGwenMoore,2B,health,1940143080637964748,@RepGwenMoore Yawn.,reply,NaN,NaN,NaN,NaN,NaN,NaN
3,RepGwenMoore,2B,health,1940143080637964748,THANK YOU for pointing out that removing the u...,reply,NaN,NaN,NaN,NaN,NaN,NaN
4,RepGwenMoore,2B,health,1940143080637964748,@RepGwenMoore if your a dorky lookin guy you ...,reply,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
all_tweets["username"].nunique()

#out of the 713 initial politicians, only 658 ended up included. This means that 55 politicians had no tweets that matched the health keywords

658

In [21]:
all_tweets = all_tweets.drop_duplicates(subset=["conversation_id", "text"])

In [9]:
len(all_tweets)

207956

In [16]:
all_tweets.to_csv("ALL_TWEETS_MASTER_FINAL.csv", index=False)

In [61]:
# takes a 2 column csv, adds a third column
#first column is ID, second column is the text 
#label studio then allows you to give it a labeling structure (binary structure)
#once you get ~10-15 positives and negatives and starts running a model and gives the ones that are hard to classify, would have to classify myself
# theres an option to do a test, of the performance of the model 
#should't be a final model, should do separate model on python but still useful to tell you which rows are most useful and how well the class. model is working
#multiclass labeling where also labeling sentiment along with the misinformation. before that, need to know if the replies are replying to the misinformation or not. do classification model first for main tweets, and once that performs well, take that classification, put it in as part of the text 
# 3 dolumns : conversatin id, text, 0 or 1 to label misinformation
#replies i want to look at sentiment
#were they part of a controversy, covid, etc are things i may also end up labeling for
# need at about over 80% accuracy

In [23]:
tweets_df = all_tweets[
    (all_tweets["row_type"] == "tweet") & (all_tweets["tweet_type"] == "health")
][["conversation_id", "text"]].copy()

tweets_label = tweets_df.copy()

# Add ID column
tweets_label["id"] = range(1, len(tweets_label) + 1)

# Keep only needed columns
tweets_label = tweets_label[["id", "conversation_id", "text"]]

# Save to CSV
tweets_label.to_csv("tweet_labeling.csv", index=False)

In [25]:
#create replies only df:

replies_df = all_tweets[
    (all_tweets["row_type"] == "reply") & (all_tweets["tweet_type"] == "health")
][["conversation_id", "text"]].copy()

replies_label = replies_df.copy()

replies_label["id"] = range(1, len(replies_label) + 1)

replies_label = replies_label[["id", "conversation_id", "text"]]

replies_label.to_csv("reply_labeling.csv", index=False)